<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>QSBS Practical 2 — Estimating parameters and fitting distributions Answers</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="QSBS_2_estimating_parameters_answers_files/libs/clipboard/clipboard.min.js"></script>
<script src="QSBS_2_estimating_parameters_answers_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="QSBS_2_estimating_parameters_answers_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="QSBS_2_estimating_parameters_answers_files/libs/quarto-html/popper.min.js"></script>
<script src="QSBS_2_estimating_parameters_answers_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="QSBS_2_estimating_parameters_answers_files/libs/quarto-html/anchor.min.js"></script>
<link href="QSBS_2_estimating_parameters_answers_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="QSBS_2_estimating_parameters_answers_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="QSBS_2_estimating_parameters_answers_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="QSBS_2_estimating_parameters_answers_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="QSBS_2_estimating_parameters_answers_files/libs/bootstrap/bootstrap-94053d6e10daeb31c4957f2bd90b11ca.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#exercise-1" id="toc-exercise-1" class="nav-link" data-scroll-target="#exercise-1">Exercise 1</a>
  <ul class="collapse">
  <li><a href="#answer" id="toc-answer" class="nav-link" data-scroll-target="#answer">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-2" id="toc-exercise-2" class="nav-link" data-scroll-target="#exercise-2">Exercise 2</a>
  <ul class="collapse">
  <li><a href="#answer-1" id="toc-answer-1" class="nav-link" data-scroll-target="#answer-1">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-3" id="toc-exercise-3" class="nav-link" data-scroll-target="#exercise-3">Exercise 3</a>
  <ul class="collapse">
  <li><a href="#answer-2" id="toc-answer-2" class="nav-link" data-scroll-target="#answer-2">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-4" id="toc-exercise-4" class="nav-link" data-scroll-target="#exercise-4">Exercise 4</a>
  <ul class="collapse">
  <li><a href="#answer-3" id="toc-answer-3" class="nav-link" data-scroll-target="#answer-3">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-5" id="toc-exercise-5" class="nav-link" data-scroll-target="#exercise-5">Exercise 5</a>
  <ul class="collapse">
  <li><a href="#answer-4" id="toc-answer-4" class="nav-link" data-scroll-target="#answer-4">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-6" id="toc-exercise-6" class="nav-link" data-scroll-target="#exercise-6">Exercise 6</a>
  <ul class="collapse">
  <li><a href="#answer-5" id="toc-answer-5" class="nav-link" data-scroll-target="#answer-5">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-7" id="toc-exercise-7" class="nav-link" data-scroll-target="#exercise-7">Exercise 7</a>
  <ul class="collapse">
  <li><a href="#answer-6" id="toc-answer-6" class="nav-link" data-scroll-target="#answer-6">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-8" id="toc-exercise-8" class="nav-link" data-scroll-target="#exercise-8">Exercise 8</a>
  <ul class="collapse">
  <li><a href="#answer-7" id="toc-answer-7" class="nav-link" data-scroll-target="#answer-7">Answer</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">QSBS Practical 2 — Estimating parameters and fitting distributions Answers</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In the previous practical we <em>chose</em> the parameters of a distribution ourselves. Here we turn the question around: given a set of measurements, which distribution, with which parameter values, describes these data best?</p>
<p>We are again using data from the <code>MASS</code> package, which also contains the function <code>fitdistr()</code>, so we make sure this package is loaded.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The survival times in <code>Melanoma</code> are recorded in days; we convert them to years, which makes all output easier to read.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>surv_years <span class="ot">&lt;-</span> Melanoma<span class="sc">$</span>time <span class="sc">/</span> <span class="fl">365.25</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="exercise-1" class="level1">
<h1>Exercise 1</h1>
<p>We toss a coin 100 times and observe 60 heads. The number of heads follows a binomial distribution with <code>size = 100</code> and an unknown parameter <code>p</code>.</p>
<ol type="a">
<li>Calculate the probability of this result if <code>p = 0.5</code>, and the probability if <code>p = 0.6</code>. Which of the two values of <code>p</code> makes the observed data more plausible?</li>
<li>Now treat this probability as a function of <code>p</code>: calculate it for a fine grid of values of <code>p</code> between 0 and 1 and plot the result. This curve is the <strong>likelihood function</strong>.</li>
<li>Read the maximum off the graph and find it exactly with <code>which.max()</code>. Compare it with the analytical maximum likelihood estimator for the binomial distribution, <span class="math inline">\(\hat{p} = \bar{x}/n\)</span> (Dormann, Sect. 3.3.3.3).</li>
<li>Plot the <em>log</em>-likelihood over the same grid. Does the maximum lie at the same place? Explain why taking the logarithm cannot move the maximum, and why we nevertheless prefer to work with log-likelihoods.</li>
</ol>
<section id="answer" class="level2">
<h2 class="anchored" data-anchor-id="answer">Answer</h2>
<p><strong>a.</strong> Both numbers come out of the same function, <code>dbinom()</code>, with the data fixed at 60 successes out of 100:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">p_0.5 =</span> <span class="fu">dbinom</span>(<span class="dv">60</span>, <span class="at">size =</span> <span class="dv">100</span>, <span class="at">prob =</span> <span class="fl">0.5</span>),</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_0.6 =</span> <span class="fu">dbinom</span>(<span class="dv">60</span>, <span class="at">size =</span> <span class="dv">100</span>, <span class="at">prob =</span> <span class="fl">0.6</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     p_0.5      p_0.6 
0.01084387 0.08121914 </code></pre>
</div>
</div>
<p>Observing 60 heads is about eight times more probable under <code>p = 0.6</code> (0.081) than under <code>p = 0.5</code> (0.011). We say that <code>p = 0.6</code> has the higher <strong>likelihood</strong> given these data. Note that this is exactly the same number as the probability — the likelihood is not a new calculation, it is the same quantity read in the other direction: <span class="math inline">\(\mathcal{L}(\theta \mid \mathrm{data}) = P(\mathrm{data} \mid \theta)\)</span>.</p>
<p><strong>b.</strong> Now we let <code>p</code> run over a grid and keep the data fixed:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>p_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.001</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>likelihood <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(<span class="dv">60</span>, <span class="at">size =</span> <span class="dv">100</span>, <span class="at">prob =</span> p_grid)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p_grid, likelihood, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"p (probability of heads)"</span>, <span class="at">ylab =</span> <span class="st">"likelihood L(p | 60 heads)"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fl">0.6</span>, <span class="at">col =</span> <span class="st">"firebrick"</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.6</span>), <span class="fu">dbinom</span>(<span class="dv">60</span>, <span class="dv">100</span>, <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.6</span>)), <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"steelblue"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">0.5</span>, <span class="fu">dbinom</span>(<span class="dv">60</span>, <span class="dv">100</span>, <span class="fl">0.5</span>), <span class="at">labels =</span> <span class="st">"p = 0.5"</span>, <span class="at">pos =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_2_estimating_parameters_answers_files/figure-html/ex1-likelihood-curve-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Likelihood of p, given 60 heads out of 100 tosses.</figcaption>
</figure>
</div>
</div>
</div>
<p>Watch the axes carefully. In the previous practical the x-axis carried the <em>data</em> (<code>k</code>) and the parameter was fixed; here the x-axis carries the <em>parameter</em> and the data are fixed. Both curves are produced by <code>dbinom()</code>, but they answer different questions. Also note that the likelihood curve is not a probability distribution: it does not integrate to 1 over <code>p</code>.</p>
<p><strong>c.</strong> The maximum:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">grid_maximum =</span> p_grid[<span class="fu">which.max</span>(likelihood)],</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">analytical_MLE =</span> <span class="dv">60</span> <span class="sc">/</span> <span class="dv">100</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  grid_maximum analytical_MLE 
           0.6            0.6 </code></pre>
</div>
</div>
<p>The maximum of the curve lies at <code>p = 0.6</code>, precisely the value given by the analytical maximum likelihood estimator <span class="math inline">\(\hat{p} = \bar{x}/n = 60/100\)</span>. The estimate is exactly the observed proportion of heads, which is reassuringly close to common sense: the parameter that makes the data most plausible is the one that reproduces the observed frequency.</p>
<p><strong>d.</strong> The log-likelihood:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>log_likelihood <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(<span class="dv">60</span>, <span class="at">size =</span> <span class="dv">100</span>, <span class="at">prob =</span> p_grid, <span class="at">log =</span> <span class="cn">TRUE</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p_grid, log_likelihood, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">60</span>, <span class="dv">0</span>),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"p (probability of heads)"</span>, <span class="at">ylab =</span> <span class="st">"log-likelihood"</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fl">0.6</span>, <span class="at">col =</span> <span class="st">"firebrick"</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_2_estimating_parameters_answers_files/figure-html/ex1-loglikelihood-curve-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Log-likelihood of p for the same data. The maximum is in the same place.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>p_grid[<span class="fu">which.max</span>(log_likelihood)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6</code></pre>
</div>
</div>
<p>The maximum is at exactly the same place. The logarithm is a <strong>monotonically increasing</strong> function: if <span class="math inline">\(a &gt; b\)</span> then <span class="math inline">\(\ln(a) &gt; \ln(b)\)</span>. It can therefore stretch and squeeze the curve, but it cannot change which value of <code>p</code> is the largest. What we gain is numerical: as we will see in the next exercise, the likelihood of a real data set is a product of hundreds of small numbers and rapidly becomes too small for a computer to represent, whereas the log-likelihood is a sum of manageable numbers. This is why virtually all software reports <span class="math inline">\(\ell\)</span> rather than <span class="math inline">\(\mathcal{L}\)</span>.</p>
</section>
</section>
<section id="exercise-2" class="level1">
<h1>Exercise 2</h1>
<p>We now move from one data point to a whole data set: the survival times <code>surv_years</code> of the 205 melanoma patients.</p>
<ol type="a">
<li>Make a histogram of <code>surv_years</code> and decide, by eye, whether a normal distribution is a plausible candidate.</li>
<li>Fit a normal distribution to these data with <code>fitdistr()</code>. Report the two parameter estimates and their standard errors, and compare the estimates with <code>mean(surv_years)</code> and <code>sd(surv_years)</code>. Are they identical? Should they be (see Dormann, Sect. 3.3.3.1)?</li>
<li>Calculate the likelihood of the data set “by hand” as the product of the densities of all 205 observations. Then calculate <code>prod(dnorm(rep(surv_years, 3), ...))</code>, i.e.&nbsp;the same thing for a data set three times as long. Explain what you see.</li>
<li>Calculate the log-likelihood by hand in two ways: as <code>sum(log(dnorm(...)))</code> and as <code>sum(dnorm(..., log = TRUE))</code>. Check your result against <code>logLik(fit)</code>.</li>
<li>Calculate AIC and BIC by hand from the log-likelihood, using <span class="math inline">\(\mathrm{AIC} = -2\ell + 2p\)</span> and <span class="math inline">\(\mathrm{BIC} = -2\ell + \ln(n)p\)</span>, and check them against <code>AIC(fit)</code> and <code>BIC(fit)</code>. How many parameters <code>p</code> did you use, and where can you see this number in the output of <code>logLik()</code>?</li>
</ol>
<section id="answer-1" class="level2">
<h2 class="anchored" data-anchor-id="answer-1">Answer</h2>
<p><strong>a.</strong> A first look at the data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(surv_years, <span class="at">breaks =</span> <span class="dv">15</span>, <span class="at">col =</span> <span class="st">"grey90"</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"survival time (years)"</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(surv_years)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_2_estimating_parameters_answers_files/figure-html/ex2-histogram-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Survival times of 205 melanoma patients.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(surv_years)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
 0.02738  4.17522  5.48939  5.89405  8.32854 15.23614 </code></pre>
</div>
</div>
<p>The histogram is broad and roughly bell-shaped, with a slight right skew and a hard lower boundary at 0 (a survival time cannot be negative). Strictly speaking a normal distribution is therefore <em>wrong</em>, because it allows negative values. That does not mean it is useless: as Dormann puts it for the fir tree diameters, the distribution may be principally false but still be a useful description. That is exactly what we are going to test.</p>
<p><strong>b.</strong> Fitting by maximum likelihood:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>fit_norm <span class="ot">&lt;-</span> <span class="fu">fitdistr</span>(surv_years, <span class="st">"normal"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>fit_norm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     mean         sd    
  5.8940452   3.0645328 
 (0.2140363) (0.1513465)</code></pre>
</div>
</div>
<p>The first line contains the estimates, the second line (in brackets) their standard errors. Comparison with the sample statistics:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fitdistr =</span> fit_norm<span class="sc">$</span>estimate,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample =</span> <span class="fu">c</span>(<span class="at">mean =</span> <span class="fu">mean</span>(surv_years), <span class="at">sd =</span> <span class="fu">sd</span>(surv_years))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             mean       sd
fitdistr 5.894045 3.064533
sample   5.894045 3.072035</code></pre>
</div>
</div>
<p>The means are <strong>identical</strong>, and that is not a coincidence: Dormann shows analytically (Sect. 3.3.3.1) that the arithmetic mean <em>is</em> the maximum likelihood estimator of <span class="math inline">\(\mu\)</span> for a normal distribution. The standard deviations differ very slightly (3.0645 versus 3.0720). The reason is the denominator: the maximum likelihood estimator divides the sum of squares by <span class="math inline">\(n\)</span>, whereas <code>sd()</code> divides by <span class="math inline">\(n - 1\)</span> (the unbiased sample standard deviation). With <span class="math inline">\(n = 205\)</span> the difference is negligible, but it is real:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mle_sd =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((surv_years <span class="sc">-</span> <span class="fu">mean</span>(surv_years))<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_function =</span> <span class="fu">sd</span>(surv_years))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     mle_sd sd_function 
   3.064533    3.072035 </code></pre>
</div>
</div>
<p><strong>c.</strong> The likelihood of the whole data set is the product of the individual densities, because the observations are assumed to be independent:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>mu_hat <span class="ot">&lt;-</span> fit_norm<span class="sc">$</span>estimate[<span class="st">"mean"</span>]</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>sigma_hat <span class="ot">&lt;-</span> fit_norm<span class="sc">$</span>estimate[<span class="st">"sd"</span>]</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># the first two observations</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(surv_years[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">mean =</span> mu_hat, <span class="at">sd =</span> sigma_hat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02083230 0.02155378</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># all 205 of them multiplied together</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(<span class="fu">dnorm</span>(surv_years, <span class="at">mean =</span> mu_hat, <span class="at">sd =</span> sigma_hat))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.261989e-227</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># and the same for a data set three times as long</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(<span class="fu">dnorm</span>(<span class="fu">rep</span>(surv_years, <span class="dv">3</span>), <span class="at">mean =</span> mu_hat, <span class="at">sd =</span> sigma_hat))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Multiplying 205 numbers that are all smaller than 1 gives <span class="math inline">\(9.3 \times 10^{-227}\)</span>: a number with 226 zeros after the decimal point. That is still just about representable, but with 615 observations the result is returned as exactly <code>0</code>. The computer has run out of digits (<strong>underflow</strong>), not because the likelihood really is zero, but because a <code>double</code> cannot store numbers below roughly <span class="math inline">\(10^{-308}\)</span>. Any comparison of fits based on such a number would be worthless.</p>
<p><strong>d.</strong> The cure is the logarithm, which turns the product into a sum (<span class="math inline">\(\log(ab) = \log a + \log b\)</span>):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">sum_of_logs =</span> <span class="fu">sum</span>(<span class="fu">log</span>(<span class="fu">dnorm</span>(surv_years, <span class="at">mean =</span> mu_hat, <span class="at">sd =</span> sigma_hat))),</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">log_argument =</span> <span class="fu">sum</span>(<span class="fu">dnorm</span>(surv_years, <span class="at">mean =</span> mu_hat, <span class="at">sd =</span> sigma_hat, <span class="at">log =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">from_logLik =</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_norm))</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> sum_of_logs log_argument  from_logLik 
   -520.4609    -520.4609    -520.4609 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logLik</span>(fit_norm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' -520.4609 (df=2)</code></pre>
</div>
</div>
<p>All three routes give <span class="math inline">\(\ell = -520.46\)</span>. The second version, with <code>log = TRUE</code> inside <code>dnorm()</code>, is preferable: it computes the logarithm of the density directly and therefore never creates the tiny intermediate numbers that could underflow. For the same reason it also works for the 615-observation data set, where the first version would fail.</p>
<p>Note that a log-likelihood is almost always negative (densities smaller than 1 have negative logarithms) and that its absolute value has no meaning on its own — only differences between log-likelihoods <strong>of the same data set</strong> are interpretable.</p>
<p><strong>e.</strong> AIC and BIC by hand:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>ll <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_norm))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(surv_years)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">2</span>   <span class="co"># mu and sigma</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">by_hand =</span> <span class="fu">c</span>(<span class="at">AIC =</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> ll <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> p, <span class="at">BIC =</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> ll <span class="sc">+</span> <span class="fu">log</span>(n) <span class="sc">*</span> p),</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">by_function =</span> <span class="fu">c</span>(<span class="at">AIC =</span> <span class="fu">AIC</span>(fit_norm), <span class="at">BIC =</span> <span class="fu">BIC</span>(fit_norm))</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 AIC      BIC
by_hand     1044.922 1051.568
by_function 1044.922 1051.568</code></pre>
</div>
</div>
<p>We estimated <span class="math inline">\(p = 2\)</span> parameters, and R reports this itself as <code>df=2</code> in the output of <code>logLik()</code> (“degrees of freedom”). Both criteria start from <span class="math inline">\(-2\ell\)</span>, so that <em>lower</em> becomes <em>better</em>, and then add a penalty for each estimated parameter: 2 per parameter for the AIC, <span class="math inline">\(\ln(n) = \ln(205) = 5.3\)</span> per parameter for the BIC. The BIC therefore punishes extra parameters more severely than the AIC as soon as <span class="math inline">\(n &gt; 7\)</span>.</p>
</section>
</section>
<section id="exercise-3" class="level1">
<h1>Exercise 3</h1>
<p>Which distribution describes the melanoma survival times best? Fit four continuous distributions to <code>surv_years</code> with <code>fitdistr()</code>: the normal, the log-normal, the gamma and the Weibull distribution.</p>
<ol type="a">
<li>Collect the log-likelihood, the AIC and the BIC of the four fits in one small table.</li>
<li>Which distribution fits best according to the log-likelihood, and which according to AIC and BIC? Do the three criteria agree here? Would you expect them to agree in general?</li>
<li>Draw the four fitted densities on top of a density histogram of the data, each in its own colour, and add the empirical density curve. Does the figure agree with the ranking from the table? Where exactly do the poor fits go wrong?</li>
<li>All four distributions have two parameters here. Explain what would change in the comparison if one of the candidates had only one parameter, and why we cannot simply pick the distribution with the highest log-likelihood in that case.</li>
</ol>
<section id="answer-2" class="level2">
<h2 class="anchored" data-anchor-id="answer-2">Answer</h2>
<p><strong>a.</strong> We fit the four distributions and put all the fits in a list, so that we can treat them in one go:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>fit_norm  <span class="ot">&lt;-</span> <span class="fu">fitdistr</span>(surv_years, <span class="st">"normal"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>fit_lnorm <span class="ot">&lt;-</span> <span class="fu">fitdistr</span>(surv_years, <span class="st">"lognormal"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>fit_gamma <span class="ot">&lt;-</span> <span class="fu">fitdistr</span>(surv_years, <span class="st">"gamma"</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>fit_weib  <span class="ot">&lt;-</span> <span class="fu">fitdistr</span>(surv_years, <span class="st">"weibull"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>fits <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">normal =</span> fit_norm, <span class="at">lognormal =</span> fit_lnorm,</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">gamma =</span> fit_gamma, <span class="at">weibull =</span> fit_weib)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>comparison <span class="ot">&lt;-</span> <span class="fu">sapply</span>(fits, <span class="cf">function</span>(f) <span class="fu">c</span>(<span class="at">logLik =</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(f)),</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">AIC =</span> <span class="fu">AIC</span>(f),</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">BIC =</span> <span class="fu">BIC</span>(f)))</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(comparison, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        normal lognormal   gamma weibull
logLik -520.46   -578.78 -534.54 -521.65
AIC    1044.92   1161.57 1073.08 1047.31
BIC    1051.57   1168.21 1079.73 1053.95</code></pre>
</div>
</div>
<p>The parameter estimates themselves are worth a look too, since every distribution has its own parameter names:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(fits, <span class="cf">function</span>(f) <span class="fu">round</span>(f<span class="sc">$</span>estimate, <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$normal
 mean    sd 
5.894 3.065 

$lognormal
meanlog   sdlog 
  1.547   0.867 

$gamma
shape  rate 
2.355 0.400 

$weibull
shape scale 
1.889 6.569 </code></pre>
</div>
</div>
<p><strong>b.</strong> The normal distribution has the highest (least negative) log-likelihood, <span class="math inline">\(-520.5\)</span>, and consequently also the lowest AIC (1044.9) and the lowest BIC (1051.6). The Weibull distribution follows closely behind (<span class="math inline">\(\ell = -521.7\)</span>, AIC 1047.3), the gamma distribution is clearly worse, and the log-normal distribution is by far the worst (AIC 1161.6, more than 100 units above the winner).</p>
<p>The three criteria agree here, and they <em>must</em> agree in this particular case, because all four distributions have exactly two parameters: the penalty term is then the same for all four, so ordering by <span class="math inline">\(\ell\)</span>, by AIC and by BIC gives the same ranking. In general they need not agree: as soon as the candidates differ in the number of parameters, the log-likelihood always favours the most flexible one, while the AIC and especially the BIC may prefer a simpler distribution.</p>
<p>As a rule of thumb, a difference in AIC of less than about 2 is not convincing evidence. The gap between the normal and the Weibull distribution (1047.3 - 1044.9 = 2.4) is therefore modest: these two are practically tied. The gap to the log-normal is enormous and leaves no doubt.</p>
<p><strong>c.</strong> The visual check:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(surv_years, <span class="at">breaks =</span> <span class="dv">15</span>, <span class="at">probability =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"grey93"</span>, <span class="at">border =</span> <span class="st">"grey60"</span>,</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">las =</span> <span class="dv">1</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.18</span>),</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"survival time (years)"</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(surv_years)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, fit_norm<span class="sc">$</span>estimate[<span class="dv">1</span>], fit_norm<span class="sc">$</span>estimate[<span class="dv">2</span>]),</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"black"</span>)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dweibull</span>(x, fit_weib<span class="sc">$</span>estimate[<span class="dv">1</span>], fit_weib<span class="sc">$</span>estimate[<span class="dv">2</span>]),</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"firebrick"</span>)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dgamma</span>(x, fit_gamma<span class="sc">$</span>estimate[<span class="dv">1</span>], fit_gamma<span class="sc">$</span>estimate[<span class="dv">2</span>]),</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"darkgreen"</span>)</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dlnorm</span>(x, fit_lnorm<span class="sc">$</span>estimate[<span class="dv">1</span>], fit_lnorm<span class="sc">$</span>estimate[<span class="dv">2</span>]),</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"steelblue"</span>)</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(surv_years), <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"grey30"</span>)</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"firebrick"</span>, <span class="st">"darkgreen"</span>, <span class="st">"steelblue"</span>, <span class="st">"grey30"</span>),</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"normal"</span>, <span class="st">"Weibull"</span>, <span class="st">"gamma"</span>, <span class="st">"log-normal"</span>, <span class="st">"empirical density"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_2_estimating_parameters_answers_files/figure-html/ex3-densities-on-histogram-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Four fitted distributions on top of the survival times.</figcaption>
</figure>
</div>
</div>
</div>
<p>The figure confirms the table. The normal and the Weibull curve are almost indistinguishable over most of the range and both follow the histogram well; the Weibull curve is slightly better at the left edge (it cannot go below 0) and slightly worse around the peak. The gamma and especially the log-normal curve are far too high near zero and have far too long a right tail: they are strongly right-skewed distributions, and these data are only mildly skewed. This is where their likelihood is lost — a log-normal distribution assigns a lot of probability density to short survival times that simply are not observed, and hands out relatively little density in the region between 4 and 8 years where most of the observations actually lie.</p>
<p><strong>d.</strong> With an unequal number of parameters the raw log-likelihood becomes useless as a criterion. A distribution with more parameters is more flexible and can therefore always follow the data at least as well, so it will practically always have a higher <span class="math inline">\(\ell\)</span> — even if the extra flexibility is only fitting noise. The AIC and BIC solve this by adding a penalty of 2 (respectively <span class="math inline">\(\ln n\)</span>) per parameter: a distribution with one extra parameter must improve the log-likelihood by more than 1 unit (AIC) before it is declared better. In Dormann’s ash tree example the normal distribution (2 parameters) is compared with a Poisson distribution (1 parameter) in exactly this way; there the normal distribution wins on all fronts, so the penalty does not decide the outcome. In Exercise 6 we will see a case where the number of parameters does differ.</p>
</section>
</section>
<section id="exercise-4" class="level1">
<h1>Exercise 4</h1>
<p>The likelihood is not the only way to judge a fit. In this exercise we compare the fitted distributions with the <strong>empirical cumulative distribution function</strong> of the data (Dormann, Sect. 4.3).</p>
<ol type="a">
<li>Plot <code>ecdf(surv_years)</code> and add, in a different colour, the cumulative distribution function of the fitted normal distribution using <code>curve(pnorm(...), add = TRUE)</code>. Make the same plot for the fitted log-normal distribution next to it (use <code>par(mfrow = c(1, 2))</code>).</li>
<li>Where in the figure is the largest vertical distance between the two curves, roughly, and how large is it?</li>
<li>Run a Kolmogorov-Smirnov test of the data against each of the four distributions you fitted in Exercise 3. Report <code>D</code> and the p-value for each.</li>
<li>Interpret: does the ranking by <code>D</code> agree with the ranking by AIC? What is the null hypothesis of this test, and what does a p-value of, say, 0.049 mean here?</li>
<li>R gives a warning about <strong>ties</strong>. Explain what a tie is, why it is a problem for this test, and check with <code>sum(duplicated(surv_years))</code> how many there are.</li>
<li>A second, more fundamental problem is that we estimated the parameters of the reference distribution <em>from the same data</em>. Explain why this makes the p-value too optimistic, and name the test that corrects for this (Dormann, Side Note 3 and Sect. 4.4).</li>
</ol>
<section id="answer-3" class="level2">
<h2 class="anchored" data-anchor-id="answer-3">Answer</h2>
<p><strong>a.</strong> The ECDF is the cumulative version of the data: a staircase that rises by <span class="math inline">\(1/n\)</span> at every observation. It is the natural thing to compare with a theoretical cumulative distribution function, because both live on the same scale (0 to 1) and neither depends on an arbitrary choice of histogram bins.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="fl">4.5</span>, <span class="dv">3</span>, <span class="dv">1</span>))</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">ecdf</span>(surv_years), <span class="at">verticals =</span> <span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="st">""</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"normal"</span>, <span class="at">xlab =</span> <span class="st">"survival time (years)"</span>, <span class="at">ylab =</span> <span class="st">"Fn(x)"</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">pnorm</span>(x, fit_norm<span class="sc">$</span>estimate[<span class="dv">1</span>], fit_norm<span class="sc">$</span>estimate[<span class="dv">2</span>]),</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"firebrick"</span>)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">ecdf</span>(surv_years), <span class="at">verticals =</span> <span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="st">""</span>)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">ecdf</span>(surv_years), <span class="at">verticals =</span> <span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="st">""</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"log-normal"</span>, <span class="at">xlab =</span> <span class="st">"survival time (years)"</span>, <span class="at">ylab =</span> <span class="st">"Fn(x)"</span>)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">plnorm</span>(x, fit_lnorm<span class="sc">$</span>estimate[<span class="dv">1</span>], fit_lnorm<span class="sc">$</span>estimate[<span class="dv">2</span>]),</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"firebrick"</span>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">ecdf</span>(surv_years), <span class="at">verticals =</span> <span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="st">""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_2_estimating_parameters_answers_files/figure-html/ex4-ecdf-plots-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>ECDF of the survival times (black) with the fitted normal (left) and log-normal (right) cumulative distribution function in red.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>b.</strong> For the normal distribution the two curves run close together everywhere; the widest gap is in the middle of the range, at a survival time of roughly 6 years, where the staircase runs above the red curve — around the median slightly more patients have already been reached than the fitted normal distribution predicts. For the log-normal distribution the gap is much larger and lies lower down, around 4 years, and it has the opposite sign: there the red curve runs well above the staircase, i.e.&nbsp;the log-normal distribution predicts far more short survival times than were actually observed. We can locate the largest gap exactly, which is precisely what the KS test statistic <code>D</code> is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>sorted <span class="ot">&lt;-</span> <span class="fu">sort</span>(surv_years)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>ecdf_values <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(sorted)) <span class="sc">/</span> <span class="fu">length</span>(sorted)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>gap_norm <span class="ot">&lt;-</span> <span class="fu">abs</span>(ecdf_values <span class="sc">-</span> <span class="fu">pnorm</span>(sorted, fit_norm<span class="sc">$</span>estimate[<span class="dv">1</span>], fit_norm<span class="sc">$</span>estimate[<span class="dv">2</span>]))</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>gap_lnorm <span class="ot">&lt;-</span> <span class="fu">abs</span>(ecdf_values <span class="sc">-</span> <span class="fu">plnorm</span>(sorted, fit_lnorm<span class="sc">$</span>estimate[<span class="dv">1</span>], fit_lnorm<span class="sc">$</span>estimate[<span class="dv">2</span>]))</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">normal =</span> <span class="fu">c</span>(<span class="at">largest_gap =</span> <span class="fu">max</span>(gap_norm), <span class="at">at_survival_time =</span> sorted[<span class="fu">which.max</span>(gap_norm)]),</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">lognormal =</span> <span class="fu">c</span>(<span class="at">largest_gap =</span> <span class="fu">max</span>(gap_lnorm), <span class="at">at_survival_time =</span> sorted[<span class="fu">which.max</span>(gap_lnorm)])</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          largest_gap at_survival_time
normal      0.0950263         5.782341
lognormal   0.2138142         4.104038</code></pre>
</div>
</div>
<p><strong>c.</strong> The same comparison as a formal test, for all four distributions:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>ks_norm  <span class="ot">&lt;-</span> <span class="fu">ks.test</span>(surv_years, <span class="st">"pnorm"</span>,    fit_norm<span class="sc">$</span>estimate[<span class="dv">1</span>],  fit_norm<span class="sc">$</span>estimate[<span class="dv">2</span>])</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>ks_weib  <span class="ot">&lt;-</span> <span class="fu">ks.test</span>(surv_years, <span class="st">"pweibull"</span>, fit_weib<span class="sc">$</span>estimate[<span class="dv">1</span>],  fit_weib<span class="sc">$</span>estimate[<span class="dv">2</span>])</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>ks_gamma <span class="ot">&lt;-</span> <span class="fu">ks.test</span>(surv_years, <span class="st">"pgamma"</span>,   fit_gamma<span class="sc">$</span>estimate[<span class="dv">1</span>], fit_gamma<span class="sc">$</span>estimate[<span class="dv">2</span>])</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>ks_lnorm <span class="ot">&lt;-</span> <span class="fu">ks.test</span>(surv_years, <span class="st">"plnorm"</span>,   fit_lnorm<span class="sc">$</span>estimate[<span class="dv">1</span>], fit_lnorm<span class="sc">$</span>estimate[<span class="dv">2</span>])</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>ks_norm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic one-sample Kolmogorov-Smirnov test

data:  surv_years
D = 0.095026, p-value = 0.04933
alternative hypothesis: two-sided</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>ks_results <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="fu">list</span>(<span class="at">normal =</span> ks_norm, <span class="at">weibull =</span> ks_weib,</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">gamma =</span> ks_gamma, <span class="at">lognormal =</span> ks_lnorm),</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                     <span class="cf">function</span>(k) <span class="fu">c</span>(<span class="at">D =</span> <span class="fu">as.numeric</span>(k<span class="sc">$</span>statistic), <span class="at">p =</span> k<span class="sc">$</span>p.value))</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">signif</span>(ks_results, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  normal weibull    gamma lognormal
D 0.0950 0.11800 1.63e-01  2.19e-01
p 0.0493 0.00689 3.78e-05  6.10e-09</code></pre>
</div>
</div>
<p><strong>d.</strong> The ranking by <code>D</code> (normal 0.095 &lt; Weibull 0.118 &lt; gamma 0.163 &lt; log-normal 0.219) is exactly the same as the ranking by AIC in Exercise 3. That is encouraging but not guaranteed: the two criteria measure different things. <code>D</code> is a purely local measure — the single largest vertical gap, ignoring how good or bad the fit is everywhere else — whereas the log-likelihood uses every observation.</p>
<p>The null hypothesis of the test is that the data were drawn from the specified distribution. A large <code>D</code> and a small p-value are evidence <em>against</em> that distribution. Note the asymmetry: a large p-value is not proof that the distribution is correct, only that we failed to demonstrate a difference.</p>
<p>For the normal distribution we get <span class="math inline">\(D = 0.095\)</span> with <span class="math inline">\(p = 0.049\)</span>: just below the conventional 5% threshold, so on a strict reading we would reject even our best candidate. This is a good illustration of why the graphical comparison in (a) is more informative than the p-value. The picture shows a small, systematic discrepancy in the lower tail, and with 205 observations that is enough to become “significant”. Whether such a deviation matters depends on what we want to do with the distribution, not on whether the p-value happens to fall on one or the other side of 0.05.</p>
<p><strong>e.</strong> A tie is a value that occurs more than once in the data set. The exact p-value of the KS test is derived for continuous data, in which two observations are never exactly equal; with ties the ECDF makes jumps larger than <span class="math inline">\(1/n\)</span> and the formula no longer holds, so R falls back on an approximation and warns us.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">duplicated</span>(surv_years))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11</code></pre>
</div>
</div>
<p>There are 11 duplicated values among 205 observations. That is few, and with a data set of this size the approximate p-value is still usable — but the ties are real, because survival times were recorded in whole days.</p>
<p><strong>f.</strong> The p-value of the KS test assumes that the reference distribution is fixed <em>in advance</em>. We did the opposite: we used <code>fitdistr()</code> to choose exactly those parameter values that make the distribution resemble these data as closely as possible. The fitted distribution therefore hugs the data more tightly than a distribution specified beforehand would, <code>D</code> comes out too small, and the p-value comes out too large. In other words, the test is too lenient — which makes the borderline <span class="math inline">\(p = 0.049\)</span> for the normal distribution look even less flattering.</p>
<p>The <strong>Lilliefors test</strong> (<code>lillie.test()</code> in the <code>nortest</code> package) is the corrected variant of the KS test for exactly this situation. Dormann also mentions the Shapiro-Wilk test, the Anderson-Darling test (<code>ad.test()</code> in <code>ADGofTest</code>), the Cramér-von-Mises test and the Pearson <span class="math inline">\(\chi^2\)</span> test. If those packages are installed you can compare them:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lillie.test</span>(surv_years)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ADGofTest)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ad.test</span>(surv_years, pnorm, <span class="at">mean =</span> fit_norm<span class="sc">$</span>estimate[<span class="dv">1</span>], <span class="at">sd =</span> fit_norm<span class="sc">$</span>estimate[<span class="dv">2</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="exercise-5" class="level1">
<h1>Exercise 5</h1>
<p>Section 4.4 of Dormann discusses formal tests for normality, and warns that they should not be trusted blindly.</p>
<ol type="a">
<li>Apply <code>shapiro.test()</code> to <code>surv_years</code>, to <code>log(surv_years)</code>, to <code>cats$Bwt</code> and to <code>quine$Days</code>. Report <code>W</code> and the p-value for each and state your conclusion for each variable.</li>
<li>Make a QQ-plot (<code>qqnorm()</code> with <code>qqline()</code>) for each of these four variables. Describe for each what the QQ-plot tells you that the p-value does not, in particular <em>how</em> the variable deviates from normality (skew, heavy tails, discreteness, …).</li>
<li><code>log(surv_years)</code> is <em>worse</em> than <code>surv_years</code> according to the test. Explain why taking logarithms is not automatically an improvement.</li>
<li>Now demonstrate the sample-size problem. Simulate 2000 values from a clearly non-normal distribution, e.g.&nbsp;<code>set.seed(1); big &lt;- rlnorm(2000, meanlog = 0, sdlog = 0.6)</code>, and apply <code>shapiro.test()</code> to the first 10, 20, 50, 100, 500 and 2000 values. Report the p-values and explain what this shows about the usefulness of a normality test on a small sample and on a very large sample.</li>
</ol>
<section id="answer-4" class="level2">
<h2 class="anchored" data-anchor-id="answer-4">Answer</h2>
<p><strong>a.</strong> The Shapiro-Wilk test is purely a test for normality; <code>W</code> is close to 1 when the data are normal.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>variables <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">surv_years =</span> surv_years,</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">log_surv_years =</span> <span class="fu">log</span>(surv_years),</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">cats_Bwt =</span> cats<span class="sc">$</span>Bwt,</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">quine_Days =</span> quine<span class="sc">$</span>Days)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>shapiro_results <span class="ot">&lt;-</span> <span class="fu">sapply</span>(variables, <span class="cf">function</span>(v) {</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  test <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(v)</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">W =</span> <span class="fu">as.numeric</span>(test<span class="sc">$</span>statistic), <span class="at">p =</span> test<span class="sc">$</span>p.value)</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a><span class="fu">signif</span>(shapiro_results, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  surv_years log_surv_years cats_Bwt quine_Days
W    0.97900       7.76e-01 9.52e-01   8.36e-01
p    0.00428       2.03e-16 6.73e-05   1.81e-11</code></pre>
</div>
</div>
<p>All four p-values are below 0.05, so formally normality is rejected in every case. But the four <code>W</code> values tell a much more differentiated story: <code>surv_years</code> (<span class="math inline">\(W = 0.979\)</span>) is close to normal, <code>cats$Bwt</code> (<span class="math inline">\(W = 0.952\)</span>) somewhat less so, and <code>log(surv_years)</code> (<span class="math inline">\(W = 0.776\)</span>) and <code>quine$Days</code> (<span class="math inline">\(W = 0.836\)</span>) are far off. Reporting only “p &lt; 0.05, not normal” throws away that information.</p>
<p><strong>b.</strong> The QQ-plot compares the quantiles of the data (y-axis) with the quantiles expected under a normal distribution (x-axis). If the data are normal the points lie on the straight line; the <em>shape</em> of the deviation tells us what kind of departure we are dealing with.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (nm <span class="cf">in</span> <span class="fu">names</span>(variables)) {</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">qqnorm</span>(variables[[nm]], <span class="at">main =</span> nm, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> <span class="fu">rgb</span>(<span class="fl">0.1</span>, <span class="fl">0.35</span>, <span class="fl">0.65</span>, <span class="fl">0.5</span>))</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">qqline</span>(variables[[nm]], <span class="at">col =</span> <span class="st">"firebrick"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_2_estimating_parameters_answers_files/figure-html/ex5-qqplots-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>QQ-plots of the four variables.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><code>surv_years</code>: the points follow the line closely over most of the range, with a mild S-shape and a slightly short left tail. This is the small systematic deviation we already saw in the ECDF plot of Exercise 4 — a defensible fit.</li>
<li><code>log(surv_years)</code>: a dramatic downward bend on the left. Taking logarithms has produced a strong <em>left</em> skew and a few extreme low values.</li>
<li><code>cats$Bwt</code>: a wavy pattern with steps, reflecting both the mixture of the two sexes and the fact that weights were rounded to 0.1 kg.</li>
<li><code>quine$Days</code>: a strongly convex curve, the signature of pronounced right skew, plus visible horizontal stretches because these are counts (many children share the same value).</li>
</ul>
<p>The p-values in (a) said “not normal” four times; the QQ-plots explain <em>why</em>, and make clear that the first case is nothing like the other three.</p>
<p><strong>c.</strong> Logarithms compress large values and stretch small ones. That is the right medicine for right-skewed data with a long upper tail. <code>surv_years</code> is only mildly right-skewed but contains a handful of very short survival times (the minimum is 0.03 years, about 10 days). After taking logarithms those few small values are pulled far away from the rest, and the mild right skew is converted into a heavy left skew. A transformation must always be checked afterwards, exactly as we are doing here: the result has to satisfy the assumptions of the <em>new</em> distribution, and there is no guarantee of that in advance.</p>
<p><strong>d.</strong> The sample-size demonstration:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>big <span class="ot">&lt;-</span> <span class="fu">rlnorm</span>(<span class="dv">2000</span>, <span class="at">meanlog =</span> <span class="dv">0</span>, <span class="at">sdlog =</span> <span class="fl">0.6</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>sizes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">500</span>, <span class="dv">2000</span>)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>sample_size_effect <span class="ot">&lt;-</span> <span class="fu">sapply</span>(sizes, <span class="cf">function</span>(n) {</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  test <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(big[<span class="dv">1</span><span class="sc">:</span>n])</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">n =</span> n, <span class="at">W =</span> <span class="fu">as.numeric</span>(test<span class="sc">$</span>statistic), <span class="at">p =</span> test<span class="sc">$</span>p.value)</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a><span class="fu">signif</span>(sample_size_effect, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]   [,2]   [,3]     [,4]     [,5]     [,6]
n 10.0000 20.000 50.000 1.00e+02 5.00e+02 2.00e+03
W  0.8630  0.958  0.966 8.75e-01 7.76e-01 8.14e-01
p  0.0826  0.511  0.158 1.08e-07 1.37e-25 3.25e-43</code></pre>
</div>
</div>
<p>Every one of these samples comes from the <em>same</em> log-normal distribution, which is definitely not normal. Nevertheless the test does not detect this at <span class="math inline">\(n = 10\)</span>, 20 or 50 (<span class="math inline">\(p\)</span> between 0.08 and 0.51), while from <span class="math inline">\(n = 100\)</span> onwards the p-value collapses: <span class="math inline">\(10^{-7}\)</span>, then <span class="math inline">\(10^{-25}\)</span>, then <span class="math inline">\(10^{-43}\)</span>. Look at <code>W</code> alongside it. It does not decrease steadily with <code>n</code>: at <span class="math inline">\(n = 20\)</span> and <span class="math inline">\(n = 50\)</span> it is actually <em>higher</em> (0.96, 0.97) than at <span class="math inline">\(n = 10\)</span> (0.86), simply because a small sample is dominated by luck of the draw. Only from about <span class="math inline">\(n = 100\)</span> does <code>W</code> settle down, around 0.78-0.87, close to the value it will keep for this distribution. The population being sampled never changes; what changes is how reliably a sample of that size reflects it.</p>
<p>The conclusion is uncomfortable but important. With a small sample the test almost never rejects, so “p &gt; 0.05” is no evidence of normality — it usually just means we have too little data. With a very large sample the test rejects almost always, because every real data set deviates a little from a mathematical ideal, and a large <code>n</code> makes even a trivial deviation significant. A normality test therefore mostly measures your sample size. The QQ-plot from part (b) measures the thing you actually care about: how big the deviation is, and in which direction.</p>
</section>
</section>
<section id="exercise-6" class="level1">
<h1>Exercise 6</h1>
<p>Someone left a data set scribbled on a piece of paper behind on the tram. These are whole numbers, so both a normal and a Poisson distribution are conceivable candidates.</p>
<ol type="a">
<li>Calculate the mean and the variance of these 13 numbers. Which of the two candidate distributions is already made unlikely by this comparison, and why (Dormann, Sect. 3.4.4)?</li>
<li>Fit both distributions with <code>fitdistr()</code> and compare them using the BIC. Which one wins, and by how much?</li>
<li>The Poisson fit returns only one parameter. What is its estimate, and which sample statistic does it equal? Why (Dormann, Sect. 3.3.3.2)?</li>
<li>Plot the observed values as a histogram together with both fitted distributions. Remember that one of the two is discrete and needs a different kind of plot.</li>
<li>We have only 13 observations. How much confidence do you place in this conclusion? Look at the standard errors that <code>fitdistr()</code> reports.</li>
</ol>
<section id="answer-5" class="level2">
<h2 class="anchored" data-anchor-id="answer-5">Answer</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>tram <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">36</span>, <span class="dv">37</span>, <span class="dv">15</span>, <span class="dv">14</span>, <span class="dv">25</span>, <span class="dv">33</span>, <span class="dv">44</span>, <span class="dv">34</span>, <span class="dv">37</span>, <span class="dv">32</span>, <span class="dv">12</span>, <span class="dv">2</span>, <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>a.</strong> The decisive comparison for count data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">n =</span> <span class="fu">length</span>(tram), <span class="at">mean =</span> <span class="fu">mean</span>(tram), <span class="at">variance =</span> <span class="fu">var</span>(tram),</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">ratio =</span> <span class="fu">var</span>(tram) <span class="sc">/</span> <span class="fu">mean</span>(tram))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         n       mean   variance      ratio 
 13.000000  25.000000 193.666667   7.746667 </code></pre>
</div>
</div>
<p>For a Poisson distribution the variance <strong>equals</strong> the mean, so the ratio should be about 1. Here the variance is 194 against a mean of 25, a ratio of nearly 8: the data are heavily <strong>overdispersed</strong>. Before fitting anything we can therefore already suspect that the Poisson distribution will do badly. The normal distribution has independent parameters for location and spread and does not have this problem.</p>
<p><strong>b.</strong> The two fits and their BIC values:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>fit_tram_norm <span class="ot">&lt;-</span> <span class="fu">fitdistr</span>(tram, <span class="st">"normal"</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>fit_tram_pois <span class="ot">&lt;-</span> <span class="fu">fitdistr</span>(tram, <span class="st">"Poisson"</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>fit_tram_norm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     mean         sd    
  25.000000   13.370461 
 ( 3.708299) ( 2.622163)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>fit_tram_pois</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    lambda 
  25.00000 
 ( 1.38675)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sapply</span>(<span class="fu">list</span>(<span class="at">normal =</span> fit_tram_norm, <span class="at">Poisson =</span> fit_tram_pois),</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>             <span class="cf">function</span>(f) <span class="fu">c</span>(<span class="at">logLik =</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(f)),</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">AIC =</span> <span class="fu">AIC</span>(f), <span class="at">BIC =</span> <span class="fu">BIC</span>(f))), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       normal Poisson
logLik -52.16  -88.71
AIC    108.31  179.42
BIC    109.44  179.98</code></pre>
</div>
</div>
<p>The normal distribution wins decisively: BIC 109.4 against 180.0, a difference of about 70 units. Anything above roughly 10 is regarded as very strong evidence, so there is no doubt at all. Note that this happens <em>despite</em> the fact that the Poisson distribution is being rewarded for its simplicity: it estimates only one parameter and therefore receives a smaller penalty (<span class="math inline">\(1 \times \ln 13 = 2.6\)</span> instead of <span class="math inline">\(2 \times \ln 13 = 5.1\)</span>). Even with that advantage it loses by a mile, because its log-likelihood is 36 units worse.</p>
<p><strong>c.</strong> The Poisson estimate is <span class="math inline">\(\hat{\lambda} = 25\)</span>, exactly <code>mean(tram)</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">lambda_hat =</span> <span class="fu">as.numeric</span>(fit_tram_pois<span class="sc">$</span>estimate), <span class="at">sample_mean =</span> <span class="fu">mean</span>(tram))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> lambda_hat sample_mean 
         25          25 </code></pre>
</div>
</div>
<p>This is the analytical result from Dormann Sect. 3.3.3.2: for the Poisson distribution the arithmetic mean is the maximum likelihood estimator of <span class="math inline">\(\lambda\)</span>, which is why <span class="math inline">\(\lambda\)</span> is usually simply called “the mean” of the Poisson distribution. And this immediately explains the poor fit: having matched the mean, the Poisson distribution has no freedom left, and it is then forced to claim that the variance is also 25 — while it is in fact 194.</p>
<p><strong>d.</strong> The two fits drawn on the data. The normal distribution is continuous, so we draw a curve; the Poisson distribution is discrete, so we draw spikes.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(tram, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">50</span>, <span class="at">by =</span> <span class="dv">5</span>), <span class="at">probability =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"grey93"</span>,</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="st">"grey60"</span>, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.09</span>),</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"value"</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(tram, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, fit_tram_norm<span class="sc">$</span>estimate[<span class="dv">1</span>], fit_tram_norm<span class="sc">$</span>estimate[<span class="dv">2</span>]),</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"firebrick"</span>)</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">50</span></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(k, <span class="fu">dpois</span>(k, fit_tram_pois<span class="sc">$</span>estimate), <span class="at">type =</span> <span class="st">"h"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"steelblue"</span>)</span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"firebrick"</span>, <span class="st">"steelblue"</span>),</span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"normal"</span>, <span class="st">"Poisson"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_2_estimating_parameters_answers_files/figure-html/ex6-plot-fits-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>The 13 tram numbers with a fitted normal density (curve) and Poisson probabilities (spikes).</figcaption>
</figure>
</div>
</div>
</div>
<p>The picture speaks for itself. The Poisson spikes form a narrow bundle around 25 with essentially no probability below 12 or above 40, while five of the thirteen observations lie outside exactly that region. The normal curve is wide enough to accommodate the whole range.</p>
<p><strong>e.</strong> Caution is in order. With <span class="math inline">\(n = 13\)</span> the estimates are imprecise, as the standard errors show: the mean is estimated as <span class="math inline">\(25 \pm 3.7\)</span> and the standard deviation as <span class="math inline">\(13.4 \pm 2.6\)</span>, so a standard deviation of 10 or 18 would also be quite compatible with these data. What we may safely conclude is the <em>negative</em> result — the Poisson distribution is untenable, because the discrepancy of 70 BIC units is far larger than any sampling uncertainty could explain. The <em>positive</em> claim, that the normal distribution is the correct one, rests on much weaker ground: with 13 observations several other distributions would fit about as well, and as Exercise 5 showed, no test would be able to distinguish between them at this sample size. And of course we have no idea what these numbers actually are, which in practice is the strongest argument of all — the choice of distribution should follow from the process that generated the data (Dormann, Sect. 3.5).</p>
</section>
</section>
<section id="exercise-7" class="level1">
<h1>Exercise 7</h1>
<p>Count data are common in biology, and the Poisson distribution is the obvious first candidate. Use <code>quine$Days</code>, the number of days that each of 146 Australian schoolchildren was absent from school (see <code>?quine</code>).</p>
<ol type="a">
<li>Calculate the mean and the variance of <code>Days</code>. Calculate the ratio variance/mean. What is this ratio for a true Poisson distribution, and what do we call the situation you observe here (Dormann, Sect. 3.4.4)?</li>
<li>Fit a Poisson and a negative binomial distribution with <code>fitdistr()</code> and compare them with AIC and BIC. How large is the difference, and what does a difference of this size mean?</li>
<li>Compare the observed number of children in a few count classes with the number expected under each of the two fitted distributions, and plot the three sets of frequencies next to each other in a barplot. Which parts of the range does the Poisson distribution get badly wrong?</li>
<li>Would it be sensible to use <code>ks.test()</code> here to decide between the two distributions? Explain.</li>
</ol>
<section id="answer-6" class="level2">
<h2 class="anchored" data-anchor-id="answer-6">Answer</h2>
<p><strong>a.</strong> The same diagnostic as in the previous exercise:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>days <span class="ot">&lt;-</span> quine<span class="sc">$</span>Days</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">n =</span> <span class="fu">length</span>(days), <span class="at">mean =</span> <span class="fu">mean</span>(days), <span class="at">variance =</span> <span class="fu">var</span>(days),</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">ratio =</span> <span class="fu">var</span>(days) <span class="sc">/</span> <span class="fu">mean</span>(days), <span class="at">maximum =</span> <span class="fu">max</span>(days), <span class="at">zeros =</span> <span class="fu">sum</span>(days <span class="sc">==</span> <span class="dv">0</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        n      mean  variance     ratio   maximum     zeros 
146.00000  16.45890 264.16726  16.05011  81.00000   9.00000 </code></pre>
</div>
</div>
<p>For a Poisson distribution mean and variance are equal, so the ratio should be about 1. It is 16. These data are strongly <strong>overdispersed</strong>, and the negative binomial distribution is the standard remedy: it is the count distribution that has an extra parameter precisely to let the variance exceed the mean (Dormann, Sect. 3.4.5).</p>
<p><strong>b.</strong> Both fits:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>fit_pois <span class="ot">&lt;-</span> <span class="fu">fitdistr</span>(days, <span class="st">"Poisson"</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>fit_nb <span class="ot">&lt;-</span> <span class="fu">fitdistr</span>(days, <span class="st">"negative binomial"</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>fit_pois</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     lambda  
  16.4589041 
 ( 0.3357562)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>fit_nb</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      size          mu    
   1.0667932   16.4589041 
 ( 0.1292224) ( 1.3608854)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sapply</span>(<span class="fu">list</span>(<span class="at">Poisson =</span> fit_pois, <span class="at">negative_binomial =</span> fit_nb),</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>             <span class="cf">function</span>(f) <span class="fu">c</span>(<span class="at">logLik =</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(f)),</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">AIC =</span> <span class="fu">AIC</span>(f), <span class="at">BIC =</span> <span class="fu">BIC</span>(f))), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Poisson negative_binomial
logLik -1331.00           -559.13
AIC     2664.01           1122.27
BIC     2666.99           1128.23</code></pre>
</div>
</div>
<p>The difference is gigantic: an AIC of 2664 against 1122, a gap of more than 1500 units. Differences of 2 are already worth mentioning and differences of 10 are decisive, so this is not a close call. The negative binomial fit uses one parameter more (<code>size</code> and <code>mu</code> against only <code>lambda</code>) and pays a penalty of 2 AIC units for it — utterly negligible against an improvement of 772 in the log-likelihood.</p>
<p>Note that the estimated <code>mu</code> of the negative binomial distribution equals the Poisson <code>lambda</code> and both equal the sample mean, 16.46. The two distributions agree entirely about the mean; they disagree about the spread. The <code>size</code> parameter of 1.07 is the dispersion parameter: the smaller it is, the more overdispersed the data (as <code>size</code> goes to infinity the negative binomial distribution becomes the Poisson distribution).</p>
<p><strong>c.</strong> Observed against expected frequencies:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>breaks <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">100</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>observed <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="fu">cut</span>(days, <span class="at">breaks =</span> breaks))</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(days)</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>upper <span class="ot">&lt;-</span> breaks[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>lower <span class="ot">&lt;-</span> breaks[<span class="sc">-</span><span class="fu">length</span>(breaks)]</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>exp_pois <span class="ot">&lt;-</span> n <span class="sc">*</span> (<span class="fu">ppois</span>(upper, <span class="at">lambda =</span> fit_pois<span class="sc">$</span>estimate) <span class="sc">-</span></span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">ppois</span>(lower, <span class="at">lambda =</span> fit_pois<span class="sc">$</span>estimate))</span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>exp_nb <span class="ot">&lt;-</span> n <span class="sc">*</span> (<span class="fu">pnbinom</span>(upper, <span class="at">size =</span> fit_nb<span class="sc">$</span>estimate[<span class="st">"size"</span>],</span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>                       <span class="at">mu =</span> fit_nb<span class="sc">$</span>estimate[<span class="st">"mu"</span>]) <span class="sc">-</span></span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>               <span class="fu">pnbinom</span>(lower, <span class="at">size =</span> fit_nb<span class="sc">$</span>estimate[<span class="st">"size"</span>],</span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a>                       <span class="at">mu =</span> fit_nb<span class="sc">$</span>estimate[<span class="st">"mu"</span>]))</span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="at">observed =</span> <span class="fu">as.numeric</span>(observed),</span>
<span id="cb74-17"><a href="#cb74-17" aria-hidden="true" tabindex="-1"></a>                <span class="at">Poisson =</span> exp_pois,</span>
<span id="cb74-18"><a href="#cb74-18" aria-hidden="true" tabindex="-1"></a>                <span class="at">negative_binomial =</span> exp_nb)</span>
<span id="cb74-19"><a href="#cb74-19" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(counts) <span class="ot">&lt;-</span> <span class="fu">names</span>(observed)</span>
<span id="cb74-20"><a href="#cb74-20" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(counts, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  (-1,0] (0,5] (5,10] (10,15] (15,20] (20,30] (30,40] (40,100]
observed             9.0  36.0   24.0    23.0    12.0    17.0    11.0     14.0
Poisson              0.0   0.1    9.1    52.4    61.2    23.1     0.1      0.0
negative_binomial    7.4  34.3   26.7    20.1    15.0    19.4    10.6     12.2</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(counts, <span class="at">beside =</span> <span class="cn">TRUE</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"grey40"</span>, <span class="st">"steelblue"</span>, <span class="st">"firebrick"</span>),</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"days absent from school"</span>, <span class="at">ylab =</span> <span class="st">"number of children"</span>,</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.text =</span> <span class="fu">c</span>(<span class="st">"observed"</span>, <span class="st">"Poisson"</span>, <span class="st">"negative binomial"</span>),</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">args.legend =</span> <span class="fu">list</span>(<span class="at">x =</span> <span class="st">"topright"</span>, <span class="at">bty =</span> <span class="st">"n"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_2_estimating_parameters_answers_files/figure-html/ex7-barplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Observed and expected numbers of children per class of days absent.</figcaption>
</figure>
</div>
</div>
</div>
<p>The table makes the failure of the Poisson distribution concrete, and it fails at both ends. It expects essentially <strong>no</strong> children with 0 days absent (0.0 against 9 observed) and virtually none in the class 1-5 days (0.2 against 36 observed), while at the other end it expects nobody above 40 days (0.0 against 14 observed). Instead it piles almost everything into the middle classes: 61 children expected in the class 15-20 days against 12 observed. This is the direct consequence of the variance being locked to the mean: the Poisson distribution simply cannot be this wide. The negative binomial expectations follow the observed frequencies much more closely across the whole range.</p>
<p><strong>d.</strong> No.&nbsp;The Kolmogorov-Smirnov test is derived for <strong>continuous</strong> distributions, and both candidates here are discrete. Applying it to count data means that the entire data set consists of ties — with 146 observations and only a few dozen distinct values, R’s warning about ties would be the least of the problem: the exact null distribution of <code>D</code> simply does not apply. Furthermore, <code>ks.test()</code> compares the data with <em>one</em> distribution at a time; it is a goodness-of-fit test, not a model-selection tool. For discrete data the appropriate alternatives are the comparison of AIC/BIC values that we did in (b), a <span class="math inline">\(\chi^2\)</span> goodness-of-fit test on the observed and expected counts from (c), or simply the graphical comparison — which here is the most convincing evidence of all.</p>
</section>
</section>
<section id="exercise-8" class="level1">
<h1>Exercise 8</h1>
<p>In this final exercise we cheat: we generate the data ourselves, so for once we know the true answer. This is a variant of exercises 5 and 6 in Sect. 4.5 of Dormann.</p>
<ol type="a">
<li>Choose a location and a scale for the <strong>logistic</strong> distribution (not the default values of 0 and 1) and simulate 100 observations with <code>rlogis()</code>. Use <code>set.seed()</code> so that your results are reproducible, and store the sample in an object. Make a histogram of the simulated values with the true density curve (<code>dlogis()</code> with <em>your</em> parameter values) drawn on top.</li>
<li>Plot the empirical cumulative distribution function of your sample and draw the true cumulative distribution function (<code>plogis()</code> with your parameter values) on top. Describe the discrepancy between the two. Nothing is wrong here: this is simply the difference between a random realisation and the truth.</li>
<li>Repeat (b) with a sample of 20 and a sample of 2000 observations from the same distribution. What happens to the discrepancy, and what is the name of the principle you are demonstrating?</li>
<li>Now pretend you do not know the truth: fit a logistic distribution to your sample of 100 with <code>fitdistr()</code>. Compare the estimates with the values you used to simulate. Are the true values within roughly two standard errors of the estimates?</li>
<li>Calculate the log-likelihood of these data “by hand” by summing <code>dlogis(..., log = TRUE)</code> at the fitted parameters, and check the result against <code>logLik()</code>.</li>
<li>Finally, also fit a <strong>normal</strong> distribution to the same 100 simulated values and compare the two fits with AIC. Does the criterion select the distribution that actually generated the data? Plot both fitted densities on top of the histogram and comment on how easy or hard it is to tell these two distributions apart with only 100 observations.</li>
</ol>
<section id="answer-7" class="level2">
<h2 class="anchored" data-anchor-id="answer-7">Answer</h2>
<p><strong>a.</strong> We choose <code>location = 5</code> and <code>scale = 2</code>. <code>set.seed()</code> fixes the random number generator so that the results are reproducible; without it you would get different numbers every time (which is instructive to try).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>true_location <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>true_scale <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>sim <span class="ot">&lt;-</span> <span class="fu">rlogis</span>(<span class="dv">100</span>, <span class="at">location =</span> true_location, <span class="at">scale =</span> true_scale)</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(sim, <span class="at">breaks =</span> <span class="dv">15</span>, <span class="at">probability =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"grey93"</span>, <span class="at">border =</span> <span class="st">"grey60"</span>,</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">las =</span> <span class="dv">1</span>, <span class="at">xlab =</span> <span class="st">"simulated value"</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(sim)</span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dlogis</span>(x, <span class="at">location =</span> true_location, <span class="at">scale =</span> true_scale),</span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"firebrick"</span>)</span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"firebrick"</span>,</span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="st">"true density logistic(5, 2)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_2_estimating_parameters_answers_files/figure-html/ex8-simulate-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>100 simulated values from a logistic(5, 2) distribution with the true density.</figcaption>
</figure>
</div>
</div>
</div>
<p>The histogram follows the curve in outline, but bar by bar there are clear deviations: some classes have too many values, others too few. Remember that the histogram <em>is</em> the truth here in the sense that these really are values from this distribution — the deviations are pure sampling variation.</p>
<p><strong>b.</strong> The cumulative version of the same comparison:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">ecdf</span>(sim), <span class="at">verticals =</span> <span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="st">""</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">""</span>, <span class="at">xlab =</span> <span class="st">"value"</span>, <span class="at">ylab =</span> <span class="st">"Fn(x)"</span>)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">plogis</span>(x, <span class="at">location =</span> true_location, <span class="at">scale =</span> true_scale),</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"firebrick"</span>)</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">ecdf</span>(sim), <span class="at">verticals =</span> <span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="st">""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_2_estimating_parameters_answers_files/figure-html/ex8-ecdf-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>ECDF of the 100 simulated values (black) with the true cumulative distribution function (red).</figcaption>
</figure>
</div>
</div>
</div>
<p>The staircase wanders around the smooth curve, sometimes above it and sometimes below, with the largest gaps in the middle where the data are densest. This is worth dwelling on: we know with certainty that the red curve is correct, and yet the data deviate visibly from it. Whenever you judge a fit to real data, this is the amount of discrepancy you should regard as normal.</p>
<p><strong>c.</strong> The same picture at three sample sizes:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="fl">4.5</span>, <span class="dv">3</span>, <span class="dv">1</span>))</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (n <span class="cf">in</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">100</span>, <span class="dv">2000</span>)) {</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>  sample_n <span class="ot">&lt;-</span> <span class="fu">rlogis</span>(n, <span class="at">location =</span> true_location, <span class="at">scale =</span> true_scale)</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="fu">ecdf</span>(sample_n), <span class="at">verticals =</span> <span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="st">""</span>, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">8</span>, <span class="dv">18</span>),</span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"n ="</span>, n), <span class="at">xlab =</span> <span class="st">"value"</span>, <span class="at">ylab =</span> <span class="st">"Fn(x)"</span>)</span>
<span id="cb79-8"><a href="#cb79-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">curve</span>(<span class="fu">plogis</span>(x, <span class="at">location =</span> true_location, <span class="at">scale =</span> true_scale),</span>
<span id="cb79-9"><a href="#cb79-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"firebrick"</span>)</span>
<span id="cb79-10"><a href="#cb79-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(<span class="fu">ecdf</span>(sample_n), <span class="at">verticals =</span> <span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="st">""</span>)</span>
<span id="cb79-11"><a href="#cb79-11" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_2_estimating_parameters_answers_files/figure-html/ex8-sample-sizes-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>ECDF and true cumulative distribution function for n = 20, 100 and 2000.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>With <span class="math inline">\(n = 20\)</span> the staircase is coarse and can be far from the curve; with <span class="math inline">\(n = 100\)</span> it follows the curve reasonably; with <span class="math inline">\(n = 2000\)</span> the two are almost indistinguishable. This is the <strong>law of large numbers</strong>: as the number of observations grows, the relative frequencies converge to the underlying probabilities. It is also the reason why the estimators of Sect. 3.3 are called <em>consistent</em> — with more data the estimate approaches the true value — and why the tests in Exercise 5 become so sensitive at large <code>n</code>: the sampling noise shrinks, so any systematic deviation stands out.</p>
<p><strong>d.</strong> Now we forget that we know the answer and let <code>fitdistr()</code> estimate the parameters:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>fit_logis <span class="ot">&lt;-</span> <span class="fu">fitdistr</span>(sim, <span class="st">"logistic"</span>)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>fit_logis</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   location      scale  
  5.2961717   2.2793268 
 (0.3907025) (0.1926476)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimate =</span> fit_logis<span class="sc">$</span>estimate,</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">std_error =</span> fit_logis<span class="sc">$</span>sd,</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">truth =</span> <span class="fu">c</span>(<span class="at">location =</span> true_location, <span class="at">scale =</span> true_scale),</span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower_2se =</span> fit_logis<span class="sc">$</span>estimate <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> fit_logis<span class="sc">$</span>sd,</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">upper_2se =</span> fit_logis<span class="sc">$</span>estimate <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> fit_logis<span class="sc">$</span>sd</span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           location     scale
estimate  5.2961717 2.2793268
std_error 0.3907025 0.1926476
truth     5.0000000 2.0000000
lower_2se 4.5147668 1.8940315
upper_2se 6.0775767 2.6646221</code></pre>
</div>
</div>
<p>The estimates are <span class="math inline">\(\hat{\text{location}} = 5.30\)</span> and <span class="math inline">\(\hat{\text{scale}} = 2.28\)</span>, against true values of 5 and 2. Both true values lie comfortably inside the interval “estimate <span class="math inline">\(\pm\)</span> two standard errors” (4.51 to 6.08 and 1.89 to 2.66), so maximum likelihood has done its job. But note how wide those intervals are: with 100 observations we cannot pin the scale down more precisely than “somewhere between 1.9 and 2.7”. The estimates are not <em>the</em> truth, they are a good guess with a quantified uncertainty — which is exactly what the second line of <code>fitdistr()</code> output is for.</p>
<p><strong>e.</strong> The log-likelihood by hand, exactly as in Exercise 2:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>ll_by_hand <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">dlogis</span>(sim,</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">location =</span> fit_logis<span class="sc">$</span>estimate[<span class="st">"location"</span>],</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">scale =</span> fit_logis<span class="sc">$</span>estimate[<span class="st">"scale"</span>],</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">log =</span> <span class="cn">TRUE</span>))</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">by_hand =</span> ll_by_hand, <span class="at">from_logLik =</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_logis)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    by_hand from_logLik 
  -283.8571   -283.8571 </code></pre>
</div>
</div>
<p>Identical, as it should be: <code>fitdistr()</code> found its estimates precisely by maximising this sum. As a check that it really is a <em>maximum</em>, the log-likelihood at the true parameter values must be slightly lower than at the estimates — the estimates are, by construction, the best possible values <em>for this sample</em>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">at_estimates =</span> ll_by_hand,</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">at_true_values =</span> <span class="fu">sum</span>(<span class="fu">dlogis</span>(sim, <span class="at">location =</span> true_location,</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">scale =</span> true_scale, <span class="at">log =</span> <span class="cn">TRUE</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  at_estimates at_true_values 
     -283.8571      -285.4908 </code></pre>
</div>
</div>
<p><strong>f.</strong> The comparison with a distribution that did <em>not</em> generate the data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>fit_normal_sim <span class="ot">&lt;-</span> <span class="fu">fitdistr</span>(sim, <span class="st">"normal"</span>)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>fit_normal_sim</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     mean         sd    
  5.0513858   4.3063272 
 (0.4306327) (0.3045033)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sapply</span>(<span class="fu">list</span>(<span class="at">logistic =</span> fit_logis, <span class="at">normal =</span> fit_normal_sim),</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>             <span class="cf">function</span>(f) <span class="fu">c</span>(<span class="at">logLik =</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(f)),</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">AIC =</span> <span class="fu">AIC</span>(f), <span class="at">BIC =</span> <span class="fu">BIC</span>(f))), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       logistic  normal
logLik  -283.86 -287.90
AIC      571.71  579.80
BIC      576.92  585.02</code></pre>
</div>
</div>
<p>The AIC does select the correct distribution: 571.7 for the logistic against 579.8 for the normal. Both have two parameters, so the penalty is identical and the ranking follows the log-likelihood directly. A difference of 8 AIC units is substantial, so in this case the criterion gives a clear and correct answer.</p>
<p>The graphical comparison is much less impressive:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(sim, <span class="at">breaks =</span> <span class="dv">15</span>, <span class="at">probability =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"grey93"</span>, <span class="at">border =</span> <span class="st">"grey60"</span>,</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">las =</span> <span class="dv">1</span>, <span class="at">xlab =</span> <span class="st">"simulated value"</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(sim)</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dlogis</span>(x, fit_logis<span class="sc">$</span>estimate[<span class="dv">1</span>], fit_logis<span class="sc">$</span>estimate[<span class="dv">2</span>]),</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"firebrick"</span>)</span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, fit_normal_sim<span class="sc">$</span>estimate[<span class="dv">1</span>], fit_normal_sim<span class="sc">$</span>estimate[<span class="dv">2</span>]),</span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"steelblue"</span>)</span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"firebrick"</span>, <span class="st">"steelblue"</span>),</span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"fitted logistic"</span>, <span class="st">"fitted normal"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_2_estimating_parameters_answers_files/figure-html/ex8-both-densities-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>The same 100 values with a fitted logistic (red) and a fitted normal (blue) density.</figcaption>
</figure>
</div>
</div>
</div>
<p>The two curves are almost on top of each other. Both are symmetric and bell-shaped; the logistic distribution merely has a slightly sharper peak and heavier tails, and that small difference in the tails is where the eight AIC units come from. No one could reliably pick the winner from this picture, and indeed a Shapiro-Wilk test would happily reject normality here while a KS test against the fitted logistic does not:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(sim)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  sim
W = 0.94834, p-value = 0.0006464</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(sim, <span class="st">"plogis"</span>, fit_logis<span class="sc">$</span>estimate[<span class="dv">1</span>], fit_logis<span class="sc">$</span>estimate[<span class="dv">2</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic one-sample Kolmogorov-Smirnov test

data:  sim
D = 0.043981, p-value = 0.9903
alternative hypothesis: two-sided</code></pre>
</div>
</div>
<p>Two lessons to close the practical with. First, <code>fitdistr()</code> and the AIC do work: they recovered both the right parameters and the right distribution. Second, they are working with small margins. Distinguishing between similar distributions demands a great deal of data, and even when the criterion points the right way the practical difference between the two fits may be negligible. The choice of a distribution should therefore rest primarily on knowledge of the process that generated the data — counts, proportions, waiting times, sums of many small contributions — and only secondarily on the numbers that come out of a fit (Dormann, Sect. 3.5).</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>