<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>QSBS Practical 3 — Regression: generalised linear models Answers</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="QSBS_3_regression_answers_files/libs/clipboard/clipboard.min.js"></script>
<script src="QSBS_3_regression_answers_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="QSBS_3_regression_answers_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="QSBS_3_regression_answers_files/libs/quarto-html/popper.min.js"></script>
<script src="QSBS_3_regression_answers_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="QSBS_3_regression_answers_files/libs/quarto-html/anchor.min.js"></script>
<link href="QSBS_3_regression_answers_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="QSBS_3_regression_answers_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="QSBS_3_regression_answers_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="QSBS_3_regression_answers_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="QSBS_3_regression_answers_files/libs/bootstrap/bootstrap-94053d6e10daeb31c4957f2bd90b11ca.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#exercise-1" id="toc-exercise-1" class="nav-link" data-scroll-target="#exercise-1">Exercise 1</a>
  <ul class="collapse">
  <li><a href="#answer" id="toc-answer" class="nav-link" data-scroll-target="#answer">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-2" id="toc-exercise-2" class="nav-link" data-scroll-target="#exercise-2">Exercise 2</a>
  <ul class="collapse">
  <li><a href="#answer-1" id="toc-answer-1" class="nav-link" data-scroll-target="#answer-1">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-3" id="toc-exercise-3" class="nav-link" data-scroll-target="#exercise-3">Exercise 3</a>
  <ul class="collapse">
  <li><a href="#answer-2" id="toc-answer-2" class="nav-link" data-scroll-target="#answer-2">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-4" id="toc-exercise-4" class="nav-link" data-scroll-target="#exercise-4">Exercise 4</a>
  <ul class="collapse">
  <li><a href="#answer-3" id="toc-answer-3" class="nav-link" data-scroll-target="#answer-3">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-5" id="toc-exercise-5" class="nav-link" data-scroll-target="#exercise-5">Exercise 5</a>
  <ul class="collapse">
  <li><a href="#answer-4" id="toc-answer-4" class="nav-link" data-scroll-target="#answer-4">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-6" id="toc-exercise-6" class="nav-link" data-scroll-target="#exercise-6">Exercise 6</a>
  <ul class="collapse">
  <li><a href="#answer-5" id="toc-answer-5" class="nav-link" data-scroll-target="#answer-5">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-7" id="toc-exercise-7" class="nav-link" data-scroll-target="#exercise-7">Exercise 7</a>
  <ul class="collapse">
  <li><a href="#answer-6" id="toc-answer-6" class="nav-link" data-scroll-target="#answer-6">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-8" id="toc-exercise-8" class="nav-link" data-scroll-target="#exercise-8">Exercise 8</a>
  <ul class="collapse">
  <li><a href="#answer-7" id="toc-answer-7" class="nav-link" data-scroll-target="#answer-7">Answer</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">QSBS Practical 3 — Regression: generalised linear models Answers</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In the previous practical we fitted a distribution to a sample: one set of parameter values for the whole data set. In this practical a parameter of the distribution is allowed to depend on a predictor variable. That is what a regression is (Dormann, Chap. 7 and 8).</p>
<p>The data for this practical come from the <code>qsbsdata</code> package; the negative binomial GLM and <code>dose.p()</code> come from <code>MASS</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(qsbsdata)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="exercise-1" class="level1">
<h1>Exercise 1</h1>
<p>The <code>RIKZdat</code> data set contains the number of macro-fauna species (<code>Richness</code>) found in 45 samples on nine Dutch beaches, together with the height of each sampling station relative to mean tidal level (<code>NAP</code>, in m). Stations with a high <code>NAP</code> are flooded less often; we expect fewer species there.</p>
<ol type="a">
<li>Plot <code>Richness</code> against <code>NAP</code>. Which distribution is the natural first candidate for the response variable, and which link function goes with it (Dormann, Table 7.1)? Write down the model in the notation <span class="math inline">\(y \sim \mathrm{Dist}(\ldots)\)</span>.</li>
<li>Fit the model with <code>glm()</code> and look at <code>summary()</code>. Report the two coefficients with their standard errors. On which scale are these numbers? Is the effect of <code>NAP</code> significant?</li>
<li>Back-transform the intercept. What does the resulting number mean in words? Then calculate, from the coefficients and by hand, the expected species richness at <code>NAP = -1</code>, <code>0</code> and <code>1</code> m and check with <code>predict(..., type = "response")</code>. By what <em>factor</em> does the expected richness change for every metre increase in <code>NAP</code>?</li>
<li>Calculate the deviance explained by the model from the null and residual deviance in the output. Compare the ratio residual deviance / residual degrees of freedom with 1 and comment.</li>
<li>Draw the fitted curve with its 95 % confidence band on top of the data: make a sequence of 100 <code>NAP</code> values, use <code>predict(..., se.fit = TRUE)</code>, add <span class="math inline">\(\pm 2\)</span> standard errors <em>on the link scale</em> and back-transform with <code>exp()</code> before drawing. Explain why the band is not symmetric around the curve.</li>
<li>Make the same plot with a logarithmic y-axis (<code>log = "y"</code>). What happens to the curve and to the band, and why (Dormann, Fig. 7.5)? Which of the two plots would you show in a report, and which to a statistician?</li>
</ol>
<section id="answer" class="level2">
<h2 class="anchored" data-anchor-id="answer">Answer</h2>
<p><strong>a.</strong> Always plot first:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Richness <span class="sc">~</span> NAP, <span class="at">data =</span> RIKZdat, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"NAP (m)"</span>, <span class="at">ylab =</span> <span class="st">"number of species"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex1-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Species richness of macro-fauna against the height of the sampling station relative to mean tidal level.</figcaption>
</figure>
</div>
</div>
</div>
<p><code>Richness</code> is a <strong>count</strong> (0, 1, 2, …), so the natural first candidate is the <strong>Poisson</strong> distribution, whose canonical link is the <strong>log</strong> (Table 7.1). The model is</p>
<p><span class="math display">\[\mathrm{Richness} \sim \mathrm{Pois}\big(\lambda = e^{\,\beta_0 + \beta_1 \cdot \mathrm{NAP}}\big), \qquad \text{i.e.}\quad \ln \lambda = \beta_0 + \beta_1 \cdot \mathrm{NAP}.\]</span></p>
<p>The log link guarantees that the expected count can never become negative, however large <code>NAP</code> gets.</p>
<p><strong>b.</strong> Fitting:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Richness <span class="sc">~</span> NAP, <span class="at">data =</span> RIKZdat, <span class="at">family =</span> poisson)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Richness ~ NAP, family = poisson, data = RIKZdat)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  1.79100    0.06329  28.297  &lt; 2e-16 ***
NAP         -0.55597    0.07163  -7.762 8.39e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 179.75  on 44  degrees of freedom
Residual deviance: 113.18  on 43  degrees of freedom
AIC: 259.18

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>The intercept is 1.791 (SE 0.063) and the slope for <code>NAP</code> is -0.556 (SE 0.072). Both numbers are on the <strong>link scale</strong> — they are coefficients of a straight line for <span class="math inline">\(\ln \lambda\)</span>, not for <span class="math inline">\(\lambda\)</span>. The slope differs from zero by almost eight standard errors (<span class="math inline">\(z = -7.8\)</span>, <span class="math inline">\(p &lt; 10^{-14}\)</span>): richness decreases significantly with height above mean tidal level.</p>
<p><strong>c.</strong> Back-transforming:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(fm1))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         NAP 
  5.9954272   0.5735136 </code></pre>
</div>
</div>
<p><span class="math inline">\(e^{\beta_0} =\)</span> 6 is the expected number of species at <code>NAP = 0</code>, i.e.&nbsp;at a station exactly at mean tidal level. Predictions by hand and with <code>predict()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>NAPvals <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>by_hand <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(fm1)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(fm1)[<span class="dv">2</span>] <span class="sc">*</span> NAPvals)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>with_predict <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm1, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">NAP =</span> NAPvals), <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">NAP =</span> NAPvals, by_hand, with_predict)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    1        2        3
NAP          -1.00000 0.000000 1.000000
by_hand      10.45385 5.995427 3.438459
with_predict 10.45385 5.995427 3.438459</code></pre>
</div>
</div>
<p>Every metre increase in <code>NAP</code> <em>multiplies</em> the expected richness by <span class="math inline">\(e^{\beta_1} =\)</span> 0.574, i.e.&nbsp;the richness drops by about 43 % per metre. On the link scale the effect is additive (−0.56 per metre); on the response scale it is multiplicative. That is what a log link does.</p>
<p><strong>d.</strong> Deviance explained and dispersion:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">deviance_explained =</span> (fm1<span class="sc">$</span>null.deviance <span class="sc">-</span> <span class="fu">deviance</span>(fm1)) <span class="sc">/</span> fm1<span class="sc">$</span>null.deviance,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">dispersion =</span> <span class="fu">deviance</span>(fm1) <span class="sc">/</span> <span class="fu">df.residual</span>(fm1))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>deviance_explained         dispersion 
         0.3703455          2.6321450 </code></pre>
</div>
</div>
<p>The model explains about 37 % of the deviance. The residual deviance per degree of freedom is 2.6, well above the value of 1 that a Poisson distribution implies (Dormann, Sect. 7.3.2, point 3). The counts are <strong>overdispersed</strong>: there is more variation among stations than the Poisson distribution allows for, presumably because stations on the same beach are similar and because other variables (exposure, grain size, …) also matter. The consequence is that the standard errors in the summary are too small. In this case the effect is so strong that the conclusion does not change, but in general one would move to a negative binomial model (see Exercise 2).</p>
<p><strong>e.</strong> The confidence band:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>NAPnew <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(RIKZdat<span class="sc">$</span>NAP), <span class="fu">max</span>(RIKZdat<span class="sc">$</span>NAP), <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>pr <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm1, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">NAP =</span> NAPnew), <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Richness <span class="sc">~</span> NAP, <span class="at">data =</span> RIKZdat, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"NAP (m)"</span>, <span class="at">ylab =</span> <span class="st">"number of species"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(NAPnew, <span class="fu">exp</span>(pr<span class="sc">$</span>fit), <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(NAPnew, <span class="fu">exp</span>(pr<span class="sc">$</span>fit <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> pr<span class="sc">$</span>se.fit), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(NAPnew, <span class="fu">exp</span>(pr<span class="sc">$</span>fit <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> pr<span class="sc">$</span>se.fit), <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex1-band-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Fitted Poisson regression (solid) with 95 % confidence band (dashed), response scale.</figcaption>
</figure>
</div>
</div>
</div>
<p><code>predict()</code> returns fitted values and standard errors on the link scale, where the estimates are (approximately) normally distributed and <span class="math inline">\(\pm 2\)</span> SE is a symmetric interval. Back-transforming with <code>exp()</code> stretches the upper half of the interval more than the lower half, so the band on the response scale is asymmetric — wider above the curve than below. The same happened to the confidence intervals of the hyena parameters in Dormann, Sect. 8.4.</p>
<p><strong>f.</strong> Logarithmic y-axis:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Richness <span class="sc">~</span> NAP, <span class="at">data =</span> RIKZdat, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">log =</span> <span class="st">"y"</span>,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"NAP (m)"</span>, <span class="at">ylab =</span> <span class="st">"number of species (log axis)"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(NAPnew, <span class="fu">exp</span>(pr<span class="sc">$</span>fit), <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(NAPnew, <span class="fu">exp</span>(pr<span class="sc">$</span>fit <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> pr<span class="sc">$</span>se.fit), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(NAPnew, <span class="fu">exp</span>(pr<span class="sc">$</span>fit <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> pr<span class="sc">$</span>se.fit), <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex1-logaxis-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>The same fit with a logarithmic y-axis (= the link scale): the curve becomes a straight line.</figcaption>
</figure>
</div>
</div>
</div>
<p>On a log axis the exponential curve becomes a <strong>straight line</strong> and the band becomes symmetric, because a logarithmic axis <em>is</em> the link scale: we are now looking at <span class="math inline">\(\ln \lambda = \beta_0 + \beta_1 \mathrm{NAP}\)</span> directly. Note that the station with 0 species disappears, because <span class="math inline">\(\log(0)\)</span> is not defined. The response-scale plot (e) is the one to show in a report: it shows the data as they were collected. The link-scale plot is what a statistician would want, because it shows the form of the <em>model</em> — a straight line — and makes it easy to judge whether a straight line on the link scale is adequate.</p>
</section>
</section>
<section id="exercise-2" class="level1">
<h1>Exercise 2</h1>
<p>The predictor can also be a factor. In <code>slugs</code>, the number of slugs was counted under 40 tiles in each of two grasslands (<code>field</code>: Nursery and Rookery).</p>
<ol type="a">
<li>Make a boxplot or a table of the counts per field, and calculate the mean and the variance per field. What do you expect a Poisson GLM to give as coefficients, before you fit anything?</li>
<li>Fit <code>glm(slugs ~ field, family = poisson)</code>. Which field is the reference level, and why that one? Show that <code>exp()</code> of the intercept equals the mean of the reference field, and that <code>exp()</code> of the sum of the two coefficients equals the mean of the other field. What does <code>exp()</code> of the <code>fieldRookery</code> coefficient on its own represent?</li>
<li>Look at <code>model.matrix(~ field, data = slugs)</code>. Explain how the factor with two levels has become a column of 0s and 1s, and where the intercept lives in this matrix (Dormann, Sect. 7.2.1).</li>
<li>Use <code>relevel()</code> to make Rookery the reference level and refit. Which numbers in the output change, and which stay the same (fitted means, deviances, AIC, p-value)?</li>
<li>Compare the residual deviance with the residual degrees of freedom. Are the counts overdispersed? Also compare, for each field, the variance with the mean.</li>
<li>Refit the model with <code>glm.nb()</code>. Report the estimate of the clumping parameter <span class="math inline">\(\theta\)</span> and compare the two models with AIC. What happened to the standard error and the p-value of the field effect, and why (Dormann, Sect. 8.3)? Which model would you report, and is the difference between the fields significant?</li>
</ol>
<section id="answer-1" class="level2">
<h2 class="anchored" data-anchor-id="answer-1">Answer</h2>
<p><strong>a.</strong> A look at the data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>slugs<span class="sc">$</span>field <span class="ot">&lt;-</span> <span class="fu">factor</span>(slugs<span class="sc">$</span>field)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(slugs<span class="sc">$</span>field, slugs<span class="sc">$</span>slugs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
           0  1  2  3  4  5  6  7  8  9 10
  Nursery 25  5  2  2  2  1  1  1  0  0  1
  Rookery  9  9  8  5  2  4  1  0  1  1  0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(slugs <span class="sc">~</span> field, <span class="at">data =</span> slugs, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">ylab =</span> <span class="st">"slugs per tile"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex2-describe-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Slug counts under 40 tiles in each of two grasslands.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">mean =</span> <span class="fu">tapply</span>(slugs<span class="sc">$</span>slugs, slugs<span class="sc">$</span>field, mean),</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">variance =</span> <span class="fu">tapply</span>(slugs<span class="sc">$</span>slugs, slugs<span class="sc">$</span>field, var))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Nursery  Rookery
mean     1.275000 2.275000
variance 5.332692 4.922436</code></pre>
</div>
</div>
<p>A Poisson GLM with a two-level factor fits one mean per field, on the log scale. So we expect the intercept to be <span class="math inline">\(\ln(1.275) =\)</span> 0.243 (the log of the Nursery mean) and the second coefficient to be <span class="math inline">\(\ln(2.275) - \ln(1.275) = \ln(2.275/1.275) =\)</span> 0.579.</p>
<p><strong>b.</strong> Fitting:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>fm2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(slugs <span class="sc">~</span> field, <span class="at">data =</span> slugs, <span class="at">family =</span> poisson)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = slugs ~ field, family = poisson, data = slugs)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)    0.2429     0.1400   1.735 0.082744 .  
fieldRookery   0.5790     0.1749   3.310 0.000932 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 224.86  on 79  degrees of freedom
Residual deviance: 213.44  on 78  degrees of freedom
AIC: 346.26

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>Nursery is the reference level simply because it comes first alphabetically (<code>levels(slugs$field)</code>). Back-transforming:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">coef</span>(fm2)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">exp_intercept =</span> <span class="fu">exp</span>(b[<span class="dv">1</span>]),</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">exp_sum =</span> <span class="fu">exp</span>(b[<span class="dv">1</span>] <span class="sc">+</span> b[<span class="dv">2</span>]),</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">exp_slope =</span> <span class="fu">exp</span>(b[<span class="dv">2</span>]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>exp_intercept.(Intercept)       exp_sum.(Intercept)    exp_slope.fieldRookery 
                 1.275000                  2.275000                  1.784314 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(slugs<span class="sc">$</span>slugs, slugs<span class="sc">$</span>field, mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nursery Rookery 
  1.275   2.275 </code></pre>
</div>
</div>
<p><span class="math inline">\(e^{\beta_0} = 1.275\)</span> is the mean of Nursery, <span class="math inline">\(e^{\beta_0 + \beta_1} = 2.275\)</span> is the mean of Rookery. <span class="math inline">\(e^{\beta_1} = 1.78\)</span> on its own is the <strong>ratio</strong> of the two means: Rookery has 1.78 times as many slugs per tile as Nursery. With a log link, a difference on the link scale is a ratio on the response scale.</p>
<p><strong>c.</strong> The design matrix:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">model.matrix</span>(<span class="sc">~</span> field, <span class="at">data =</span> slugs))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) fieldRookery
1           1            0
2           1            0
3           1            0
4           1            0
5           1            0
6           1            0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(<span class="fu">model.matrix</span>(<span class="sc">~</span> field, <span class="at">data =</span> slugs))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) fieldRookery
75           1            1
76           1            1
77           1            1
78           1            1
79           1            1
80           1            1</code></pre>
</div>
</div>
<p>R has replaced the factor by a <strong>dummy variable</strong> <code>fieldRookery</code> that is 0 for Nursery tiles and 1 for Rookery tiles. The intercept is the column of ones. The regression <span class="math inline">\(\ln \lambda = \beta_0 \cdot 1 + \beta_1 \cdot \mathrm{fieldRookery}\)</span> therefore gives <span class="math inline">\(\ln\lambda = \beta_0\)</span> for Nursery and <span class="math inline">\(\beta_0 + \beta_1\)</span> for Rookery. A factor with two levels needs one dummy, with <span class="math inline">\(k\)</span> levels it needs <span class="math inline">\(k - 1\)</span> dummies (Dormann, Sect. 7.2.2).</p>
<p><strong>d.</strong> Changing the reference level:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>slugs<span class="sc">$</span>field2 <span class="ot">&lt;-</span> <span class="fu">relevel</span>(slugs<span class="sc">$</span>field, <span class="at">ref =</span> <span class="st">"Rookery"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>fm2b <span class="ot">&lt;-</span> <span class="fu">glm</span>(slugs <span class="sc">~</span> field2, <span class="at">data =</span> slugs, <span class="at">family =</span> poisson)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(fm2b))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate Std. Error   z value     Pr(&gt;|z|)
(Intercept)    0.8219801  0.1048285  7.841190 4.462967e-15
field2Nursery -0.5790339  0.1749195 -3.310288 9.319987e-04</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">AIC =</span> <span class="fu">AIC</span>(fm2b), <span class="at">residual_deviance =</span> <span class="fu">deviance</span>(fm2b))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              AIC residual_deviance 
         346.2551          213.4378 </code></pre>
</div>
</div>
<p>The intercept is now the log of the Rookery mean and the slope is <span class="math inline">\(-0.579\)</span>: the same difference with the opposite sign. The fitted means, the null and residual deviance, the AIC and the p-value of the field effect are all unchanged. The reference level is a matter of presentation; the model is the same.</p>
<p><strong>e.</strong> Overdispersion:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">deviance</span>(fm2) <span class="sc">/</span> <span class="fu">df.residual</span>(fm2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.736382</code></pre>
</div>
</div>
<p>The residual deviance per degree of freedom is 2.7, far above 1. Within each field the variance (5.3 and 4.9) is more than twice the mean (1.3 and 2.3) — the counts are strongly <strong>overdispersed</strong> relative to a Poisson distribution: many tiles have no slugs, a few have many.</p>
<p><strong>f.</strong> Negative binomial:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>fm2nb <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(slugs <span class="sc">~</span> field, <span class="at">data =</span> slugs)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm2nb)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = slugs ~ field, data = slugs, init.theta = 0.7859313363, 
    link = log)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)    0.2429     0.2268   1.071   0.2840  
fieldRookery   0.5790     0.3069   1.886   0.0592 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(0.7859) family taken to be 1)

    Null deviance: 86.818  on 79  degrees of freedom
Residual deviance: 83.256  on 78  degrees of freedom
AIC: 291.35

Number of Fisher Scoring iterations: 1

              Theta:  0.786 
          Std. Err.:  0.224 

 2 x log-likelihood:  -285.350 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">theta =</span> fm2nb<span class="sc">$</span>theta, <span class="at">AIC_poisson =</span> <span class="fu">AIC</span>(fm2), <span class="at">AIC_negbin =</span> <span class="fu">AIC</span>(fm2nb))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      theta AIC_poisson  AIC_negbin 
  0.7859313 346.2550580 291.3499640 </code></pre>
</div>
</div>
<p>The clumping parameter is <span class="math inline">\(\theta \approx 0.79\)</span>; a small <span class="math inline">\(\theta\)</span> means strong clumping. The AIC drops by about 55 units, so the negative binomial model is vastly better. The coefficients are <strong>identical</strong> to the Poisson ones (both models fit the same two means), but the standard error of the field effect has grown from 0.17 to 0.31 and the p-value from 0.001 to 0.06. The Poisson model assumed a variance equal to the mean, and so under-estimated the uncertainty; the negative binomial model estimates the extra variance from the data. We would report the negative binomial model, and with it the difference between the fields is <em>not</em> significant at the 5 % level. This is a typical case: ignoring overdispersion makes effects look more significant than they are.</p>
</section>
</section>
<section id="exercise-3" class="level1">
<h1>Exercise 3</h1>
<p>In <code>wells</code>, groundwater samples from <code>n</code> wells were taken in each of 20 areas on Long Island (New York); in <code>y</code> of the wells the solvent TCE was detected. The areas differ in median nitrate concentration (<code>nitrate</code>, mg/l) and in whether the area is sewered (<code>sewer</code>).</p>
<ol type="a">
<li>Plot the proportion of contaminated wells <code>y/n</code> against <code>nitrate</code>. Why is a proportion not a good response variable for a <code>gaussian</code> GLM, and what should we use instead (Dormann, Sect. 8.1, the bioassay example)?</li>
<li>Build the two-column response <code>cbind(y, n - y)</code> and fit a binomial GLM with <code>nitrate</code> as predictor. Report the coefficients. Which link function was used?</li>
<li>Back-transform the intercept with <code>plogis()</code>: what is the fitted probability of contamination in an area with a nitrate concentration of 0 mg/l? What is it at 3 mg/l and at 7 mg/l? Do these calculations by hand from the coefficients and check them with <code>predict(..., type = "response")</code>.</li>
<li>Draw the fitted curve with a 95 % confidence band on top of the plot from (a). Remember that the standard errors are on the logit scale, so back-transform with <code>plogis()</code> <em>after</em> adding <span class="math inline">\(\pm 2\)</span> SE.</li>
<li>Use <code>dose.p()</code> to estimate the nitrate concentration at which half of the wells are contaminated. Compare this value with <code>range(wells$nitrate)</code> and explain why you should be reluctant to believe it.</li>
<li>Now fit a binomial GLM with the factor <code>sewer</code> as the only predictor. Back-transform the intercept and the sum of the coefficients to two proportions, and check them against the pooled numbers of contaminated and clean wells in sewered and unsewered areas (<code>aggregate()</code> or <code>tapply()</code>). Compare the p-value of the sewer effect with the p-value of <code>chisq.test()</code> on the <span class="math inline">\(2 \times 2\)</span> table of pooled counts (Dormann, Sect. 7.3.2). Are the two answers similar?</li>
</ol>
<section id="answer-2" class="level2">
<h2 class="anchored" data-anchor-id="answer-2">Answer</h2>
<p><strong>a.</strong> The data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y <span class="sc">/</span> n <span class="sc">~</span> nitrate, <span class="at">data =</span> wells, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="fu">sqrt</span>(n) <span class="sc">/</span> <span class="dv">4</span>,</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"nitrate (mg/l)"</span>, <span class="at">ylab =</span> <span class="st">"proportion of wells with TCE"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.6</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex3-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Proportion of wells in which TCE was detected against the median nitrate concentration of the area. Symbol size is proportional to the number of wells sampled.</figcaption>
</figure>
</div>
</div>
</div>
<p>A proportion is confined to the interval <span class="math inline">\([0, 1]\)</span>, a normal distribution is not, so a gaussian GLM could predict negative proportions or proportions above 1. Moreover, a proportion based on 5 wells is much less precise than one based on 86 wells, and a gaussian model treats them as equally informative. The proper description is the <strong>binomial</strong> distribution: out of <code>n</code> trials, <code>y</code> successes, with a success probability <span class="math inline">\(p\)</span> that depends on nitrate through the logit link: <span class="math inline">\(y \sim \mathrm{Binom}(n,\ p = \mathrm{logit}^{-1}(\beta_0 + \beta_1 \cdot \mathrm{nitrate}))\)</span>.</p>
<p><strong>b.</strong> Fitting:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>fm3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(y, n <span class="sc">-</span> y) <span class="sc">~</span> nitrate, <span class="at">data =</span> wells, <span class="at">family =</span> binomial)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(y, n - y) ~ nitrate, family = binomial, data = wells)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -2.71354    0.25042 -10.836  &lt; 2e-16 ***
nitrate      0.34156    0.05928   5.762 8.34e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 146.96  on 19  degrees of freedom
Residual deviance: 112.16  on 18  degrees of freedom
AIC: 161.44

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>The link is the <strong>logit</strong> (the default for <code>binomial</code>), so the intercept -2.714 and the slope 0.342 are on the log-odds scale. The probability of contamination increases significantly with nitrate (<span class="math inline">\(z = 5.8\)</span>).</p>
<p><strong>c.</strong> Back-transforming with the inverse logit <span class="math inline">\(p = e^{x}/(1 + e^{x})\)</span>, which R calls <code>plogis()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>nit <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">7</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>by_hand <span class="ot">&lt;-</span> <span class="fu">plogis</span>(<span class="fu">coef</span>(fm3)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(fm3)[<span class="dv">2</span>] <span class="sc">*</span> nit)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>with_predict <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm3, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">nitrate =</span> nit), <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">nitrate =</span> nit, by_hand, with_predict)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      1         2         3
nitrate      0.00000000 3.0000000 7.0000000
by_hand      0.06217926 0.1559257 0.4200358
with_predict 0.06217926 0.1559257 0.4200358</code></pre>
</div>
</div>
<p>At 0 mg/l nitrate the fitted probability of contamination is 0.062; at 3 mg/l it is 0.16 and at 7 mg/l 0.42. Note that the intercept refers to 0 mg/l, a concentration slightly below the lowest observed value (0.8 mg/l).</p>
<p><strong>d.</strong> Confidence band:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>nitnew <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(wells<span class="sc">$</span>nitrate), <span class="fu">max</span>(wells<span class="sc">$</span>nitrate), <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>pr3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm3, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">nitrate =</span> nitnew), <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y <span class="sc">/</span> n <span class="sc">~</span> nitrate, <span class="at">data =</span> wells, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="fu">sqrt</span>(n) <span class="sc">/</span> <span class="dv">4</span>,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"nitrate (mg/l)"</span>, <span class="at">ylab =</span> <span class="st">"proportion of wells with TCE"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.6</span>))</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(nitnew, <span class="fu">plogis</span>(pr3<span class="sc">$</span>fit), <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(nitnew, <span class="fu">plogis</span>(pr3<span class="sc">$</span>fit <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> pr3<span class="sc">$</span>se.fit), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(nitnew, <span class="fu">plogis</span>(pr3<span class="sc">$</span>fit <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> pr3<span class="sc">$</span>se.fit), <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex3-band-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Fitted logistic regression with 95 % confidence band.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>e.</strong> The “50 % dose”:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dose.p</span>(fm3, <span class="at">p =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Dose        SE
p = 0.5: 7.944572 0.7761761</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(wells<span class="sc">$</span>nitrate)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8 7.0</code></pre>
</div>
</div>
<p>Half of the wells are predicted to be contaminated at a nitrate concentration of about 7.9 mg/l (SE 0.8). But the highest observed concentration is 7.0 mg/l, and at that concentration only about 40 % of the wells are contaminated (with one area far below the curve). The estimate is an <strong>extrapolation</strong> beyond the range of the data: it relies on the logistic curve continuing to rise in the same way, which the data cannot confirm. In the bioassay example of Dormann the LD<span class="math inline">\(_{50}\)</span> lay in the middle of the concentration range, which is why it was trustworthy there.</p>
<p><strong>f.</strong> A categorical predictor in a binomial GLM:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>fm3s <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(y, n <span class="sc">-</span> y) <span class="sc">~</span> sewer, <span class="at">data =</span> wells, <span class="at">family =</span> binomial)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(fm3s))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error   z value     Pr(&gt;|z|)
(Intercept) -2.884180  0.2422006 -11.90823 1.072343e-32
seweryes     2.142242  0.2709669   7.90592 2.659618e-15</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">p_unsewered =</span> <span class="fu">plogis</span>(<span class="fu">coef</span>(fm3s)[<span class="dv">1</span>]),</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_sewered =</span> <span class="fu">plogis</span>(<span class="fu">sum</span>(<span class="fu">coef</span>(fm3s))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>p_unsewered.(Intercept)               p_sewered 
             0.05294118              0.32258065 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>pooled <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(<span class="fu">cbind</span>(y, n) <span class="sc">~</span> sewer, <span class="at">data =</span> wells, sum)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>pooled<span class="sc">$</span>proportion <span class="ot">&lt;-</span> pooled<span class="sc">$</span>y <span class="sc">/</span> pooled<span class="sc">$</span>n</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>pooled</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sewer   y   n proportion
1    no  18 340 0.05294118
2   yes 100 310 0.32258065</code></pre>
</div>
</div>
<p>The back-transformed intercept, 0.053, is exactly the pooled proportion of contaminated wells in unsewered areas (18 of 340), and the back-transformed sum, 0.323, is the pooled proportion in sewered areas (100 of 310). With a single two-level factor, the GLM simply reproduces the two observed proportions — just as in the smokers example (Dormann, Sect. 7.3.2).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="at">contaminated =</span> pooled<span class="sc">$</span>y, <span class="at">clean =</span> pooled<span class="sc">$</span>n <span class="sc">-</span> pooled<span class="sc">$</span>y)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(tab) <span class="ot">&lt;-</span> pooled<span class="sc">$</span>sewer</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>tab</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    contaminated clean
no            18   322
yes          100   210</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  tab
X-squared = 77.542, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Both tests find an overwhelmingly significant difference (<span class="math inline">\(p \approx 10^{-15}\)</span> for the GLM, <span class="math inline">\(p \approx 10^{-18}\)</span> for the <span class="math inline">\(\chi^2\)</span> test). The numbers are not identical because the two tests use different approximations (a <span class="math inline">\(z\)</span>-test on a log-odds ratio versus a <span class="math inline">\(\chi^2\)</span> test on counts), but they answer the same question and agree in every practical sense. The <span class="math inline">\(\chi^2\)</span> test is a special case of the binomial GLM.</p>
</section>
</section>
<section id="exercise-4" class="level1">
<h1>Exercise 4</h1>
<p>The classic species–area relationship states that the number of species <span class="math inline">\(S\)</span> on an island grows with the island’s area <span class="math inline">\(A\)</span> as a power law: <span class="math inline">\(S = c A^z\)</span>. The <code>gala</code> data set gives the number of plant species on 29 Galápagos islands.</p>
<ol type="a">
<li>Plot <code>Species</code> against <code>Area</code>, and then against <code>log(Area)</code>. Which plot is more useful, and why?</li>
<li>Show, by taking the logarithm of both sides of <span class="math inline">\(S = c A^z\)</span>, that the power law is a <em>linear</em> model on the log scale with predictor <span class="math inline">\(\log A\)</span>. Which family and link in <code>glm()</code> fit exactly this model without transforming the response?</li>
<li>Fit <code>glm(Species ~ log(Area), family = poisson)</code>. Read <span class="math inline">\(z\)</span> directly from the output and calculate <span class="math inline">\(c\)</span>. Is <span class="math inline">\(z\)</span> in the range 0.2–0.35 that is typical for islands?</li>
<li>Calculate the ratio residual deviance / residual degrees of freedom. What do you conclude, and what does it mean for the standard errors and p-values in the Poisson output?</li>
<li>Refit with <code>glm.nb()</code>. Compare the estimates of <span class="math inline">\(z\)</span>, their standard errors, and the AIC of the two models. Draw both fitted curves on the plot of <code>Species</code> against <code>log(Area)</code>.</li>
<li>A third option, common in older literature, is <code>lm(log(Species) ~ log(Area))</code>. Fit it and compare its <span class="math inline">\(z\)</span> with the other two. Explain why the AIC of this model <em>cannot</em> be compared with the AICs from (e) (Dormann, Sect. 7.2.2), and what the model assumes about the noise that the Poisson and negative binomial models do not.</li>
</ol>
<section id="answer-3" class="level2">
<h2 class="anchored" data-anchor-id="answer-3">Answer</h2>
<p><strong>a.</strong> Two plots:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Species <span class="sc">~</span> Area, <span class="at">data =</span> gala, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">xlab =</span> <span class="st">"area (km²)"</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Species <span class="sc">~</span> <span class="fu">log</span>(Area), <span class="at">data =</span> gala, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">xlab =</span> <span class="st">"log(area)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex4-plots-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Number of plant species on 29 Galápagos islands against island area (left) and log island area (right).</figcaption>
</figure>
</div>
</div>
</div>
<p>Island areas span five orders of magnitude (0.01 to 4700 km²), so on the linear scale almost all islands are squashed against the y-axis and two large islands dominate. On the log scale the islands are spread out evenly and the relationship becomes visible. The log of the predictor is the useful scale here.</p>
<p><strong>b.</strong> Taking logarithms of <span class="math inline">\(S = cA^z\)</span> gives <span class="math display">\[\ln S = \ln c + z \ln A,\]</span> a straight line in <span class="math inline">\(\ln A\)</span> with intercept <span class="math inline">\(\ln c\)</span> and slope <span class="math inline">\(z\)</span>. This is exactly a model with a <strong>log link</strong> for the mean of <span class="math inline">\(S\)</span> and predictor <span class="math inline">\(\log(A)\)</span>. Since <span class="math inline">\(S\)</span> is a count, the natural family is <code>poisson</code> (whose canonical link is the log): <code>glm(Species ~ log(Area), family = poisson)</code>. The response itself is not transformed; only its expected value is modelled on the log scale.</p>
<p><strong>c.</strong> Fitting:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>fm4p <span class="ot">&lt;-</span> <span class="fu">glm</span>(Species <span class="sc">~</span> <span class="fu">log</span>(Area), <span class="at">data =</span> gala, <span class="at">family =</span> poisson)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(fm4p))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate  Std. Error  z value Pr(&gt;|z|)
(Intercept) 3.2409698 0.043050230 75.28345        0
log(Area)   0.3429906 0.007346425 46.68809        0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">z =</span> <span class="fu">coef</span>(fm4p)[<span class="dv">2</span>], <span class="at">c =</span> <span class="fu">exp</span>(<span class="fu">coef</span>(fm4p)[<span class="dv">1</span>]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  z.log(Area) c.(Intercept) 
    0.3429906    25.5584970 </code></pre>
</div>
</div>
<p><span class="math inline">\(z =\)</span> 0.343 and <span class="math inline">\(c = e^{\beta_0} =\)</span> 25.6 species for an island of 1 km². The exponent is well within the typical island range of 0.2–0.35.</p>
<p><strong>d.</strong> Dispersion:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">deviance</span>(fm4p) <span class="sc">/</span> <span class="fu">df.residual</span>(fm4p)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 23.7118</code></pre>
</div>
</div>
<p>A residual deviance per degree of freedom of about 24 is enormous: the species counts vary around the fitted curve far more than a Poisson distribution allows — islands differ in much more than area (elevation, isolation, habitat diversity). The Poisson standard errors (0.007 for <span class="math inline">\(z\)</span>!) are therefore wildly too small and the <span class="math inline">\(z\)</span>-values (47) and p-values (0) are meaningless.</p>
<p><strong>e.</strong> Negative binomial:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>fm4nb <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Species <span class="sc">~</span> <span class="fu">log</span>(Area), <span class="at">data =</span> gala)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(fm4nb))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error  z value      Pr(&gt;|z|)
(Intercept) 3.1495864 0.14035397 22.44031 1.591359e-111
log(Area)   0.3669952 0.03596514 10.20419  1.898911e-24</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">theta =</span> fm4nb<span class="sc">$</span>theta, <span class="at">AIC_poisson =</span> <span class="fu">AIC</span>(fm4p), <span class="at">AIC_negbin =</span> <span class="fu">AIC</span>(fm4nb))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      theta AIC_poisson  AIC_negbin 
   2.634311  800.026632  273.992627 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>Anew <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(<span class="fu">log</span>(gala<span class="sc">$</span>Area)), <span class="fu">max</span>(<span class="fu">log</span>(gala<span class="sc">$</span>Area)), <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Species <span class="sc">~</span> <span class="fu">log</span>(Area), <span class="at">data =</span> gala, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">xlab =</span> <span class="st">"log(area)"</span>)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(Anew, <span class="fu">predict</span>(fm4p, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Area =</span> <span class="fu">exp</span>(Anew)), <span class="at">type =</span> <span class="st">"response"</span>), <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(Anew, <span class="fu">predict</span>(fm4nb, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Area =</span> <span class="fu">exp</span>(Anew)), <span class="at">type =</span> <span class="st">"response"</span>), <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="fu">c</span>(<span class="st">"Poisson"</span>, <span class="st">"negative binomial"</span>), <span class="at">lty =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">bty =</span> <span class="st">"n"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex4-negbin-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Species–area relationship fitted with a Poisson (solid) and a negative binomial (dashed) GLM.</figcaption>
</figure>
</div>
</div>
</div>
<p>The two estimates of <span class="math inline">\(z\)</span> (0.34 and 0.37) are similar and the curves almost coincide, but the standard error of <span class="math inline">\(z\)</span> is five times larger under the negative binomial model (0.036 instead of 0.007) — that is the honest uncertainty. The AIC drops by several hundred units, so the negative binomial model is far better. The Poisson curve is pulled slightly more towards the large islands, because under a Poisson distribution the large counts are assumed to be very precise and therefore get more weight.</p>
<p><strong>f.</strong> Log-transformed response:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>fm4lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Species) <span class="sc">~</span> <span class="fu">log</span>(Area), <span class="at">data =</span> gala)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(fm4lm))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) 2.8338361 0.15708986 18.039587 1.368653e-16
log(Area)   0.4042697 0.04120598  9.810947 2.134924e-10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">Poisson =</span> <span class="fu">coef</span>(fm4p), <span class="at">negbin =</span> <span class="fu">coef</span>(fm4nb), <span class="at">lm_log =</span> <span class="fu">coef</span>(fm4lm))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        (Intercept) log(Area)
Poisson    3.240970 0.3429906
negbin     3.149586 0.3669952
lm_log     2.833836 0.4042697</code></pre>
</div>
</div>
<p>The linear model on <span class="math inline">\(\ln S\)</span> gives <span class="math inline">\(z = 0.40\)</span>, somewhat larger, and a smaller intercept. Its AIC (70.1) looks much better than the others, but this is an <strong>illusion</strong>: the likelihood of <code>fm4lm</code> is calculated for the <em>transformed</em> data <span class="math inline">\(\ln S\)</span>, whereas the other two are calculated for the counts <span class="math inline">\(S\)</span> themselves. Likelihoods, and therefore AICs, can only be compared between models of the <em>same</em> response (Dormann, Sect. 7.2.2, the butterfly example). The log-normal model also assumes something different about the noise: that the scatter around the curve is symmetric and of constant size on the log scale, i.e.&nbsp;multiplicative on the original scale, so that its fitted curve describes the <em>median</em> rather than the mean number of species (see also Exercise 7). The Poisson and negative binomial models describe the mean of the counts directly, and the negative binomial estimates how the variance grows with the mean.</p>
</section>
</section>
<section id="exercise-5" class="level1">
<h1>Exercise 5</h1>
<p>In this exercise we calculate the Poisson regression of Exercise 1 by hand, following Dormann, Sect. 8.2.1. Take <code>RIKZdat</code> again, with <code>Richness</code> as the response and <code>NAP</code> as the predictor.</p>
<ol type="a">
<li>Write a function <code>llfun(parms)</code> that takes a vector of two parameters (<span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>), calculates <span class="math inline">\(\lambda_i = e^{\beta_0 + \beta_1 \mathrm{NAP}_i}\)</span> for every station and returns the sum of <code>dpois(Richness, lambda, log = TRUE)</code>. Test it with <code>llfun(c(1, 0))</code> and with <code>llfun(c(1.8, -0.5))</code>. Which of the two is more plausible?</li>
<li>Fix <span class="math inline">\(\beta_0\)</span> at 1.8 and calculate the log-likelihood for a sequence of 100 values of <span class="math inline">\(\beta_1\)</span> between <span class="math inline">\(-1.5\)</span> and <span class="math inline">\(0.5\)</span> (a <code>for</code> loop or <code>sapply()</code>). Plot the result. This is a <strong>likelihood profile</strong>. Read off the best <span class="math inline">\(\beta_1\)</span> with <code>which.max()</code>.</li>
<li>Now do the same on a grid of 100 × 100 combinations of <span class="math inline">\(\beta_0\)</span> (between 1 and 2.5) and <span class="math inline">\(\beta_1\)</span> (between <span class="math inline">\(-1.5\)</span> and 0.5), store the values in a matrix and show it with <code>contour()</code>. Find the best combination with <code>which(..., arr.ind = TRUE)</code>. Describe the shape of the contours: are the two parameters independent?</li>
<li>Let <code>optim()</code> do the work: maximise <code>llfun</code> starting from <code>c(1, 0)</code> (remember <code>fnscale = -1</code> and ask for the <code>hessian</code>). Compare <code>op$par</code> and <code>op$value</code> with the coefficients and <code>logLik()</code> of the GLM from Exercise 1. Did the optimiser converge?</li>
<li>Calculate the standard errors from the Hessian with <code>sqrt(diag(solve(-op$hessian)))</code> and compare them with the standard errors in the GLM summary (Dormann, Side Note 6).</li>
<li>Why does the likelihood surface in (c) have its maximum at an intercept that is <em>not</em> the log of the mean richness? What would the intercept be if you centred <code>NAP</code> first (<code>NAP - mean(NAP)</code>)? Check it.</li>
</ol>
<section id="answer-4" class="level2">
<h2 class="anchored" data-anchor-id="answer-4">Answer</h2>
<p><strong>a.</strong> The likelihood function is the heart of the analysis: it <em>is</em> the model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>llfun <span class="ot">&lt;-</span> <span class="cf">function</span>(parms) {</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  lambda <span class="ot">&lt;-</span> <span class="fu">exp</span>(parms[<span class="dv">1</span>] <span class="sc">+</span> parms[<span class="dv">2</span>] <span class="sc">*</span> RIKZdat<span class="sc">$</span>NAP)</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">dpois</span>(RIKZdat<span class="sc">$</span>Richness, <span class="at">lambda =</span> lambda, <span class="at">log =</span> <span class="cn">TRUE</span>))</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">llfun</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>)), <span class="fu">llfun</span>(<span class="fu">c</span>(<span class="fl">1.8</span>, <span class="sc">-</span><span class="fl">0.5</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -216.2582 -127.8999</code></pre>
</div>
</div>
<p>For every station the function calculates the expected richness <span class="math inline">\(\lambda_i\)</span> from the parameters, then the log-probability of the observed count under a Poisson distribution with that <span class="math inline">\(\lambda_i\)</span>, and sums. The second parameter combination has a much higher log-likelihood (−107 versus −167) and is therefore far more plausible.</p>
<p><strong>b.</strong> The likelihood profile for the slope:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">1.5</span>, <span class="fl">0.5</span>, <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>ll <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">100</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>) ll[i] <span class="ot">&lt;-</span> <span class="fu">llfun</span>(<span class="fu">c</span>(<span class="fl">1.8</span>, beta1[i]))</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(beta1, ll, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="fu">expression</span>(beta[<span class="dv">1</span>]), <span class="at">ylab =</span> <span class="st">"log-likelihood"</span>)</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> beta1[<span class="fu">which.max</span>(ll)], <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex5-profile-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Likelihood profile for the slope, with the intercept fixed at 1.8.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>beta1[<span class="fu">which.max</span>(ll)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.5505051</code></pre>
</div>
</div>
<p>With the intercept fixed at 1.8 the best slope is about −0.56.</p>
<p><strong>c.</strong> The likelihood surface:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>beta0 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="fl">2.5</span>, <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">1.5</span>, <span class="fl">0.5</span>, <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>ll.m <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> <span class="dv">100</span>, <span class="at">ncol =</span> <span class="dv">100</span>)</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>) {</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>) {</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>    ll.m[i, j] <span class="ot">&lt;-</span> <span class="fu">llfun</span>(<span class="fu">c</span>(beta0[i], beta1[j]))</span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb79-8"><a href="#cb79-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb79-9"><a href="#cb79-9" aria-hidden="true" tabindex="-1"></a><span class="fu">contour</span>(beta0, beta1, ll.m, <span class="at">nlevels =</span> <span class="dv">40</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb79-10"><a href="#cb79-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="fu">expression</span>(beta[<span class="dv">0</span>]), <span class="at">ylab =</span> <span class="fu">expression</span>(beta[<span class="dv">1</span>]))</span>
<span id="cb79-11"><a href="#cb79-11" aria-hidden="true" tabindex="-1"></a>best <span class="ot">&lt;-</span> <span class="fu">which</span>(ll.m <span class="sc">==</span> <span class="fu">max</span>(ll.m), <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span>
<span id="cb79-12"><a href="#cb79-12" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(beta0[best[<span class="dv">1</span>]], beta1[best[<span class="dv">2</span>]], <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex5-surface-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Log-likelihood surface for intercept and slope. The red point is the maximum on the grid.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">beta0 =</span> beta0[best[<span class="dv">1</span>]], <span class="at">beta1 =</span> beta1[best[<span class="dv">2</span>]], <span class="at">loglik =</span> <span class="fu">max</span>(ll.m))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       beta0        beta1       loglik 
   1.7878788   -0.5505051 -127.5951913 </code></pre>
</div>
</div>
<p>The contours are elongated ellipses, tilted: a larger intercept goes together with a more negative slope. The two parameters are <strong>not independent</strong> — they are negatively correlated, as is almost always the case for an intercept and a slope (Dormann, Fig. 8.7). This is why we must optimise both at the same time rather than one after the other.</p>
<p><strong>d.</strong> Optimisation:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>op <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), <span class="at">fn =</span> llfun, <span class="at">control =</span> <span class="fu">list</span>(<span class="at">fnscale =</span> <span class="sc">-</span><span class="dv">1</span>),</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">method =</span> <span class="st">"BFGS"</span>, <span class="at">hessian =</span> <span class="cn">TRUE</span>)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>op<span class="sc">$</span>par; op<span class="sc">$</span>value; op<span class="sc">$</span>convergence</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1.7909969 -0.5559736</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -127.5904</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">optim =</span> op<span class="sc">$</span>par, <span class="at">glm =</span> <span class="fu">coef</span>(fm1))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept)        NAP
optim    1.790997 -0.5559736
glm      1.790997 -0.5559735</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">optim =</span> op<span class="sc">$</span>value, <span class="at">glm =</span> <span class="fu">logLik</span>(fm1))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    optim       glm 
-127.5904 -127.5904 </code></pre>
</div>
</div>
<p><code>optim()</code> finds the same coefficients as <code>glm()</code> to four decimals, the same maximum log-likelihood, and <code>convergence = 0</code> tells us that it converged. <code>glm()</code> uses a different algorithm (iteratively re-weighted least squares) but maximises the same likelihood, so it must arrive at the same place.</p>
<p><strong>e.</strong> Standard errors from the Hessian:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">optim =</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">solve</span>(<span class="sc">-</span>op<span class="sc">$</span>hessian))),</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">glm =</span> <span class="fu">coef</span>(<span class="fu">summary</span>(fm1))[, <span class="st">"Std. Error"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept)        NAP
optim  0.06329338 0.07163200
glm    0.06329337 0.07163199</code></pre>
</div>
</div>
<p>The Hessian is the matrix of second derivatives at the maximum; its (negative) inverse is the variance-covariance matrix of the estimates, and the square roots of its diagonal are the standard errors. They agree with the GLM output to three decimals.</p>
<p><strong>f.</strong> The intercept is the log of the expected richness at <code>NAP = 0</code>, not at the mean <code>NAP</code>. Since the mean <code>NAP</code> is not 0 (it is 0.348), the intercept is not the log of the mean richness (1.739). If we centre the predictor, <code>NAP = 0</code> becomes the average station:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>RIKZdat<span class="sc">$</span>NAPc <span class="ot">&lt;-</span> RIKZdat<span class="sc">$</span>NAP <span class="sc">-</span> <span class="fu">mean</span>(RIKZdat<span class="sc">$</span>NAP)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>fm1c <span class="ot">&lt;-</span> <span class="fu">glm</span>(Richness <span class="sc">~</span> NAPc, <span class="at">data =</span> RIKZdat, <span class="at">family =</span> poisson)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">intercept_centred =</span> <span class="fu">coef</span>(fm1c)[<span class="dv">1</span>], <span class="at">log_mean_richness =</span> <span class="fu">log</span>(<span class="fu">mean</span>(RIKZdat<span class="sc">$</span>Richness)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>intercept_centred.(Intercept)             log_mean_richness 
                     1.597691                      1.738515 </code></pre>
</div>
</div>
<p>Now the intercept is close to the log of the mean richness (exactly equal only if the relationship were flat; with a curved fit the mean of <span class="math inline">\(\lambda_i\)</span> is slightly larger than <span class="math inline">\(\lambda\)</span> at the mean <span class="math inline">\(x\)</span>). The slope is unchanged by centring.</p>
</section>
</section>
<section id="exercise-6" class="level1">
<h1>Exercise 6</h1>
<p>Some relationships are not linear on any link scale. In <code>beepollen</code>, Harder and Thomson (1989) measured the proportion of a flower’s pollen that a bee removed (<code>removed</code>) as a function of how long it stayed at the flower (<code>duration</code>, s). A bee cannot remove more than all of the pollen, so we expect the curve to level off.</p>
<ol type="a">
<li>Plot <code>removed</code> against <code>duration</code>. Fit a straight line with a gaussian GLM and draw it. Where does the line go wrong, and what would it predict for a visit of 200 s?</li>
<li>A saturating alternative is the Michaelis–Menten function <span class="math inline">\(y = \dfrac{a\,x}{b + x}\)</span> (Dormann, Sect. 8.2.2). What is the meaning of <span class="math inline">\(a\)</span>, and of <span class="math inline">\(b\)</span>? Sketch (or reason out) what the curve looks like for <span class="math inline">\(a = 0.9\)</span> and <span class="math inline">\(b = 15\)</span>.</li>
<li>Write a likelihood function for the model <span class="math inline">\(\mathrm{removed} \sim N\!\left(\mu = \dfrac{a\,\mathrm{duration}}{b + \mathrm{duration}},\ \sigma\right)\)</span> with a <em>named</em> parameter vector <code>c(a = , b = , logsigma = )</code>. Why do we estimate <span class="math inline">\(\log \sigma\)</span> rather than <span class="math inline">\(\sigma\)</span> itself? Test the function with <code>c(a = 0.9, b = 15, logsigma = -2)</code>.</li>
<li>Maximise it with <code>optim(..., method = "BFGS", hessian = TRUE)</code>. Report <span class="math inline">\(\hat a\)</span>, <span class="math inline">\(\hat b\)</span> and <span class="math inline">\(\hat\sigma\)</span> with their standard errors, and use <span class="math inline">\(\hat a/\mathrm{SE}(\hat a)\)</span> etc. as <span class="math inline">\(t\)</span>-values to judge which parameters differ significantly from 0. Draw the fitted curve on the plot with <code>curve()</code>.</li>
<li>Calculate the AIC of this model by hand from <code>op$value</code> (how many parameters?) and compare it with <code>AIC()</code> of the straight line from (a). Which model is better, and by how much?</li>
<li>The data contain queens and workers (<code>queen</code>). Extend the likelihood function so that <span class="math inline">\(a\)</span> differs between the two castes (e.g.&nbsp;<span class="math inline">\(a = a_0 + a_1 \cdot \mathrm{queen}\)</span>) and refit. Do queens remove more pollen than workers in the limit of long visits? Judge this from the estimate and standard error of <span class="math inline">\(a_1\)</span> and from the AIC.</li>
</ol>
<section id="answer-5" class="level2">
<h2 class="anchored" data-anchor-id="answer-5">Answer</h2>
<p><strong>a.</strong> A straight line:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(removed <span class="sc">~</span> duration, <span class="at">data =</span> beepollen, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"visit duration (s)"</span>, <span class="at">ylab =</span> <span class="st">"proportion of pollen removed"</span>)</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>fm6lin <span class="ot">&lt;-</span> <span class="fu">glm</span>(removed <span class="sc">~</span> duration, <span class="at">data =</span> beepollen, <span class="at">family =</span> gaussian)</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(fm6lin, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"grey40"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex6-line-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Proportion of pollen removed against visit duration, with a straight-line fit.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fm6lin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)    duration 
0.317850710 0.008003029 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fm6lin, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">duration =</span> <span class="dv">200</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
1.918456 </code></pre>
</div>
</div>
<p>The line is too low for short visits (up to about 20 s the removal rises steeply) and too high for the longest visits, where the points level off. For a 200 s visit it predicts that 1.92 of the pollen is removed — 190 % — which is impossible: a proportion cannot exceed 1.</p>
<p><strong>b.</strong> In <span class="math inline">\(y = a x /(b + x)\)</span>, <span class="math inline">\(a\)</span> is the <strong>asymptote</strong>: as <span class="math inline">\(x \to \infty\)</span>, <span class="math inline">\(y \to a\)</span>, so <span class="math inline">\(a\)</span> is the maximum proportion of pollen a bee can remove. <span class="math inline">\(b\)</span> is the <strong>half-saturation</strong> duration: at <span class="math inline">\(x = b\)</span>, <span class="math inline">\(y = a b/(2b) = a/2\)</span>. For <span class="math inline">\(a = 0.9\)</span> and <span class="math inline">\(b = 15\)</span> the curve starts at 0, rises steeply (initial slope <span class="math inline">\(a/b = 0.06\)</span> per second), reaches 0.45 at 15 s, 0.72 at 60 s and approaches 0.9 for very long visits.</p>
<p><strong>c.</strong> The likelihood function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>llmm <span class="ot">&lt;-</span> <span class="cf">function</span>(parms) {</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  mu <span class="ot">&lt;-</span> parms[<span class="st">"a"</span>] <span class="sc">*</span> beepollen<span class="sc">$</span>duration <span class="sc">/</span> (parms[<span class="st">"b"</span>] <span class="sc">+</span> beepollen<span class="sc">$</span>duration)</span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">dnorm</span>(beepollen<span class="sc">$</span>removed, <span class="at">mean =</span> mu, <span class="at">sd =</span> <span class="fu">exp</span>(parms[<span class="st">"logsigma"</span>]), <span class="at">log =</span> <span class="cn">TRUE</span>))</span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a><span class="fu">llmm</span>(<span class="fu">c</span>(<span class="at">a =</span> <span class="fl">0.9</span>, <span class="at">b =</span> <span class="dv">15</span>, <span class="at">logsigma =</span> <span class="sc">-</span><span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25.9865</code></pre>
</div>
</div>
<p>The standard deviation must be positive. If we optimised <span class="math inline">\(\sigma\)</span> directly, <code>optim()</code> might try a negative value, <code>dnorm()</code> would return <code>NaN</code>, and the optimisation would crash. By estimating <span class="math inline">\(\log\sigma\)</span> instead, any real number the optimiser tries is turned into a positive <span class="math inline">\(\sigma\)</span> by <code>exp()</code>. This is the same trick as a link function.</p>
<p><strong>d.</strong> Optimisation:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>op6 <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="at">a =</span> <span class="fl">0.9</span>, <span class="at">b =</span> <span class="dv">15</span>, <span class="at">logsigma =</span> <span class="sc">-</span><span class="dv">2</span>), <span class="at">fn =</span> llmm,</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">control =</span> <span class="fu">list</span>(<span class="at">fnscale =</span> <span class="sc">-</span><span class="dv">1</span>), <span class="at">method =</span> <span class="st">"BFGS"</span>, <span class="at">hessian =</span> <span class="cn">TRUE</span>)</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>op6<span class="sc">$</span>convergence</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>se6 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">solve</span>(<span class="sc">-</span>op6<span class="sc">$</span>hessian)))</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">estimate =</span> op6<span class="sc">$</span>par, <span class="at">SE =</span> se6, <span class="at">t =</span> op6<span class="sc">$</span>par <span class="sc">/</span> se6)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           estimate        SE          t
a         0.9344272 0.1009051   9.260453
b        14.7664347 3.8343971   3.851045
logsigma -1.9851190 0.1031420 -19.246457</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(op6<span class="sc">$</span>par[<span class="st">"logsigma"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> logsigma 
0.1373643 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(removed <span class="sc">~</span> duration, <span class="at">data =</span> beepollen, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"visit duration (s)"</span>, <span class="at">ylab =</span> <span class="st">"proportion of pollen removed"</span>)</span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(fm6lin, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"grey60"</span>)</span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a>p6 <span class="ot">&lt;-</span> op6<span class="sc">$</span>par</span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(p6[<span class="st">"a"</span>] <span class="sc">*</span> x <span class="sc">/</span> (p6[<span class="st">"b"</span>] <span class="sc">+</span> x), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex6-optim-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Michaelis–Menten fit (black) compared with the straight line (grey).</figcaption>
</figure>
</div>
</div>
</div>
<p>The asymptote is <span class="math inline">\(\hat a =\)</span> 0.93 (SE 0.1): a bee removes at most about 93 % of the pollen. The half-saturation time is <span class="math inline">\(\hat b =\)</span> 14.8 s (SE 3.8), and <span class="math inline">\(\hat\sigma = e^{\widehat{\log\sigma}} =\)</span> 0.137. The <span class="math inline">\(t\)</span>-values for <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are 9.3 and 3.9, far above the critical value of about 2 (with 44 residual degrees of freedom), so both are clearly different from 0. (The <span class="math inline">\(t\)</span>-value of <span class="math inline">\(\log\sigma\)</span> tests whether <span class="math inline">\(\sigma = 1\)</span>, which is not an interesting hypothesis.)</p>
<p><strong>e.</strong> AIC by hand: the model has three parameters (<span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>, <span class="math inline">\(\sigma\)</span>), so <span class="math inline">\(\mathrm{AIC} = -2\ell + 2 \cdot 3\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">AIC_MichaelisMenten =</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> op6<span class="sc">$</span>value <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> <span class="dv">3</span>,</span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">AIC_line =</span> <span class="fu">AIC</span>(fm6lin))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>AIC_MichaelisMenten            AIC_line 
          -47.22096           -33.50690 </code></pre>
</div>
</div>
<p>The saturating model is better by about 14 AIC units — a large difference, even though both models use three parameters (the line also estimates an intercept, a slope and <span class="math inline">\(\sigma\)</span>).</p>
<p><strong>f.</strong> Separate asymptotes for queens and workers:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>llmm2 <span class="ot">&lt;-</span> <span class="cf">function</span>(parms) {</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>  a <span class="ot">&lt;-</span> parms[<span class="st">"a0"</span>] <span class="sc">+</span> parms[<span class="st">"a1"</span>] <span class="sc">*</span> beepollen<span class="sc">$</span>queen</span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>  mu <span class="ot">&lt;-</span> a <span class="sc">*</span> beepollen<span class="sc">$</span>duration <span class="sc">/</span> (parms[<span class="st">"b"</span>] <span class="sc">+</span> beepollen<span class="sc">$</span>duration)</span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">dnorm</span>(beepollen<span class="sc">$</span>removed, <span class="at">mean =</span> mu, <span class="at">sd =</span> <span class="fu">exp</span>(parms[<span class="st">"logsigma"</span>]), <span class="at">log =</span> <span class="cn">TRUE</span>))</span>
<span id="cb110-5"><a href="#cb110-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb110-6"><a href="#cb110-6" aria-hidden="true" tabindex="-1"></a>op6q <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="at">a0 =</span> <span class="fl">0.9</span>, <span class="at">a1 =</span> <span class="dv">0</span>, <span class="at">b =</span> <span class="dv">15</span>, <span class="at">logsigma =</span> <span class="sc">-</span><span class="dv">2</span>), <span class="at">fn =</span> llmm2,</span>
<span id="cb110-7"><a href="#cb110-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">control =</span> <span class="fu">list</span>(<span class="at">fnscale =</span> <span class="sc">-</span><span class="dv">1</span>), <span class="at">method =</span> <span class="st">"BFGS"</span>, <span class="at">hessian =</span> <span class="cn">TRUE</span>)</span>
<span id="cb110-8"><a href="#cb110-8" aria-hidden="true" tabindex="-1"></a>se6q <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">solve</span>(<span class="sc">-</span>op6q<span class="sc">$</span>hessian)))</span>
<span id="cb110-9"><a href="#cb110-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">estimate =</span> op6q<span class="sc">$</span>par, <span class="at">SE =</span> se6q, <span class="at">t =</span> op6q<span class="sc">$</span>par <span class="sc">/</span> se6q)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           estimate         SE          t
a0        0.9293735 0.07776850  11.950513
a1       -0.1978194 0.06544264  -3.022791
b         9.4710946 2.87885538   3.289882
logsigma -2.0566947 0.10314211 -19.940399</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">AIC_common_a =</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> op6<span class="sc">$</span>value <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> <span class="dv">3</span>,</span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">AIC_separate_a =</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> op6q<span class="sc">$</span>value <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  AIC_common_a AIC_separate_a 
     -47.22096      -51.94913 </code></pre>
</div>
</div>
<p><span class="math inline">\(a_1\)</span> is the difference between the asymptote of queens and that of workers. It is <em>negative</em>: <span class="math inline">\(\hat a_1 =\)</span> -0.2 (SE 0.07, <span class="math inline">\(t \approx -3\)</span>). Queens do <strong>not</strong> remove more pollen in the limit — they remove about 20 percentage points <em>less</em> than workers (asymptotes of about 0.73 versus 0.93). The AIC drops by almost 5 units when the extra parameter is added, so the difference is supported by the data.</p>
</section>
</section>
<section id="exercise-7" class="level1">
<h1>Exercise 7</h1>
<p>The same model can often be fitted in several ways, and they do not give the same answer. <code>Decay</code> contains the amount of a substance (<code>amount</code>) that remains after <code>time</code> units, a textbook case of exponential decay <span class="math inline">\(y = y_0 e^{-kt}\)</span>.</p>
<ol type="a">
<li>Plot the data on the normal scale and with a logarithmic y-axis. Which plot shows a straight line, and why?</li>
<li>Route 1: fit <code>lm(log(amount) ~ time)</code>. Route 2: fit <code>glm(amount ~ time, family = gaussian(link = "log"))</code>. Route 3: maximise the log-likelihood of <span class="math inline">\(\mathrm{amount} \sim N(\mu = e^{\beta_0 + \beta_1 t}, \sigma)\)</span> with <code>optim()</code>. Collect the estimates of <span class="math inline">\(\beta_0\)</span> (i.e.&nbsp;<span class="math inline">\(\ln y_0\)</span>) and <span class="math inline">\(\beta_1\)</span> (i.e.&nbsp;<span class="math inline">\(-k\)</span>) from the three routes in one table.</li>
<li>Two of the three routes agree to several decimals. Which two, and why must they agree?</li>
<li>Route 1 gives a different slope. Write down what each route assumes about the <em>noise</em>: is the scatter added on the log scale or on the original scale, and does it grow with the fitted value or not? Look at the plot from (a) to decide which assumption fits these data better.</li>
<li>Draw the three fitted curves on the plot of <code>amount</code> against <code>time</code>. Where do they differ most? Calculate the half-life <span class="math inline">\(t_{1/2} = \ln 2 / k\)</span> from each route.</li>
<li>For Route 1, <code>exp(fitted values)</code> gives predictions on the original scale. Explain why these predictions are systematically <em>lower</em> than the mean of the data at a given time (hint: what is the mean of a log-normal distribution?).</li>
</ol>
<section id="answer-6" class="level2">
<h2 class="anchored" data-anchor-id="answer-6">Answer</h2>
<p><strong>a.</strong> Two plots:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(amount <span class="sc">~</span> time, <span class="at">data =</span> Decay, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">las =</span> <span class="dv">1</span>)</span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(amount <span class="sc">~</span> time, <span class="at">data =</span> Decay, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">log =</span> <span class="st">"y"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex7-plots-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Exponential decay on the original scale (left) and with a logarithmic y-axis (right).</figcaption>
</figure>
</div>
</div>
</div>
<p>With a logarithmic y-axis the points follow a straight line, because <span class="math inline">\(\ln y = \ln y_0 - k t\)</span>: the exponential becomes linear on the log scale. Note also that the vertical scatter around the line looks roughly constant on the log axis, but <em>shrinks</em> with time on the original axis.</p>
<p><strong>b.</strong> Three routes to the same model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Route 1: linear model on the log-transformed response</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>r1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(amount) <span class="sc">~</span> time, <span class="at">data =</span> Decay)</span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Route 2: gaussian GLM with a log link</span></span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>r2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(amount <span class="sc">~</span> time, <span class="at">data =</span> Decay, <span class="at">family =</span> <span class="fu">gaussian</span>(<span class="at">link =</span> <span class="st">"log"</span>))</span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-7"><a href="#cb115-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Route 3: by hand</span></span>
<span id="cb115-8"><a href="#cb115-8" aria-hidden="true" tabindex="-1"></a>lldecay <span class="ot">&lt;-</span> <span class="cf">function</span>(parms) {</span>
<span id="cb115-9"><a href="#cb115-9" aria-hidden="true" tabindex="-1"></a>  mu <span class="ot">&lt;-</span> <span class="fu">exp</span>(parms[<span class="dv">1</span>] <span class="sc">+</span> parms[<span class="dv">2</span>] <span class="sc">*</span> Decay<span class="sc">$</span>time)</span>
<span id="cb115-10"><a href="#cb115-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">dnorm</span>(Decay<span class="sc">$</span>amount, <span class="at">mean =</span> mu, <span class="at">sd =</span> <span class="fu">exp</span>(parms[<span class="dv">3</span>]), <span class="at">log =</span> <span class="cn">TRUE</span>))</span>
<span id="cb115-11"><a href="#cb115-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb115-12"><a href="#cb115-12" aria-hidden="true" tabindex="-1"></a>r3 <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="fl">4.5</span>, <span class="sc">-</span><span class="fl">0.07</span>, <span class="dv">2</span>), <span class="at">fn =</span> lldecay, <span class="at">control =</span> <span class="fu">list</span>(<span class="at">fnscale =</span> <span class="sc">-</span><span class="dv">1</span>),</span>
<span id="cb115-13"><a href="#cb115-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">method =</span> <span class="st">"BFGS"</span>, <span class="at">hessian =</span> <span class="cn">TRUE</span>)</span>
<span id="cb115-14"><a href="#cb115-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-15"><a href="#cb115-15" aria-hidden="true" tabindex="-1"></a>estimates <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="at">lm_log =</span> <span class="fu">coef</span>(r1), <span class="at">glm_loglink =</span> <span class="fu">coef</span>(r2), <span class="at">optim =</span> r3<span class="sc">$</span>par[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span>
<span id="cb115-16"><a href="#cb115-16" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(estimates) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"beta0 = ln(y0)"</span>, <span class="st">"beta1 = -k"</span>)</span>
<span id="cb115-17"><a href="#cb115-17" aria-hidden="true" tabindex="-1"></a>estimates</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            beta0 = ln(y0)  beta1 = -k
lm_log            4.547386 -0.06852845
glm_loglink       4.683386 -0.08018599
optim             4.683463 -0.08019277</code></pre>
</div>
</div>
<p><strong>c.</strong> Routes 2 and 3 agree to four decimals. They <em>must</em> agree: they fit exactly the same model — a normal distribution with a mean <span class="math inline">\(e^{\beta_0 + \beta_1 t}\)</span> and constant standard deviation — by maximum likelihood, only with different optimisation algorithms. Route 1 fits a different model.</p>
<p><strong>d.</strong> The three routes assume:</p>
<ul>
<li><strong>Route 1</strong> (<code>lm</code> on <span class="math inline">\(\ln y\)</span>): <span class="math inline">\(\ln y \sim N(\beta_0 + \beta_1 t, \sigma)\)</span>. The noise is normal <em>on the log scale</em> with constant <span class="math inline">\(\sigma\)</span>. On the original scale this means the noise is <strong>multiplicative</strong>: <span class="math inline">\(y = y_0 e^{-kt} \cdot e^{\varepsilon}\)</span>, and its absolute size shrinks as the fitted value shrinks.</li>
<li><strong>Routes 2 and 3</strong>: <span class="math inline">\(y \sim N(e^{\beta_0 + \beta_1 t}, \sigma)\)</span>. The noise is normal and <strong>additive on the original scale</strong>, with the same <span class="math inline">\(\sigma\)</span> whether the fitted value is 120 or 10.</li>
</ul>
<p>In the left-hand plot of (a) the scatter is clearly larger at the start (amounts around 100 vary by ±20) than at the end (amounts around 10 vary by ±3), while on the log axis it looks about constant. The multiplicative assumption of Route 1 fits these data better. Route 1 also gives less weight to the large early values, which is why its slope is less steep.</p>
<p><strong>e.</strong> The fitted curves and half-lives:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>tnew <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">30</span>, <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(amount <span class="sc">~</span> time, <span class="at">data =</span> Decay, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">las =</span> <span class="dv">1</span>)</span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(tnew, <span class="fu">exp</span>(<span class="fu">coef</span>(r1)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(r1)[<span class="dv">2</span>] <span class="sc">*</span> tnew), <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb117-4"><a href="#cb117-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(tnew, <span class="fu">exp</span>(<span class="fu">coef</span>(r2)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(r2)[<span class="dv">2</span>] <span class="sc">*</span> tnew), <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb117-5"><a href="#cb117-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(tnew, <span class="fu">exp</span>(r3<span class="sc">$</span>par[<span class="dv">1</span>] <span class="sc">+</span> r3<span class="sc">$</span>par[<span class="dv">2</span>] <span class="sc">*</span> tnew), <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb117-6"><a href="#cb117-6" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="fu">c</span>(<span class="st">"lm on log(amount)"</span>, <span class="st">"glm, log link"</span>, <span class="st">"optim"</span>),</span>
<span id="cb117-7"><a href="#cb117-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">3</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"black"</span>, <span class="st">"red"</span>), <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">bty =</span> <span class="st">"n"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex7-curves-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>The three fits: lm on log(amount) (dashed), gaussian GLM with log link (solid) and optim (dotted, on top of the solid line).</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="sc">-</span>estimates[, <span class="dv">2</span>]</span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">k =</span> k, <span class="at">half_life =</span> <span class="fu">log</span>(<span class="dv">2</span>) <span class="sc">/</span> k)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     k half_life
lm_log      0.06852845 10.114736
glm_loglink 0.08018599  8.644243
optim       0.08019277  8.643512</code></pre>
</div>
</div>
<p>The GLM/optim curve and the log-lm curve differ most at the start (where the GLM curve is higher, <span class="math inline">\(y_0 = e^{4.68} = 108\)</span> versus <span class="math inline">\(e^{4.55} = 94\)</span>) and at the end, where the log-lm curve is higher because it decays more slowly. The half-lives are 8.6 (GLM, optim) versus 10.1 time units (log-lm): a difference of more than 15 %, purely from the assumption about the noise.</p>
<p><strong>f.</strong> Route 1 models <span class="math inline">\(\ln y\)</span> as normal, so <span class="math inline">\(y\)</span> itself is <strong>log-normal</strong>. The fitted line on the log scale is the <em>mean</em> of <span class="math inline">\(\ln y\)</span>, which back-transforms to the <em>median</em> of <span class="math inline">\(y\)</span>, not its mean. The mean of a log-normal distribution is <span class="math inline">\(e^{\mu + \sigma^2/2}\)</span> (Dormann, Sect. 3.4), which is always larger than <span class="math inline">\(e^{\mu}\)</span>. So <code>exp(fitted(r1))</code> under-estimates the mean amount by a factor <span class="math inline">\(e^{\sigma^2/2}\)</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>sigma1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(r1)<span class="sc">$</span>sigma</span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">sigma =</span> sigma1, <span class="at">correction_factor =</span> <span class="fu">exp</span>(sigma1<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            sigma correction_factor 
        0.2859929         1.0417437 </code></pre>
</div>
</div>
<p>Here the bias is small (about 2 %) because <span class="math inline">\(\sigma\)</span> on the log scale is small, but with noisier data it can be substantial. This is a general lesson: back-transformed predictions from a model of <span class="math inline">\(\ln y\)</span> are medians.</p>
</section>
</section>
<section id="exercise-8" class="level1">
<h1>Exercise 8</h1>
<p>In the last exercise we model a distribution parameter other than the mean (Dormann, Sect. 8.4). Black bears in Minnesota were weighed at known ages (<code>beargrowth</code>). Restrict the data to young bears, <code>bears &lt;- subset(beargrowth, age &lt;= 6)</code>, for which weight still increases roughly linearly with age.</p>
<ol type="a">
<li>Plot <code>wtkg</code> against <code>age</code> and calculate the standard deviation of weight for each age with <code>tapply()</code>. What happens to the spread as the bears get older? Why does this violate the assumption of <code>glm(wtkg ~ age, family = gaussian)</code>?</li>
<li>Fit that gaussian GLM anyway and note the coefficients, the dispersion parameter and the AIC.</li>
<li>Write a likelihood function for the model <span class="math inline">\(\mathrm{wtkg} \sim N\!\big(\mu = a + b\,\mathrm{age},\ \sigma = e^{c + d\,\mathrm{age}}\big)\)</span> with four parameters. Explain the role of the exponential. Test it with <code>c(20, 10, 2, 0)</code>. What does <span class="math inline">\(d = 0\)</span> correspond to?</li>
<li>Maximise it with <code>optim()</code> (use <code>method = "BFGS"</code>, <code>hessian = TRUE</code>; if it fails, change the starting values). Report the four estimates with their standard errors. Is <span class="math inline">\(d\)</span> significantly different from 0?</li>
<li>Calculate the AIC of the four-parameter model by hand and compare it with the AIC of the model in (b). Are the estimates of <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> very different between the two models? Which part of the output <em>does</em> change a lot, and why does that matter for a confidence band?</li>
<li>Use the fitted values of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> to draw, on the plot from (a), the fitted mean line and the lines <span class="math inline">\(\mu \pm 2\sigma\)</span> as a function of age. Roughly what fraction of the bears should fall between the outer lines? Check it with the data.</li>
</ol>
<section id="answer-7" class="level2">
<h2 class="anchored" data-anchor-id="answer-7">Answer</h2>
<p><strong>a.</strong> The data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>bears <span class="ot">&lt;-</span> <span class="fu">subset</span>(beargrowth, age <span class="sc">&lt;=</span> <span class="dv">6</span>)</span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wtkg <span class="sc">~</span> <span class="fu">jitter</span>(age, <span class="fl">0.3</span>), <span class="at">data =</span> bears, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">adjustcolor</span>(<span class="st">"black"</span>, <span class="fl">0.4</span>), <span class="at">xlab =</span> <span class="st">"age (years)"</span>, <span class="at">ylab =</span> <span class="st">"weight (kg)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex8-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Weight of young black bears against age.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">n =</span> <span class="fu">table</span>(bears<span class="sc">$</span>age),</span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">mean =</span> <span class="fu">round</span>(<span class="fu">tapply</span>(bears<span class="sc">$</span>wtkg, bears<span class="sc">$</span>age, mean), <span class="dv">1</span>),</span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">sd =</span> <span class="fu">round</span>(<span class="fu">tapply</span>(bears<span class="sc">$</span>wtkg, bears<span class="sc">$</span>age, sd), <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1    2    3    4    5    6
n    290.0 80.0 58.0 55.0 53.0 48.0
mean  20.1 37.4 57.4 71.7 76.5 87.1
sd     6.3  9.6 12.6 19.8 24.1 31.9</code></pre>
</div>
</div>
<p>The standard deviation grows from 6 kg at age 1 to 32 kg at age 6 — a five-fold increase, roughly in proportion to the mean. A gaussian GLM assumes one <span class="math inline">\(\sigma\)</span> for all ages (<strong>homoscedasticity</strong>), so it will overestimate the spread of yearlings and underestimate that of six-year-olds.</p>
<p><strong>b.</strong> The ordinary gaussian GLM:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>fm8 <span class="ot">&lt;-</span> <span class="fu">glm</span>(wtkg <span class="sc">~</span> age, <span class="at">data =</span> bears, <span class="at">family =</span> gaussian)</span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fm8)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age 
   7.362429   14.347215 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">dispersion =</span> <span class="fu">summary</span>(fm8)<span class="sc">$</span>dispersion, <span class="at">sigma =</span> <span class="fu">sqrt</span>(<span class="fu">summary</span>(fm8)<span class="sc">$</span>dispersion), <span class="at">AIC =</span> <span class="fu">AIC</span>(fm8))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>dispersion      sigma        AIC 
 232.91593   15.26158 4844.51248 </code></pre>
</div>
</div>
<p><strong>c.</strong> The likelihood function with a variable standard deviation:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>llbear <span class="ot">&lt;-</span> <span class="cf">function</span>(parms) {</span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>  mu <span class="ot">&lt;-</span> parms[<span class="dv">1</span>] <span class="sc">+</span> parms[<span class="dv">2</span>] <span class="sc">*</span> bears<span class="sc">$</span>age</span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a>  sigma <span class="ot">&lt;-</span> <span class="fu">exp</span>(parms[<span class="dv">3</span>] <span class="sc">+</span> parms[<span class="dv">4</span>] <span class="sc">*</span> bears<span class="sc">$</span>age)</span>
<span id="cb129-4"><a href="#cb129-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">dnorm</span>(bears<span class="sc">$</span>wtkg, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma, <span class="at">log =</span> <span class="cn">TRUE</span>))</span>
<span id="cb129-5"><a href="#cb129-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb129-6"><a href="#cb129-6" aria-hidden="true" tabindex="-1"></a><span class="fu">llbear</span>(<span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">10</span>, <span class="dv">2</span>, <span class="dv">0</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -3271.096</code></pre>
</div>
</div>
<p>The exponential guarantees that <span class="math inline">\(\sigma\)</span> is positive for any values of <span class="math inline">\(c\)</span> and <span class="math inline">\(d\)</span> — it plays the role of a log link for the standard deviation. With <span class="math inline">\(d = 0\)</span> the standard deviation is <span class="math inline">\(e^{c}\)</span> for every age, i.e.&nbsp;the model reduces to the ordinary gaussian regression of (b).</p>
<p><strong>d.</strong> Optimisation:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>op8 <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">10</span>, <span class="dv">2</span>, <span class="dv">0</span>), <span class="at">fn =</span> llbear, <span class="at">control =</span> <span class="fu">list</span>(<span class="at">fnscale =</span> <span class="sc">-</span><span class="dv">1</span>),</span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">method =</span> <span class="st">"BFGS"</span>, <span class="at">hessian =</span> <span class="cn">TRUE</span>)</span>
<span id="cb131-3"><a href="#cb131-3" aria-hidden="true" tabindex="-1"></a>op8<span class="sc">$</span>convergence</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>se8 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">solve</span>(<span class="sc">-</span>op8<span class="sc">$</span>hessian)))</span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>res8 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="at">estimate =</span> op8<span class="sc">$</span>par, <span class="at">SE =</span> se8, <span class="at">t =</span> op8<span class="sc">$</span>par <span class="sc">/</span> se8)</span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(res8) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"a (intercept mu)"</span>, <span class="st">"b (slope mu)"</span>, <span class="st">"c (intercept log sigma)"</span>, <span class="st">"d (slope log sigma)"</span>)</span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a>res8</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          estimate         SE         t
a (intercept mu)         4.1302788 0.67844301  6.087879
b (slope mu)            16.2344705 0.45015763 36.063969
c (intercept log sigma)  1.5062723 0.05180466 29.076003
d (slope log sigma)      0.3513732 0.01787106 19.661576</code></pre>
</div>
</div>
<p><span class="math inline">\(d =\)</span> 0.351 with SE 0.018, <span class="math inline">\(t \approx 20\)</span>: the standard deviation increases very significantly with age, by a factor <span class="math inline">\(e^{d} =\)</span> 1.42 per year. The fitted standard deviation is <span class="math inline">\(e^{c + d \cdot \mathrm{age}}\)</span>: about 6.4 kg at age 1 and 37.1 kg at age 6, close to the empirical values in (a).</p>
<p><strong>e.</strong> Comparison:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">AIC_constant_sigma =</span> <span class="fu">AIC</span>(fm8),</span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">AIC_variable_sigma =</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> op8<span class="sc">$</span>value <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>AIC_constant_sigma AIC_variable_sigma 
          4844.512           4406.390 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">glm =</span> <span class="fu">coef</span>(fm8), <span class="at">optim =</span> op8<span class="sc">$</span>par[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept)      age
glm      7.362429 14.34722
optim    4.130279 16.23447</code></pre>
</div>
</div>
<p>The AIC drops by more than 400 units: the model with a variable standard deviation is overwhelmingly better. The estimates of the mean line are similar but not identical: the four-parameter model gives the precise yearlings more weight and the noisy six-year-olds less, which shifts the intercept and slope a little. What changes dramatically is the description of the <strong>spread</strong>: one <span class="math inline">\(\sigma\)</span> of 15.3 kg versus a <span class="math inline">\(\sigma\)</span> that runs from about 6 kg at age 1 to 37 kg at age 6. A confidence or prediction band based on the constant-<span class="math inline">\(\sigma\)</span> model would be far too wide for young bears and too narrow for older ones.</p>
<p><strong>f.</strong> The fitted mean and the <span class="math inline">\(\pm 2\sigma\)</span> envelope:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wtkg <span class="sc">~</span> <span class="fu">jitter</span>(age, <span class="fl">0.3</span>), <span class="at">data =</span> bears, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb139-2"><a href="#cb139-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">adjustcolor</span>(<span class="st">"black"</span>, <span class="fl">0.4</span>), <span class="at">xlab =</span> <span class="st">"age (years)"</span>, <span class="at">ylab =</span> <span class="st">"weight (kg)"</span>)</span>
<span id="cb139-3"><a href="#cb139-3" aria-hidden="true" tabindex="-1"></a>agenew <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">6</span>, <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb139-4"><a href="#cb139-4" aria-hidden="true" tabindex="-1"></a>mu_new <span class="ot">&lt;-</span> op8<span class="sc">$</span>par[<span class="dv">1</span>] <span class="sc">+</span> op8<span class="sc">$</span>par[<span class="dv">2</span>] <span class="sc">*</span> agenew</span>
<span id="cb139-5"><a href="#cb139-5" aria-hidden="true" tabindex="-1"></a>sigma_new <span class="ot">&lt;-</span> <span class="fu">exp</span>(op8<span class="sc">$</span>par[<span class="dv">3</span>] <span class="sc">+</span> op8<span class="sc">$</span>par[<span class="dv">4</span>] <span class="sc">*</span> agenew)</span>
<span id="cb139-6"><a href="#cb139-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(agenew, mu_new, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb139-7"><a href="#cb139-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(agenew, mu_new <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> sigma_new, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb139-8"><a href="#cb139-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(agenew, mu_new <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> sigma_new, <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_3_regression_answers_files/figure-html/ex8-envelope-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Fitted mean (solid) and mean ± 2 fitted standard deviations (dashed) from the model with age-dependent standard deviation.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a>mu_i <span class="ot">&lt;-</span> op8<span class="sc">$</span>par[<span class="dv">1</span>] <span class="sc">+</span> op8<span class="sc">$</span>par[<span class="dv">2</span>] <span class="sc">*</span> bears<span class="sc">$</span>age</span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a>sigma_i <span class="ot">&lt;-</span> <span class="fu">exp</span>(op8<span class="sc">$</span>par[<span class="dv">3</span>] <span class="sc">+</span> op8<span class="sc">$</span>par[<span class="dv">4</span>] <span class="sc">*</span> bears<span class="sc">$</span>age)</span>
<span id="cb140-3"><a href="#cb140-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">abs</span>(bears<span class="sc">$</span>wtkg <span class="sc">-</span> mu_i) <span class="sc">&lt;</span> <span class="dv">2</span> <span class="sc">*</span> sigma_i)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9606164</code></pre>
</div>
</div>
<p>For a normal distribution about 95 % of the observations lie within <span class="math inline">\(\mu \pm 2\sigma\)</span>. In the data 96.1 % of the bears fall between the dashed lines, close to the expectation. Note that the envelope is narrow at age 1 and widens steadily — this is a <strong>prediction interval</strong> for individual bears, and it is only realistic because we modelled <span class="math inline">\(\sigma\)</span> as a function of age. This is the message of Dormann, Sect. 8.4: with maximum likelihood we can let <em>any</em> parameter of the distribution depend on the predictor, not only the mean.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>