<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>QSBS Practical 5 — Multiple regression Answers</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="QSBS_5_multiple_regression_answers_files/libs/clipboard/clipboard.min.js"></script>
<script src="QSBS_5_multiple_regression_answers_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="QSBS_5_multiple_regression_answers_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="QSBS_5_multiple_regression_answers_files/libs/quarto-html/popper.min.js"></script>
<script src="QSBS_5_multiple_regression_answers_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="QSBS_5_multiple_regression_answers_files/libs/quarto-html/anchor.min.js"></script>
<link href="QSBS_5_multiple_regression_answers_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="QSBS_5_multiple_regression_answers_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="QSBS_5_multiple_regression_answers_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="QSBS_5_multiple_regression_answers_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="QSBS_5_multiple_regression_answers_files/libs/bootstrap/bootstrap-94053d6e10daeb31c4957f2bd90b11ca.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#exercise-1-two-categorical-predictors" id="toc-exercise-1-two-categorical-predictors" class="nav-link" data-scroll-target="#exercise-1-two-categorical-predictors">Exercise 1 — Two categorical predictors</a>
  <ul class="collapse">
  <li><a href="#answer" id="toc-answer" class="nav-link" data-scroll-target="#answer">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-2-a-continuous-and-a-categorical-predictor-ancova" id="toc-exercise-2-a-continuous-and-a-categorical-predictor-ancova" class="nav-link" data-scroll-target="#exercise-2-a-continuous-and-a-categorical-predictor-ancova">Exercise 2 — A continuous and a categorical predictor (ANCOVA)</a>
  <ul class="collapse">
  <li><a href="#answer-1" id="toc-answer-1" class="nav-link" data-scroll-target="#answer-1">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-3-interaction-between-a-continuous-and-a-categorical-predictor" id="toc-exercise-3-interaction-between-a-continuous-and-a-categorical-predictor" class="nav-link" data-scroll-target="#exercise-3-interaction-between-a-continuous-and-a-categorical-predictor">Exercise 3 — Interaction between a continuous and a categorical predictor</a>
  <ul class="collapse">
  <li><a href="#answer-2" id="toc-answer-2" class="nav-link" data-scroll-target="#answer-2">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-4-interaction-and-model-simplification-with-a-negative-binomial-glm" id="toc-exercise-4-interaction-and-model-simplification-with-a-negative-binomial-glm" class="nav-link" data-scroll-target="#exercise-4-interaction-and-model-simplification-with-a-negative-binomial-glm">Exercise 4 — Interaction and model simplification with a negative binomial GLM</a>
  <ul class="collapse">
  <li><a href="#answer-3" id="toc-answer-3" class="nav-link" data-scroll-target="#answer-3">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-5-collinearity" id="toc-exercise-5-collinearity" class="nav-link" data-scroll-target="#exercise-5-collinearity">Exercise 5 — Collinearity</a>
  <ul class="collapse">
  <li><a href="#answer-4" id="toc-answer-4" class="nav-link" data-scroll-target="#answer-4">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-6-two-continuous-predictors-and-their-interaction" id="toc-exercise-6-two-continuous-predictors-and-their-interaction" class="nav-link" data-scroll-target="#exercise-6-two-continuous-predictors-and-their-interaction">Exercise 6 — Two continuous predictors and their interaction</a>
  <ul class="collapse">
  <li><a href="#answer-5" id="toc-answer-5" class="nav-link" data-scroll-target="#answer-5">Answer</a></li>
  </ul></li>
  <li><a href="#exercise-7-model-selection" id="toc-exercise-7-model-selection" class="nav-link" data-scroll-target="#exercise-7-model-selection">Exercise 7 — Model selection</a>
  <ul class="collapse">
  <li><a href="#answer-6" id="toc-answer-6" class="nav-link" data-scroll-target="#answer-6">Answer</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">QSBS Practical 5 — Multiple regression Answers</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This document gives model answers to the interpretation questions of Practical 5. The R code that produced the output is the same as in the exercise document; it is folded away here (click “Code” to see it). Where useful, the relevant output is repeated next to the answer.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(qsbsdata)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MuMIn)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="exercise-1-two-categorical-predictors" class="level1">
<h1>Exercise 1 — Two categorical predictors</h1>
<p>Asghar et al.&nbsp;(2015, <em>Science</em>) measured the telomere length of great reed warbler chicks at 9 days of age (<code>OffBTL</code>, in <code>birdmalariaO</code>) and asked whether it depends on the malaria infection status of the mother (<code>mmal</code>: healthy or infected) and on the sex of the chick.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>bird <span class="ot">&lt;-</span> birdmalariaO</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>bird<span class="sc">$</span>Sex  <span class="ot">&lt;-</span> <span class="fu">factor</span>(bird<span class="sc">$</span>Sex,  <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"male"</span>, <span class="st">"female"</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>bird<span class="sc">$</span>mmal <span class="ot">&lt;-</span> <span class="fu">factor</span>(bird<span class="sc">$</span>mmal, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"healthy"</span>, <span class="st">"infected"</span>))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>bird <span class="ot">&lt;-</span> bird[<span class="fu">complete.cases</span>(bird[, <span class="fu">c</span>(<span class="st">"OffBTL"</span>, <span class="st">"Sex"</span>, <span class="st">"mmal"</span>)]), ]</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>fb_add <span class="ot">&lt;-</span> <span class="fu">glm</span>(OffBTL <span class="sc">~</span> Sex <span class="sc">+</span> mmal, <span class="at">family =</span> gaussian, <span class="at">data =</span> bird)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>fb_int <span class="ot">&lt;-</span> <span class="fu">glm</span>(OffBTL <span class="sc">~</span> Sex <span class="sc">*</span> mmal, <span class="at">family =</span> gaussian, <span class="at">data =</span> bird)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">tapply</span>(bird<span class="sc">$</span>OffBTL, <span class="fu">list</span>(bird<span class="sc">$</span>Sex, bird<span class="sc">$</span>mmal), mean), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       healthy infected
male     0.973    0.806
female   1.009    0.823</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fb_int)<span class="sc">$</span>coefficients, <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                       Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)              0.9733     0.0456 21.3622   0.0000
Sexfemale                0.0354     0.0709  0.4990   0.6184
mmalinfected            -0.1671     0.0686 -2.4357   0.0159
Sexfemale:mmalinfected  -0.0185     0.1042 -0.1772   0.8596</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fb_int, <span class="at">test =</span> <span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: gaussian, link: identity

Response: OffBTL

Terms added sequentially (first to last)

         Df Deviance Resid. Df Resid. Dev       F    Pr(&gt;F)    
NULL                       178     22.086                      
Sex       1  0.01747       177     22.068  0.1477 0.7012309    
mmal      1  1.35984       176     20.709 11.4936 0.0008631 ***
Sex:mmal  1  0.00372       175     20.705  0.0314 0.8595539    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fb_add)<span class="sc">$</span>coefficients, <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)    0.9768     0.0409 23.9043   0.0000
Sexfemale      0.0268     0.0518  0.5180   0.6051
mmalinfected  -0.1751     0.0515 -3.3996   0.0008</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(fb_add, fb_int)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       df      AIC
fb_add  4 129.9060
fb_int  5 131.8739</code></pre>
</div>
</div>
<ol type="a">
<li>Which of the four groups is the <em>reference group</em> that the intercept of the interaction model refers to, and why that one? Reconstruct from the four coefficients of <code>fb_int</code> the fitted mean telomere length of the four groups and compare with the table of group means.</li>
<li>What does the coefficient <code>Sexfemale:mmalinfected</code> measure, in words? Do sex and mother’s infection status interact?</li>
<li>Explain what the three rows of the <code>anova()</code> table test. Which term explains most of the deviance? What fraction of the total deviance is explained by the full interaction model?</li>
<li>Which of the two models would you report, and why? Give the interpretation of the <code>mmalinfected</code> coefficient of the model you chose.</li>
<li>Is it allowed to remove <code>Sex</code> from the additive model? From the interaction model? Explain the difference.</li>
</ol>
<section id="answer" class="level2">
<h2 class="anchored" data-anchor-id="answer">Answer</h2>
<p><strong>(a)</strong> The reference group is <em>male chicks of healthy mothers</em>: R takes the first level of each factor as the reference, and we defined the levels in the order <code>male, female</code> and <code>healthy, infected</code>. (Without the explicit <code>levels</code> argument R would have sorted them alphabetically, which here happens to give the same order.) All other coefficients are <em>differences</em> from this reference group.</p>
<p>The four fitted means follow by adding the coefficients that “switch on” for each group:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>group</th>
<th>coefficients added</th>
<th>fitted mean</th>
<th>observed mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>male, healthy</td>
<td>intercept</td>
<td>0.973</td>
<td>0.973</td>
</tr>
<tr class="even">
<td>female, healthy</td>
<td>intercept + <code>Sexfemale</code> = 0.973 + 0.035</td>
<td>1.009</td>
<td>1.009</td>
</tr>
<tr class="odd">
<td>male, infected</td>
<td>intercept + <code>mmalinfected</code> = 0.973 − 0.167</td>
<td>0.806</td>
<td>0.806</td>
</tr>
<tr class="even">
<td>female, infected</td>
<td>intercept + <code>Sexfemale</code> + <code>mmalinfected</code> + interaction = 0.973 + 0.035 − 0.167 − 0.018</td>
<td>0.823</td>
<td>0.823</td>
</tr>
</tbody>
</table>
<p>The interaction model has four parameters for four groups, so it reproduces the four group means exactly. That is what makes it the “saturated” model for the group means; the additive model with three parameters cannot do this.</p>
<p><strong>(b)</strong> <code>Sexfemale:mmalinfected</code> is the <em>extra</em> effect of an infected mother for female chicks, beyond the effect for males: it is the difference between the two slopes in the interaction plot, i.e.&nbsp;(female infected − female healthy) − (male infected − male healthy) = (0.823 − 1.009) − (0.806 − 0.973) = −0.186 − (−0.167) = −0.018. The estimate is tiny compared with its standard error (0.104), <span class="math inline">\(p = 0.86\)</span>, and in the interaction plot the two lines are practically parallel. There is no interaction: the mother’s infection reduces telomere length by about the same amount in sons and daughters.</p>
<p><strong>(c)</strong> The table adds the terms one at a time, in the order of the formula:</p>
<ul>
<li><code>Sex</code>: does chick sex explain any deviance, on its own? Deviance 0.017, <span class="math inline">\(F = 0.15\)</span>, <span class="math inline">\(p = 0.70\)</span> — no.</li>
<li><code>mmal</code>: does the mother’s infection status explain additional deviance <em>after</em> sex has been accounted for? Deviance 1.36, <span class="math inline">\(F = 11.5\)</span>, <span class="math inline">\(p &lt; 0.001\)</span> — yes, by far the largest term.</li>
<li><code>Sex:mmal</code>: does allowing the infection effect to differ between the sexes explain further deviance, after both main effects? Deviance 0.004, <span class="math inline">\(p = 0.86\)</span> — no.</li>
</ul>
<p>The full model explains <span class="math inline">\((22.086 - 20.705)/22.086 = 0.063\)</span>, i.e.&nbsp;about 6 % of the total deviance. Almost all of that (1.36 of 1.38) is due to the mother’s infection status. The effect is highly significant but explains little of the variation between chicks: telomere length is variable for many other reasons (brood, year, parents), which is typical of field data.</p>
<p><strong>(d)</strong> The additive model. Both criteria agree: the AIC of the additive model is lower (129.9 vs 131.9, a difference of 2 units, which is exactly what one expects when a useless parameter is dropped), and the F-test of the interaction term gives <span class="math inline">\(p = 0.86\)</span>. There is no reason to keep a term that does not improve the fit and makes the model harder to read.</p>
<p>In the additive model <code>mmalinfected</code> <span class="math inline">\(= -0.175 \pm 0.052\)</span> (<span class="math inline">\(p &lt; 0.001\)</span>). Interpretation: chicks of malaria-infected mothers have, at 9 days of age, telomeres that are on average 0.18 units shorter (roughly 18 % of the value for chicks of healthy mothers, 0.98), irrespective of the chick’s sex; the 95 % confidence interval for the difference is about −0.28 to −0.07.</p>
<p><strong>(e)</strong> From the <em>additive</em> model, yes: <code>Sex</code> is a main effect that is part of no interaction, its coefficient is small and not significant (<span class="math inline">\(p = 0.61\)</span>), so it can be dropped (the AIC would decrease by almost 2). Whether one <em>wants</em> to drop it is a different matter: if the sex of the chick was part of the design or the hypothesis, one may keep it and report that it has no effect.</p>
<p>From the <em>interaction</em> model, no. The interaction <code>Sex:mmal</code> contains <code>Sex</code>; removing the main effect while keeping the interaction violates the marginality principle (Nelder 1977; Dormann Sect. 15.4). The resulting model would be one in which the sexes have the same mean for healthy mothers by <em>assumption</em> but may differ for infected mothers — a strange, non-hierarchical model whose coefficients depend on the arbitrary choice of reference level. The correct order is: first test the interaction; if it can go, then look at the main effects.</p>
</section>
</section>
<section id="exercise-2-a-continuous-and-a-categorical-predictor-ancova" class="level1">
<h1>Exercise 2 — A continuous and a categorical predictor (ANCOVA)</h1>
<p><code>regrowth</code>: fruit production (<code>Fruit</code>, mg) of 40 plants, initial root diameter (<code>Root</code>, mm) and grazing treatment (<code>Grazing</code>).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>fg_add <span class="ot">&lt;-</span> <span class="fu">glm</span>(Fruit <span class="sc">~</span> Root <span class="sc">+</span> Grazing, <span class="at">family =</span> gaussian, <span class="at">data =</span> regrowth)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>fg_int <span class="ot">&lt;-</span> <span class="fu">glm</span>(Fruit <span class="sc">~</span> Root <span class="sc">*</span> Grazing, <span class="at">family =</span> gaussian, <span class="at">data =</span> regrowth)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(regrowth<span class="sc">$</span>Fruit, regrowth<span class="sc">$</span>Grazing, mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Grazed Ungrazed 
 67.9405  50.8805 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(regrowth<span class="sc">$</span>Root, regrowth<span class="sc">$</span>Grazing, mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Grazed Ungrazed 
  8.3094   6.0529 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fg_add)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)     -127.829      9.664 -13.227        0
Root              23.560      1.149  20.509        0
GrazingUngrazed   36.103      3.357  10.753        0</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">glm</span>(Fruit <span class="sc">~</span> Grazing <span class="sc">+</span> Root, <span class="at">family =</span> gaussian, <span class="at">data =</span> regrowth), <span class="at">test =</span> <span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: gaussian, link: identity

Response: Fruit

Terms added sequentially (first to last)

        Df Deviance Resid. Df Resid. Dev       F    Pr(&gt;F)    
NULL                       39    23743.8                      
Grazing  1   2910.4        38    20833.4  63.929 1.397e-09 ***
Root     1  19148.9        37     1684.5 420.616 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fg_add, <span class="at">test =</span> <span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: gaussian, link: identity

Response: Fruit

Terms added sequentially (first to last)

        Df Deviance Resid. Df Resid. Dev      F    Pr(&gt;F)    
NULL                       39    23743.8                     
Root     1  16795.0        38     6948.8 368.91 &lt; 2.2e-16 ***
Grazing  1   5264.4        37     1684.5 115.63 6.107e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fg_int)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                     Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)          -125.173     12.811  -9.771    0.000
Root                   23.240      1.531  15.182    0.000
GrazingUngrazed        30.806     16.842   1.829    0.076
Root:GrazingUngrazed    0.756      2.354   0.321    0.750</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fg_add, fg_int, <span class="at">test =</span> <span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: Fruit ~ Root + Grazing
Model 2: Fruit ~ Root * Grazing
  Resid. Df Resid. Dev Df Deviance      F Pr(&gt;F)
1        37     1684.5                          
2        36     1679.7  1   4.8122 0.1031   0.75</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Fruit <span class="sc">~</span> Root, <span class="at">data =</span> regrowth, <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">1</span>)[regrowth<span class="sc">$</span>Grazing], <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"initial root diameter (mm)"</span>, <span class="at">ylab =</span> <span class="st">"fruit production (mg)"</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>cf <span class="ot">&lt;-</span> <span class="fu">coef</span>(fg_add)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> cf[<span class="st">"(Intercept)"</span>], <span class="at">b =</span> cf[<span class="st">"Root"</span>], <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> cf[<span class="st">"(Intercept)"</span>] <span class="sc">+</span> cf[<span class="st">"GrazingUngrazed"</span>], <span class="at">b =</span> cf[<span class="st">"Root"</span>], <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">1</span>), <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Grazed"</span>, <span class="st">"Ungrazed"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_5_multiple_regression_answers_files/figure-html/ex2-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Fruit production against root diameter with the two parallel lines of the additive model.</figcaption>
</figure>
</div>
</div>
</div>
<ol type="a">
<li>Explain how the apparent contradiction between the boxplot and the model arises, and which statement answers “does grazing reduce fruit production?”.</li>
<li>Write down the two fitted regression lines. What does the model assume about them?</li>
<li>Why does the order of the terms matter in the <code>anova()</code> tables, and why does the residual deviance not depend on the order?</li>
<li>What does <code>Root:GrazingUngrazed</code> represent? Is there evidence that the effect of root size differs between the groups? Which model would you report?</li>
<li>Why is it important that root diameter was measured before the treatment?</li>
</ol>
<section id="answer-1" class="level2">
<h2 class="anchored" data-anchor-id="answer-1">Answer</h2>
<p><strong>(a)</strong> The two statements answer different questions. The boxplot compares the <em>raw</em> means of the two groups (68 vs 51 mg) and ignores everything else. But the grazed plants were, by chance, <em>larger</em> to begin with: their mean root diameter is 8.3 mm against 6.1 mm for the ungrazed plants, and fruit production increases steeply with root size (23.6 mg per mm). The grazed group therefore has a head start that has nothing to do with grazing. The additive model compares the two groups <em>at the same root diameter</em> — in the scatter plot, the open symbols lie consistently above the filled symbols for any given root size — and finds that an ungrazed plant produces 36 mg more fruit than a grazed plant of the same size.</p>
<p>The question “does grazing reduce fruit production?” is about the effect of grazing <em>with everything else equal</em>, so the model’s answer is the right one: grazing reduces fruit production by about 36 mg. The raw comparison is confounded by plant size; this is a textbook example of how a covariate can reverse the sign of a group difference (a form of Simpson’s paradox). It is also the reason why Dormann insists on plotting the data against <em>all</em> predictors before interpreting a group difference.</p>
<p><strong>(b)</strong> With the reference level <code>Grazed</code>:</p>
<ul>
<li>Grazed: <span class="math inline">\(\hat{y} = -127.8 + 23.56 \cdot \mathrm{Root}\)</span></li>
<li>Ungrazed: <span class="math inline">\(\hat{y} = (-127.8 + 36.1) + 23.56 \cdot \mathrm{Root} = -91.7 + 23.56 \cdot \mathrm{Root}\)</span></li>
</ul>
<p>The additive model assumes that the two lines are <strong>parallel</strong>: the same slope for both groups, and a constant vertical distance of 36.1 mg between them. Grazing shifts the line but does not change how fruit production responds to root size. (Note the negative intercepts: they are the fitted values at <code>Root</code> = 0 mm, far outside the range of the data (roughly 5–10 mm), and have no biological meaning.)</p>
<p><strong>(c)</strong> The <code>anova()</code> table is <em>sequential</em>: each row reports the deviance explained by a term <em>given the terms above it</em>. If <code>Root</code> and <code>Grazing</code> were independent (uncorrelated) in the data set, the deviance of each would be the same regardless of order. Here they are not independent — the grazed plants are bigger — so part of the deviance can be attributed to either variable:</p>
<ul>
<li><code>Grazing</code> entered first receives 2910: the difference between the raw group means, which is partly a size effect.</li>
<li><code>Grazing</code> entered after <code>Root</code> receives 5264: the grazing effect <em>at equal root size</em>, which is larger because it is no longer masked by the size difference working in the opposite direction.</li>
</ul>
<p>The residual deviance (1684.5 on 37 df) is the same in both tables because it belongs to the <em>final</em> model, which contains both terms whatever the order. Only the split of the explained deviance among the terms depends on the order. For an unbalanced or observational data set one should therefore be careful with sequential tables: the test of interest is usually the one where the term of interest is entered <em>last</em>, or, better, the comparison of two nested models with <code>anova(fm_small, fm_big)</code>.</p>
<p><strong>(d)</strong> <code>Root:GrazingUngrazed</code> is the <em>difference in slope</em> between ungrazed and grazed plants: the ungrazed line is estimated to be 0.76 mg per mm steeper. Its standard error (2.35) is three times the estimate, <span class="math inline">\(p = 0.75\)</span>, and the model comparison gives <span class="math inline">\(F = 0.10\)</span>, <span class="math inline">\(p = 0.75\)</span>. There is no evidence that the effect of root size differs between the groups; the parallel-lines model is adequate and should be reported. Note that in the interaction model the <code>GrazingUngrazed</code> coefficient (30.8, <span class="math inline">\(p = 0.076\)</span>) is no longer “significant” — not because the grazing effect has disappeared, but because in that model it represents the difference between the groups at <code>Root</code> = 0, a meaningless extrapolation where the two lines are poorly determined. This is a typical side effect of including an unnecessary interaction.</p>
<p><strong>(e)</strong> Because root diameter was measured before the treatment, it cannot have been influenced by grazing: it is a genuine <em>covariate</em> that describes the initial state of the plant, and adjusting for it makes the grazing effect cleaner. If root diameter had been measured <em>after</em> grazing, it might itself be a consequence of grazing (e.g.&nbsp;grazed plants invest in roots, or lose root mass). Adjusting for it would then remove part of the grazing effect — the part that acts <em>through</em> root size — and the <code>GrazingUngrazed</code> coefficient would only measure the residual effect not mediated by root growth. The statistical model would be the same, but the causal interpretation would be very different. Whether a variable is a covariate or an intermediate outcome is a question of design, not of statistics.</p>
</section>
</section>
<section id="exercise-3-interaction-between-a-continuous-and-a-categorical-predictor" class="level1">
<h1>Exercise 3 — Interaction between a continuous and a categorical predictor</h1>
<p><code>wells</code>: contaminated wells <code>y</code> out of <code>n</code> in 20 areas, nitrate concentration and sewerage; quasi-binomial model.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>fw_int <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(y, n <span class="sc">-</span> y) <span class="sc">~</span> nitrate <span class="sc">*</span> sewer, <span class="at">family =</span> quasibinomial, <span class="at">data =</span> wells)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>fw_add <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(y, n <span class="sc">-</span> y) <span class="sc">~</span> nitrate <span class="sc">+</span> sewer, <span class="at">family =</span> quasibinomial, <span class="at">data =</span> wells)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fw_int)<span class="sc">$</span>coefficients, <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                 Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)       -3.0689     0.5984 -5.1287   0.0001
nitrate            0.0661     0.1656  0.3989   0.6952
seweryes          -0.1329     1.0104 -0.1315   0.8970
nitrate:seweryes   0.5541     0.2539  2.1820   0.0444</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fw_int)<span class="sc">$</span>dispersion, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.11</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fw_add, fw_int, <span class="at">test =</span> <span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: cbind(y, n - y) ~ nitrate + sewer
Model 2: cbind(y, n - y) ~ nitrate * sewer
  Resid. Df Resid. Dev Df Deviance      F  Pr(&gt;F)  
1        17     45.382                             
2        16     34.087  1   11.295 5.3532 0.03431 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y <span class="sc">/</span> n <span class="sc">~</span> nitrate, <span class="at">data =</span> wells, <span class="at">cex =</span> <span class="fu">sqrt</span>(n) <span class="sc">/</span> <span class="dv">3</span>, <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">16</span>)[<span class="fu">factor</span>(sewer)], <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"nitrate (mg/l)"</span>, <span class="at">ylab =</span> <span class="st">"proportion of contaminated wells"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>xnew <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">8</span>, <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (s <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"no"</span>, <span class="st">"yes"</span>)) {</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  pr <span class="ot">&lt;-</span> <span class="fu">predict</span>(fw_int, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">nitrate =</span> xnew, <span class="at">sewer =</span> s), <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">matlines</span>(xnew, <span class="fu">plogis</span>(<span class="fu">cbind</span>(pr<span class="sc">$</span>fit, pr<span class="sc">$</span>fit <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> pr<span class="sc">$</span>se.fit, pr<span class="sc">$</span>fit <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> pr<span class="sc">$</span>se.fit)),</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>), <span class="at">col =</span> <span class="fu">ifelse</span>(s <span class="sc">==</span> <span class="st">"yes"</span>, <span class="st">"black"</span>, <span class="st">"grey50"</span>), <span class="at">lwd =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">1</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"grey50"</span>), <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"sewered"</span>, <span class="st">"unsewered"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_5_multiple_regression_answers_files/figure-html/ex3-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Proportion of contaminated wells against nitrate in sewered (filled) and unsewered (open) areas, with the fitted curves of the interaction model.</figcaption>
</figure>
</div>
</div>
</div>
<ol type="a">
<li>Write down the fitted model on the logit scale for unsewered and for sewered areas.</li>
<li>Calculate the fitted probability of contamination at 4 mg/l nitrate in an unsewered and in a sewered area.</li>
<li>What do the two non-significant main effects test, and why must they stay in the model?</li>
<li>Describe the interaction in words for a report on groundwater quality.</li>
<li>Why an F-test rather than a <span class="math inline">\(\chi^2\)</span> test? What would have happened to the p-value with the ordinary binomial family?</li>
</ol>
<section id="answer-2" class="level2">
<h2 class="anchored" data-anchor-id="answer-2">Answer</h2>
<p><strong>(a)</strong> The reference level of <code>sewer</code> is <code>no</code>. Hence:</p>
<ul>
<li>Unsewered: <span class="math inline">\(\mathrm{logit}(p) = -3.069 + 0.066 \cdot \mathrm{nitrate}\)</span></li>
<li>Sewered: <span class="math inline">\(\mathrm{logit}(p) = (-3.069 - 0.133) + (0.066 + 0.554) \cdot \mathrm{nitrate} = -3.202 + 0.620 \cdot \mathrm{nitrate}\)</span></li>
</ul>
<p>The <code>seweryes</code> coefficient shifts the intercept, the <code>nitrate:seweryes</code> coefficient changes the slope.</p>
<p><strong>(b)</strong> At 4 mg/l:</p>
<ul>
<li>Unsewered: <span class="math inline">\(\eta = -3.069 + 0.066 \times 4 = -2.80\)</span>, so <span class="math inline">\(p = e^{-2.80}/(1 + e^{-2.80}) = 0.057\)</span>, about 6 % of the wells.</li>
<li>Sewered: <span class="math inline">\(\eta = -3.202 + 0.620 \times 4 = -0.72\)</span>, so <span class="math inline">\(p = e^{-0.72}/(1 + e^{-0.72}) = 0.33\)</span>, about a third of the wells.</li>
</ul>
<p>Both numbers can be checked against the curves in the figure at nitrate = 4.</p>
<p><strong>(c)</strong> In a model with an interaction the main effects are <em>conditional</em> effects at the reference level or at zero of the other variable:</p>
<ul>
<li><code>nitrate</code> (0.066, <span class="math inline">\(p = 0.70\)</span>) is the slope of nitrate <em>in unsewered areas only</em>. The test says: in unsewered areas there is no detectable relation between nitrate and contamination. That is a real and interesting result, not a statement about nitrate in general.</li>
<li><code>seweryes</code> (−0.13, <span class="math inline">\(p = 0.90\)</span>) is the difference between sewered and unsewered areas <em>at nitrate = 0 mg/l</em>. Nitrate concentrations of exactly 0 hardly occur, and at low nitrate the two curves are indeed close together, so this test tells us little.</li>
</ul>
<p>Both must stay in the model because the interaction <code>nitrate:sewer</code> is significant and contains them (marginality). Dropping <code>nitrate</code> while keeping <code>nitrate:sewer</code> would force the unsewered slope to be exactly zero; dropping <code>sewer</code> would force the two curves through the same intercept. Both would be arbitrary constraints that change the meaning of the remaining coefficients and make them depend on how the factor is coded.</p>
<p><strong>(d)</strong> In <em>unsewered</em> areas the proportion of contaminated wells is low (around 5 %) and does not increase with the nitrate concentration (the grey curve is almost flat). In <em>sewered</em> areas the proportion rises steeply with nitrate, from a few percent at low concentrations to about 50 % at 5 mg/l and beyond. In other words, nitrate is only a useful indicator of TCE contamination where sewers are present. This suggests that the contamination and the nitrate have a common source connected to the sewer system (leaking sewers carrying both nutrients and industrial solvents into the groundwater), rather than nitrate itself causing contamination; in unsewered areas nitrate comes from other sources (agriculture, septic tanks) that are not associated with TCE. Note that the confidence band for sewered areas at high nitrate is wide, because few areas have high nitrate.</p>
<p><strong>(e)</strong> With a quasi-likelihood family the dispersion parameter is <em>estimated</em> from the data (<span class="math inline">\(\hat\phi = 2.1\)</span>), and the deviance difference has to be divided by that estimate. A ratio of two estimated quantities is F-distributed, not <span class="math inline">\(\chi^2\)</span>-distributed — exactly as in the gaussian case, where <span class="math inline">\(\sigma^2\)</span> is estimated. The test statistic is <span class="math inline">\(F = (11.30 / 1) / 2.11 = 5.35\)</span> on 1 and 16 df.</p>
<p>With the ordinary binomial family the dispersion would have been fixed at 1, the test statistic would have been the raw deviance difference 11.3 on 1 df compared with a <span class="math inline">\(\chi^2_1\)</span> distribution, giving <span class="math inline">\(p \approx 0.0008\)</span> — some forty times smaller. As in Practical 4b, ignoring the overdispersion would have overstated the evidence for the interaction. (Note that the dispersion in the interaction model is 2.1, much less than the 5.6 we found for the model with nitrate only: the interaction with sewerage explains part of what looked like overdispersion before.)</p>
</section>
</section>
<section id="exercise-4-interaction-and-model-simplification-with-a-negative-binomial-glm" class="level1">
<h1>Exercise 4 — Interaction and model simplification with a negative binomial GLM</h1>
<p><code>RIKZdat</code>: richness against <code>NAP</code> and beach <code>exposure</code> (factor with levels 8, 10, 11), negative binomial GLMs.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>RIKZdat<span class="sc">$</span>exposure <span class="ot">&lt;-</span> <span class="fu">factor</span>(RIKZdat<span class="sc">$</span>exposure)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>fr_nap <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Richness <span class="sc">~</span> NAP, <span class="at">data =</span> RIKZdat)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>fr_exp <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Richness <span class="sc">~</span> exposure, <span class="at">data =</span> RIKZdat)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>fr_add <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Richness <span class="sc">~</span> NAP <span class="sc">+</span> exposure, <span class="at">data =</span> RIKZdat)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>fr_int <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Richness <span class="sc">~</span> NAP <span class="sc">*</span> exposure, <span class="at">data =</span> RIKZdat)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fr_int)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)       2.549      0.168  15.129    0.000
NAP              -0.324      0.178  -1.823    0.068
exposure10       -0.632      0.199  -3.182    0.001
exposure11       -1.354      0.220  -6.156    0.000
NAP:exposure10   -0.338      0.214  -1.579    0.114
NAP:exposure11   -0.244      0.244  -0.999    0.318</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fr_add, fr_int)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of Negative Binomial Models

Response: Richness
           Model    theta Resid. df    2 x log-lik.   Test    df LR stat.
1 NAP + exposure 15.25376        41       -196.0406                      
2 NAP * exposure 18.25390        39       -193.7610 1 vs 2     2 2.279608
    Pr(Chi)
1          
2 0.3198817</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(fr_nap, fr_exp, fr_add, fr_int)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       df      AIC
fr_nap  3 231.7456
fr_exp  4 239.2391
fr_add  5 206.0406
fr_int  7 207.7610</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fr_add)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)    2.583      0.175  14.761    0.000
NAP           -0.569      0.086  -6.644    0.000
exposure10    -0.658      0.205  -3.208    0.001
exposure11    -1.388      0.226  -6.133    0.000</code></pre>
</div>
</div>
<ol type="a">
<li>Which combination does the intercept of the interaction model refer to? Write down the slope of <code>NAP</code> for each exposure class.</li>
<li>Is the interaction needed? Why does the test have 2 degrees of freedom?</li>
<li>Rank the four models by AIC. Which single-predictor model is better, and how does that compare with Practical 4b?</li>
<li>By which factor does richness differ between exposure 8 and 11, and per metre of NAP?</li>
<li>Why is the y-axis on a log scale, and what property of the additive model becomes visible?</li>
</ol>
<section id="answer-3" class="level2">
<h2 class="anchored" data-anchor-id="answer-3">Answer</h2>
<p><strong>(a)</strong> The intercept (2.549) is the log expected richness at <code>NAP</code> = 0 m on a beach with exposure 8, the first factor level. The slope of <code>NAP</code> on the log scale per exposure class is:</p>
<ul>
<li>exposure 8: <span class="math inline">\(-0.324\)</span> (the <code>NAP</code> coefficient itself)</li>
<li>exposure 10: <span class="math inline">\(-0.324 - 0.338 = -0.662\)</span></li>
<li>exposure 11: <span class="math inline">\(-0.324 - 0.244 = -0.568\)</span></li>
</ul>
<p>The interaction coefficients are the <em>differences</em> in slope from the exposure-8 slope. Both are negative (steeper decline on more exposed beaches) but neither is significant on its own (<span class="math inline">\(p = 0.11\)</span> and <span class="math inline">\(0.32\)</span>).</p>
<p><strong>(b)</strong> No.&nbsp;The likelihood-ratio test compares the additive model (41 residual df) with the interaction model (39 residual df): LR statistic 2.28 on 2 df, <span class="math inline">\(p = 0.32\)</span>. The AIC agrees: 207.8 for the interaction model against 206.0 for the additive model — adding two parameters costs 4 AIC units and buys only 2.3 units of <span class="math inline">\(2\log L\)</span>. The test has 2 degrees of freedom because the interaction between a continuous variable and a factor with three levels adds <em>two</em> coefficients (one slope difference per non-reference level); <code>anova()</code> tests them jointly, which is the right way to judge whether “the interaction” is needed. Testing the two coefficients separately in the summary would only tell us something about each contrast with the reference level.</p>
<p><strong>(c)</strong> Ranked by AIC:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>model</th>
<th>AIC</th>
<th>ΔAIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>NAP + exposure</code></td>
<td>206.0</td>
<td>0</td>
</tr>
<tr class="even">
<td><code>NAP * exposure</code></td>
<td>207.8</td>
<td>1.7</td>
</tr>
<tr class="odd">
<td><code>NAP</code> only</td>
<td>231.7</td>
<td>25.7</td>
</tr>
<tr class="even">
<td><code>exposure</code> only</td>
<td>239.2</td>
<td>33.2</td>
</tr>
</tbody>
</table>
<p>The additive model is clearly best; the interaction model is within 2 units (as expected when two useless parameters are added) but is not better. Of the two single-predictor models, <code>NAP</code> alone is better than <code>exposure</code> alone by 7.5 units, but both are far behind the two-predictor models: each predictor explains a different part of the variation, and both are needed. In Practical 4b we used <code>NAP</code> alone (AIC 231.7 for the negative binomial model) and found conspicuous residuals for exposure-8 stations; adding exposure lowers the AIC by 26 units and resolves exactly that pattern.</p>
<p><strong>(d)</strong> From the additive model: <code>exposure11</code> <span class="math inline">\(= -1.388\)</span>, so <span class="math inline">\(e^{-1.388} = 0.25\)</span>: at a given NAP, the expected richness on an exposure-11 beach is a quarter of that on an exposure-8 beach (or, the other way round, sheltered beaches have four times as many species). For <code>NAP</code>: <span class="math inline">\(e^{-0.569} = 0.57\)</span>, so every metre higher on the beach multiplies the expected richness by 0.57, i.e.&nbsp;a decrease of 43 % per metre, the same on all three beach types. Because the model is additive <em>on the log scale</em>, the effects are <em>multiplicative</em> on the scale of the counts.</p>
<p><strong>(e)</strong> The link function is the log, so the model is linear in <code>NAP</code> on the log scale. On a logarithmic y-axis the fitted curves of the additive model become <strong>three parallel straight lines</strong>: same slope (the common <code>NAP</code> effect), shifted vertically by the exposure effects. That is exactly the “no interaction” assumption, and it is immediately visible. On a linear y-axis the same curves are exponential and <em>not</em> parallel — the vertical distance between them shrinks as NAP increases — which would wrongly suggest an interaction to the eye. The right-hand panel shows the interaction model, whose three lines have different slopes on the log scale; the difference from the parallel version is small, in line with the non-significant test.</p>
</section>
</section>
<section id="exercise-5-collinearity" class="level1">
<h1>Exercise 5 — Collinearity</h1>
<p><code>gala</code>: log-transformed island area, elevation, distance to nearest island and area of the adjacent island as predictors of plant species richness (negative binomial GLMs).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> gala</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>g<span class="sc">$</span>lArea <span class="ot">&lt;-</span> <span class="fu">log</span>(g<span class="sc">$</span>Area); g<span class="sc">$</span>lElev <span class="ot">&lt;-</span> <span class="fu">log</span>(g<span class="sc">$</span>Elevation)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>g<span class="sc">$</span>lNear <span class="ot">&lt;-</span> <span class="fu">log</span>(g<span class="sc">$</span>Nearest.dist); g<span class="sc">$</span>lAdj <span class="ot">&lt;-</span> <span class="fu">log</span>(g<span class="sc">$</span>Adjacent.isl.area)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(g[, <span class="fu">c</span>(<span class="st">"lArea"</span>, <span class="st">"lElev"</span>, <span class="st">"lNear"</span>, <span class="st">"lAdj"</span>)]), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      lArea lElev lNear  lAdj
lArea  1.00  0.83  0.10  0.15
lElev  0.83  1.00  0.20 -0.01
lNear  0.10  0.20  1.00 -0.09
lAdj   0.15 -0.01 -0.09  1.00</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>m_area <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Species <span class="sc">~</span> lArea, <span class="at">data =</span> g)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>m_elev <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Species <span class="sc">~</span> lElev, <span class="at">data =</span> g)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>m_both <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Species <span class="sc">~</span> lArea <span class="sc">+</span> lElev, <span class="at">data =</span> g)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>m_all  <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Species <span class="sc">~</span> lArea <span class="sc">+</span> lElev <span class="sc">+</span> lNear <span class="sc">+</span> lAdj, <span class="at">data =</span> g)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(m_area)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)    3.150      0.140  22.440        0
lArea          0.367      0.036  10.204        0</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(m_elev)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)    0.051      0.683   0.075     0.94
lElev          0.761      0.127   5.986     0.00</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(m_both)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)    3.449      0.773   4.461    0.000
lArea          0.389      0.065   5.962    0.000
lElev         -0.065      0.165  -0.396    0.692</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">vif</span>(m_all), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>lArea lElev lNear  lAdj 
 3.57  3.59  1.05  1.07 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(m_area, m_elev, m_both, m_all)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       df      AIC
m_area  3 273.9926
m_elev  3 294.3806
m_both  4 275.8631
m_all   6 276.6726</code></pre>
</div>
</div>
<ol type="a">
<li>Which pair of predictors is collinear? Why are they so strongly correlated?</li>
<li>Explain why <code>lElev</code> is highly significant alone but not in the model with <code>lArea</code>. Does elevation have no effect?</li>
<li>By what factor did the SE of <code>lArea</code> increase? What does a VIF of 3.6 mean?</li>
<li>Which model would you choose, and what can the data (not) tell us about area and elevation?</li>
<li>Can the data decide the argument that elevation is the more relevant variable? What data could?</li>
</ol>
<section id="answer-4" class="level2">
<h2 class="anchored" data-anchor-id="answer-4">Answer</h2>
<p><strong>(a)</strong> <code>lArea</code> and <code>lElev</code>, with <span class="math inline">\(r = 0.83\)</span> — well above Dormann’s limit of 0.7 (<span class="math inline">\(r^2 = 0.69\)</span>). The other correlations are all below 0.2. The physical reason is that the Galápagos are volcanic islands: an island is essentially a shield volcano, and a bigger volcano is both wider (larger area) and taller (higher elevation). Area and maximum elevation are two measurements of the same thing — the size of the volcano.</p>
<p><strong>(b)</strong> Alone, <code>lElev</code> carries all the information that is correlated with island size, and since size is a strong predictor of richness, elevation “inherits” a strong effect (0.76 per log unit, <span class="math inline">\(z = 6.0\)</span>). In the model with <code>lArea</code>, the coefficient of <code>lElev</code> measures the effect of elevation <em>at a given area</em> — the effect of the 31 % of the variation in elevation that is not explained by area. That residual variation is small, it does not seem to be related to richness, and the coefficient collapses to −0.07 with a standard error more than twice as large. The AIC also rises (274.0 → 275.9): elevation adds nothing once area is known.</p>
<p>This does <em>not</em> prove that elevation has no effect. It shows that, in this data set, area and elevation are so entangled that we cannot separate their effects: whatever elevation does is already captured by area. The interpretational problem of collinearity (Dormann Sect. 15.3) is exactly this: a non-significant coefficient for a collinear predictor means “no <em>additional</em> information”, not “no effect”.</p>
<p><strong>(c)</strong> The standard error of <code>lArea</code> rises from 0.036 in <code>m_area</code> to 0.065 in <code>m_both</code>, a factor of 1.8. The variance inflation factor of <code>lArea</code> in the full model is 3.57; the VIF is the factor by which the <em>variance</em> of a coefficient is inflated by the correlation with the other predictors, so the standard error is inflated by <span class="math inline">\(\sqrt{3.57} = 1.89\)</span> — which is what we observe. (A VIF of 3.6 corresponds to <span class="math inline">\(R^2 = 1 - 1/3.6 = 0.72\)</span> of that predictor being explained by the others, consistent with <span class="math inline">\(r = 0.83\)</span> between area and elevation.) Dormann’s threshold for action is a VIF of 10, so by that rule the collinearity is <em>not</em> severe enough to make the estimates unstable — but it is severe enough to make the <em>interpretation</em> of the two coefficients impossible, as (b) showed. The threshold of <span class="math inline">\(|r| &gt; 0.7\)</span> and the threshold of VIF &gt; 10 are answers to two different questions (can I interpret the two effects separately? / are the estimates numerically unstable?).</p>
<p><strong>(d)</strong> The model with <code>lArea</code> only (<code>m_area</code>): it has the lowest AIC (274.0), one parameter fewer than <code>m_both</code> and three fewer than <code>m_all</code>, and the extra predictors (<code>lElev</code>, <code>lNear</code>, <code>lAdj</code>) are all non-significant and change the area effect very little (0.367 → 0.389 → 0.375). <code>m_all</code> is 2.7 AIC units worse than <code>m_area</code>; <code>lNear</code> is the only other term with a hint of an effect (<span class="math inline">\(p = 0.07\)</span>), and even that does not pay for itself in AIC terms.</p>
<p>A discussion sentence: “Plant species richness increases with island area (<span class="math inline">\(z = 0.37 \pm 0.04\)</span>, negative binomial GLM). Because area and elevation are strongly correlated across the archipelago (<span class="math inline">\(r = 0.83\)</span>), the data cannot distinguish between an effect of area <em>per se</em> and an effect of elevation (or habitat diversity); we report the model with area as the single predictor, with the caveat that it should be read as an index of island size that includes elevation.”</p>
<p><strong>(e)</strong> Not with these data. The colleague’s model (<code>m_elev</code>, AIC 294.4) is 20 units worse than the area model, so if one <em>must</em> choose, the data prefer area; but that preference concerns the fit, not the mechanism, and with <span class="math inline">\(r = 0.83\)</span> neither variable can be held fixed while the other varies. What could decide the argument is data in which area and elevation are <em>decoupled</em>: an archipelago with flat large islands and steep small ones (e.g.&nbsp;atolls next to volcanic islands), or, within an island, samples of habitat diversity that vary independently of area. Alternatively, one could measure the proposed mechanism directly (the number of habitat types per island) and test whether it explains richness better than either area or elevation. In the absence of such data, the honest statement is that the two hypotheses are not distinguishable — which is itself a useful result.</p>
</section>
</section>
<section id="exercise-6-two-continuous-predictors-and-their-interaction" class="level1">
<h1>Exercise 6 — Two continuous predictors and their interaction</h1>
<p><code>loyn</code>: bird abundance in 56 forest fragments against log10(area) and grazing intensity (1–5), linear models.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>loyn<span class="sc">$</span>lAREA <span class="ot">&lt;-</span> <span class="fu">log10</span>(loyn<span class="sc">$</span>AREA)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>fl_add <span class="ot">&lt;-</span> <span class="fu">lm</span>(ABUND <span class="sc">~</span> lAREA <span class="sc">+</span> GRAZE, <span class="at">data =</span> loyn)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>fl_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(ABUND <span class="sc">~</span> lAREA <span class="sc">*</span> GRAZE, <span class="at">data =</span> loyn)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fl_add)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)   21.603      3.092   6.987        0
lAREA          6.890      1.290   5.341        0
GRAZE         -2.854      0.713  -4.005        0</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fl_int)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)   26.558      3.358   7.910    0.000
lAREA          2.112      2.038   1.037    0.305
GRAZE         -4.547      0.885  -5.138    0.000
lAREA:GRAZE    2.142      0.736   2.911    0.005</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fl_add, fl_int)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: ABUND ~ lAREA + GRAZE
Model 2: ABUND ~ lAREA * GRAZE
  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
1     53 2200.9                                
2     52 1892.5  1    308.49 8.4766 0.005287 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>area_seq  <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(loyn<span class="sc">$</span>lAREA), <span class="fu">max</span>(loyn<span class="sc">$</span>lAREA), <span class="at">length =</span> <span class="dv">50</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>graze_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="at">length =</span> <span class="dv">50</span>)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">outer</span>(area_seq, graze_seq,</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>           <span class="cf">function</span>(a, gr) <span class="fu">predict</span>(fl_int, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">lAREA =</span> a, <span class="at">GRAZE =</span> gr)))</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="fu">image</span>(area_seq, graze_seq, z, <span class="at">col =</span> <span class="fu">hcl.colors</span>(<span class="dv">50</span>, <span class="st">"YlGnBu"</span>, <span class="at">rev =</span> <span class="cn">TRUE</span>), <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">xlab =</span> <span class="st">"log10(area) (ha)"</span>, <span class="at">ylab =</span> <span class="st">"grazing intensity"</span>)</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="fu">contour</span>(area_seq, graze_seq, z, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">labcex =</span> <span class="fl">0.9</span>)</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(loyn<span class="sc">$</span>lAREA, loyn<span class="sc">$</span>GRAZE, <span class="at">pch =</span> <span class="dv">3</span>)</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>ch <span class="ot">&lt;-</span> <span class="fu">chull</span>(<span class="fu">cbind</span>(loyn<span class="sc">$</span>lAREA, loyn<span class="sc">$</span>GRAZE))</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">cbind</span>(loyn<span class="sc">$</span>lAREA, loyn<span class="sc">$</span>GRAZE)[ch, ], <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_5_multiple_regression_answers_files/figure-html/ex6-surface-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Fitted abundance surface of the interaction model with the observed predictor combinations (crosses) and their convex hull.</figcaption>
</figure>
</div>
</div>
</div>
<ol type="a">
<li>Interpret the <code>lAREA</code> (6.89) and <code>GRAZE</code> (−2.85) coefficients of the additive model, with attention to units.</li>
<li>Does the non-significant <code>lAREA</code> main effect of the interaction model mean that area has no effect? What does it represent?</li>
<li>Calculate the slope against <code>lAREA</code> at grazing intensity 1 and 5. Synergistic or antagonistic?</li>
<li>Where are the fitted values highest and lowest? Which corners have no data?</li>
<li>How would you check that the interaction is not an artefact of a non-linear effect?</li>
</ol>
<section id="answer-5" class="level2">
<h2 class="anchored" data-anchor-id="answer-5">Answer</h2>
<p><strong>(a)</strong> In the additive model, every increase of <code>lAREA</code> by one unit — i.e.&nbsp;a <strong>tenfold</strong> increase in fragment area, because the predictor is log10(area) — raises the expected bird abundance by 6.9 birds per census, at a given grazing intensity. Every step up the grazing index (e.g.&nbsp;from 2 to 3) lowers abundance by 2.9 birds, at a given area. Treating <code>GRAZE</code> as continuous assumes that each step of the index has the same effect, which is a simplification of an ordinal scale. Both effects are highly significant, and the model assumes they simply add up.</p>
<p><strong>(b)</strong> No.&nbsp;In the interaction model, <code>lAREA</code> is the slope of abundance against <code>lAREA</code> <strong>at <code>GRAZE</code> = 0</strong>, because the interaction term <code>lAREA:GRAZE</code> contributes nothing when <code>GRAZE</code> is zero. A grazing intensity of 0 does not exist — the index runs from 1 to 5 — so the coefficient is an extrapolation to a situation outside the data, with a correspondingly large standard error (2.04). The actual slopes at the grazing intensities that occur are given in (c) and are all clearly positive. This is the same phenomenon as in Exercise 2(d) and 3(c): main effects in the presence of an interaction are conditional effects at a reference point, and if that reference point is not meaningful, neither is the test. (Centring <code>GRAZE</code> at its mean, or at 3, would make the main effect the slope at an average grazing intensity and turn it “significant” again — without changing the model in any real sense.)</p>
<p><strong>(c)</strong> Slope of abundance against <code>lAREA</code> <span class="math inline">\(= 2.11 + 2.14 \times \mathrm{GRAZE}\)</span>:</p>
<ul>
<li>grazing 1: <span class="math inline">\(2.11 + 2.14 = 4.25\)</span> birds per tenfold area</li>
<li>grazing 5: <span class="math inline">\(2.11 + 10.71 = 12.82\)</span> birds per tenfold area</li>
</ul>
<p>The interaction coefficient is positive, so the effect of area is <em>stronger</em> under heavy grazing: in Dormann’s terminology the two predictors act synergistically — the effect of the product term goes in the same direction as the area effect. Equivalently, the effect of grazing depends on area: the grazing slope is <span class="math inline">\(-4.55 + 2.14 \times \mathrm{lAREA}\)</span>, which is strongly negative in small fragments (−6.7 birds per grazing step at 0.1 ha) and about zero in fragments of around 100 ha (<span class="math inline">\(\mathrm{lAREA} = 2\)</span>). In words: heavy grazing hits bird abundance hard in small fragments, whereas large fragments retain their birds even when grazed. The lines plot shows this as the three lines converging at large areas.</p>
<p><strong>(d)</strong> Fitted abundance is highest in the bottom-right (large, lightly grazed fragments, &gt; 35 birds) and lowest in the top-left (small, heavily grazed fragments), where the model even predicts <em>negative</em> abundance — an impossible value that signals that a gaussian model with an identity link is being extrapolated beyond its validity. Two corners of the plot contain no data and lie outside the convex hull: the top-left (there are no heavily grazed fragments smaller than about 0.5 ha) and the top-right (no heavily grazed fragments larger than about 25 ha; the large fragments in this data set are all lightly grazed). The model’s statements about those corners rest on the assumption that the linear interaction continues outside the data — pure extrapolation. The claim that “large fragments retain their birds even when grazed” is therefore only supported up to about 25 ha; for the largest fragments the effect of heavy grazing is unknown. This is the “curse of dimensionality” that Dormann discusses (Sect. 16.1.3): even though both predictors individually cover their range well, the <em>combinations</em> do not.</p>
<p><strong>(e)</strong> Compare the interaction model with a model that allows a curved effect of area (and/or of grazing) but no interaction, e.g.&nbsp;<code>ABUND ~ poly(lAREA, 2) + GRAZE</code>, and with a model containing both, <code>ABUND ~ poly(lAREA, 2) * GRAZE</code> or <code>poly(lAREA, 2) + GRAZE + lAREA:GRAZE</code>. If the quadratic term absorbs the improvement in fit and the interaction becomes non-significant once the quadratic term is present, the “interaction” was a disguised non-linearity. If the interaction remains significant with the quadratic term in the model, it is genuine. Dormann’s advice is to include both non-linear terms and interactions in the full model and let model selection decide.</p>
</section>
</section>
<section id="exercise-7-model-selection" class="level1">
<h1>Exercise 7 — Model selection</h1>
<p><code>loyn</code>: all six predictors of bird abundance; backward stepwise selection by AIC and BIC and best-subset selection.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>loyn<span class="sc">$</span>lDIST  <span class="ot">&lt;-</span> <span class="fu">log10</span>(loyn<span class="sc">$</span>DIST)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>loyn<span class="sc">$</span>lLDIST <span class="ot">&lt;-</span> <span class="fu">log10</span>(loyn<span class="sc">$</span>LDIST)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>fl_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(ABUND <span class="sc">~</span> lAREA <span class="sc">+</span> lDIST <span class="sc">+</span> lLDIST <span class="sc">+</span> YR.ISOL <span class="sc">+</span> GRAZE <span class="sc">+</span> ALT, <span class="at">data =</span> loyn,</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">na.action =</span> na.fail)</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fl_full)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -125.697     91.692  -1.371    0.177
lAREA          7.470      1.465   5.099    0.000
lDIST         -0.907      2.676  -0.339    0.736
lLDIST        -0.648      2.123  -0.305    0.761
YR.ISOL        0.074      0.045   1.634    0.109
GRAZE         -1.668      0.930  -1.793    0.079
ALT            0.020      0.024   0.814    0.419</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">vif</span>(fl_full), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  lAREA   lDIST  lLDIST YR.ISOL   GRAZE     ALT 
   1.91    1.65    2.01    1.80    2.52    1.47 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>fl_stepAIC <span class="ot">&lt;-</span> <span class="fu">step</span>(fl_full, <span class="at">trace =</span> <span class="dv">0</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>fl_stepBIC <span class="ot">&lt;-</span> <span class="fu">step</span>(fl_full, <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">nrow</span>(loyn)), <span class="at">trace =</span> <span class="dv">0</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(fl_full, <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">nrow</span>(loyn)), <span class="at">steps =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=228.32
ABUND ~ lAREA + lDIST + lLDIST + YR.ISOL + GRAZE + ALT

          Df Sum of Sq    RSS    AIC
- lLDIST   1      3.80 2000.7 224.40
- lDIST    1      4.68 2001.5 224.43
- ALT      1     27.02 2023.9 225.05
- YR.ISOL  1    108.83 2105.7 227.27
- GRAZE    1    131.07 2127.9 227.85
&lt;none&gt;                 1996.8 228.32
- lAREA    1   1059.75 3056.6 248.14

Step:  AIC=224.4
ABUND ~ lAREA + lDIST + YR.ISOL + GRAZE + ALT</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ABUND ~ lAREA + lDIST + YR.ISOL + GRAZE + ALT, data = loyn, 
    na.action = na.fail)

Coefficients:
(Intercept)        lAREA        lDIST      YR.ISOL        GRAZE          ALT  
 -131.84739      7.29529     -1.30325      0.07658     -1.67573      0.02145  </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>dm <span class="ot">&lt;-</span> <span class="fu">dredge</span>(fl_full, <span class="at">rank =</span> <span class="st">"AIC"</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">subset</span>(dm, delta <span class="sc">&lt;</span> <span class="dv">2</span>), <span class="at">abbrev.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Global model call: lm(formula = ABUND ~ lAREA + lDIST + lLDIST + YR.ISOL + GRAZE + 
    ALT, data = loyn, na.action = na.fail)
---
Model selection table 
   (Intercept)     ALT  GRAZE lAREA  lDIST lLDIST YR.ISOL df   logLik   AIC
39     -134.30         -1.902 7.166               0.07835  5 -180.555 371.1
40     -141.90 0.02586 -1.601 7.076               0.07991  6 -179.761 371.5
55     -113.40         -1.842 7.751        -1.646 0.06941  6 -180.036 372.1
47     -120.50         -1.939 7.487 -2.048        0.07354  6 -180.072 372.1
7        21.60         -2.854 6.890                        4 -182.257 372.5
23       25.74         -2.630 7.709        -2.190          5 -181.347 372.7
38     -236.70 0.03623        8.150               0.12480  5 -181.428 372.9
   delta weight
39  0.00  0.228
40  0.41  0.185
55  0.96  0.141
47  1.04  0.136
7   1.40  0.113
23  1.59  0.103
38  1.75  0.095
Models ranked by AIC(x) </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(fl_full, fl_stepAIC, fl_stepBIC)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>           df      AIC
fl_full     8 375.0638
fl_stepAIC  5 371.1092
fl_stepBIC  4 372.5134</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(fl_full, fl_stepAIC, fl_stepBIC)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>           df      BIC
fl_full     8 391.2666
fl_stepAIC  5 381.2360
fl_stepBIC  4 380.6148</code></pre>
</div>
</div>
<ol type="a">
<li>Is collinearity a problem in the full model?</li>
<li>Why can a model be highly significant as a whole while most coefficients are not?</li>
<li>Explain the rows of the displayed selection step. Which term is removed and why?</li>
<li>Why does BIC lead to a smaller model? Which criterion with 56 observations?</li>
<li>What does <code>weight</code> mean? What does a best-model weight of 0.23 tell you? Which predictors appear in all or most of the seven models?</li>
<li>Formulate your final model with justification, and one caveat about its p-values.</li>
</ol>
<section id="answer-6" class="level2">
<h2 class="anchored" data-anchor-id="answer-6">Answer</h2>
<p><strong>(a)</strong> Not seriously. The largest correlations are between <code>GRAZE</code> and <code>YR.ISOL</code> (<span class="math inline">\(r = -0.64\)</span>: fragments isolated longer ago are more heavily grazed), between <code>lDIST</code> and <code>lLDIST</code> (0.60: the two distance measures partly describe the same isolation) and between <code>GRAZE</code> and <code>lAREA</code> (−0.56). All are below the 0.7 limit, and the VIFs are all below 2.6, far from the critical value of 10. The pair <code>GRAZE</code>/<code>YR.ISOL</code> is the one to keep an eye on: because they are correlated, the model has some difficulty attributing the effect to one or the other, which is why both have moderate p-values (0.08 and 0.11) in the full model although each is a good predictor on its own. It is not a problem for the fit, but it will show up in the model selection as an ambiguity about which of the two to keep.</p>
<p><strong>(b)</strong> The p-value of an individual coefficient tests whether that predictor explains variation <em>that the other predictors in the model do not already explain</em>. When predictors are correlated, they share explanatory power: the model as a whole explains 68 % of the variance (<span class="math inline">\(F = 17.8\)</span>, <span class="math inline">\(p &lt; 10^{-10}\)</span>), but much of that is joint, and any single predictor except <code>lAREA</code> can be dropped with only a small loss because a correlated partner takes over its role. Two further reasons: the full model spends 7 parameters on 56 observations, so each is estimated with limited precision, and <code>lDIST</code> and <code>lLDIST</code> are simply weak predictors. “Not significant in the full model” therefore means “not needed <em>in addition to the others</em>”, which is a different statement from “unrelated to bird abundance”.</p>
<p><strong>(c)</strong> The table shows the current model (<code>&lt;none&gt;</code>: the full model, with residual sum of squares 1996.8 and criterion value 228.3) together with every model that can be obtained by removing one term. Each row <code>- term</code> gives the increase in residual sum of squares (<code>Sum of Sq</code>) and the criterion value of the model without that term. The rows are sorted by the criterion, best (lowest) first. Rows <em>above</em> <code>&lt;none&gt;</code> are models that are better than the current one; rows below are worse. <code>- lAREA</code> is at the bottom because removing area increases the residual sum of squares by 1060 (half of what the model explains) and the criterion by 20 units: area is by far the most important predictor. <code>- lLDIST</code> is at the top: removing it costs only 3.8 units of RSS and lowers the criterion from 228.3 to 224.4. So <code>lLDIST</code> is removed in this step, and the procedure continues with the five-predictor model. (Note that R labels the column <code>AIC</code> even though we asked for the BIC penalty <code>k = log(56)</code>; the values are BIC-like, which is why they differ from the <code>AIC()</code> values below.)</p>
<p><strong>(d)</strong> Both criteria are <span class="math inline">\(-2 \log L + k \times (\text{number of parameters})\)</span>; AIC uses <span class="math inline">\(k = 2\)</span>, BIC uses <span class="math inline">\(k = \log n = \log 56 = 4.0\)</span>. BIC therefore charges twice as much per parameter, and a term has to reduce <span class="math inline">\(-2\log L\)</span> by at least 4 (rather than 2) to earn its place. <code>YR.ISOL</code> reduces it by about 3.4 — enough for AIC, not for BIC — so AIC keeps <code>lAREA + YR.ISOL + GRAZE</code> and BIC keeps only <code>lAREA + GRAZE</code>. With 56 observations and moderately correlated predictors, the more conservative BIC (or the small-sample AICc) is the safer choice, following Dormann’s reasoning in Sect. 16.3.1: AIC tends to keep marginal terms when <span class="math inline">\(n\)</span> is small. The two final models differ by one term with <span class="math inline">\(p = 0.077\)</span>; either would be defensible, and both criteria agree that <code>lDIST</code>, <code>lLDIST</code> and <code>ALT</code> can go.</p>
<p><strong>(e)</strong> The Akaike weight of a model is <span class="math inline">\(\exp(-\Delta_i/2)\)</span> normalised so that the weights of all 64 models sum to 1; it can be read as the probability that this model is the best of the set, given the data. A weight of only 0.23 for the top model means that the data do not single out one model: the second model (adding <code>ALT</code>) has weight 0.19, and seven models within <span class="math inline">\(\Delta &lt; 2\)</span> together carry about 1.0 of the weight — they are practically equivalent descriptions. <code>lAREA</code> appears in all seven models with a stable coefficient (6.9–8.2), so its importance is beyond doubt. <code>GRAZE</code> appears in six of the seven and <code>YR.ISOL</code> in five; the one model without <code>GRAZE</code> (model 38) has <code>YR.ISOL</code> with a larger coefficient, and the one without <code>YR.ISOL</code> is the BIC model — this is the <code>GRAZE</code>/<code>YR.ISOL</code> correlation from (a) showing up as model-selection uncertainty. <code>ALT</code>, <code>lDIST</code> and <code>lLDIST</code> each appear in only one or two models, with small coefficients: they are dispensable.</p>
<p><strong>(f)</strong> A defensible final model is <code>ABUND ~ lAREA + GRAZE + YR.ISOL</code> (the AIC model, 371.1): it has the lowest AIC of all 64 sub-models and contains the three predictors that best-subset selection identifies as consistently useful. Bird abundance increases by about 7 birds per tenfold increase in fragment area, decreases by about 1.9 birds per step of grazing intensity and is higher in fragments isolated more recently (0.08 birds per year; <span class="math inline">\(p = 0.08\)</span>). One may equally report the BIC model without <code>YR.ISOL</code> (ΔAIC 1.4, lower BIC), noting that the effects of grazing and isolation age cannot be fully separated because heavily grazed fragments tend to be the ones isolated longest.</p>
<p>The caveat: the p-values in the selected model are computed as if the model had been specified in advance, but it was chosen <em>because</em> its terms looked good in this data set. Selection biases the retained coefficients away from zero and makes their p-values too optimistic (Dormann Sect. 15.4; Harrell 2001). The evidence for <code>lAREA</code> is overwhelming and unaffected, but the modest evidence for <code>YR.ISOL</code> (<span class="math inline">\(p = 0.08\)</span>) or <code>GRAZE</code> (<span class="math inline">\(p = 0.03\)</span>) after selection should be read as suggestive rather than confirmatory, and ideally checked on independent data.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>