<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>QSBS Practical 5 — Multiple regression: more than one predictor</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="QSBS_5_multiple_regression_files/libs/clipboard/clipboard.min.js"></script>
<script src="QSBS_5_multiple_regression_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="QSBS_5_multiple_regression_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="QSBS_5_multiple_regression_files/libs/quarto-html/popper.min.js"></script>
<script src="QSBS_5_multiple_regression_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="QSBS_5_multiple_regression_files/libs/quarto-html/anchor.min.js"></script>
<link href="QSBS_5_multiple_regression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="QSBS_5_multiple_regression_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="QSBS_5_multiple_regression_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="QSBS_5_multiple_regression_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="QSBS_5_multiple_regression_files/libs/bootstrap/bootstrap-94053d6e10daeb31c4957f2bd90b11ca.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#commands-used-in-this-practical" id="toc-commands-used-in-this-practical" class="nav-link" data-scroll-target="#commands-used-in-this-practical">Commands used in this practical</a></li>
  <li><a href="#exercise-1-two-categorical-predictors" id="toc-exercise-1-two-categorical-predictors" class="nav-link" data-scroll-target="#exercise-1-two-categorical-predictors">Exercise 1 — Two categorical predictors</a></li>
  <li><a href="#exercise-2-a-continuous-and-a-categorical-predictor-ancova" id="toc-exercise-2-a-continuous-and-a-categorical-predictor-ancova" class="nav-link" data-scroll-target="#exercise-2-a-continuous-and-a-categorical-predictor-ancova">Exercise 2 — A continuous and a categorical predictor (ANCOVA)</a></li>
  <li><a href="#exercise-3-interaction-between-a-continuous-and-a-categorical-predictor" id="toc-exercise-3-interaction-between-a-continuous-and-a-categorical-predictor" class="nav-link" data-scroll-target="#exercise-3-interaction-between-a-continuous-and-a-categorical-predictor">Exercise 3 — Interaction between a continuous and a categorical predictor</a></li>
  <li><a href="#exercise-4-interaction-and-model-simplification-with-a-negative-binomial-glm" id="toc-exercise-4-interaction-and-model-simplification-with-a-negative-binomial-glm" class="nav-link" data-scroll-target="#exercise-4-interaction-and-model-simplification-with-a-negative-binomial-glm">Exercise 4 — Interaction and model simplification with a negative binomial GLM</a></li>
  <li><a href="#exercise-5-collinearity" id="toc-exercise-5-collinearity" class="nav-link" data-scroll-target="#exercise-5-collinearity">Exercise 5 — Collinearity</a></li>
  <li><a href="#exercise-6-two-continuous-predictors-and-their-interaction" id="toc-exercise-6-two-continuous-predictors-and-their-interaction" class="nav-link" data-scroll-target="#exercise-6-two-continuous-predictors-and-their-interaction">Exercise 6 — Two continuous predictors and their interaction</a></li>
  <li><a href="#exercise-7-model-selection" id="toc-exercise-7-model-selection" class="nav-link" data-scroll-target="#exercise-7-model-selection">Exercise 7 — Model selection</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">QSBS Practical 5 — Multiple regression: more than one predictor</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Up to now every regression model had a single predictor. In this practical we add more predictors (Dormann, Chap. 15 and 16). In principle nothing changes: the model simply gets one more term, e.g.&nbsp;<span class="math inline">\(y \sim \mathrm{NegBin}(\mu = e^{a + b x_1 + c x_2}, \theta)\)</span>, and <code>glm()</code> estimates all coefficients by maximum likelihood. In practice, four complications arise:</p>
<ol type="1">
<li><strong>Visualising</strong> the data and the model, because a figure has only two axes. The usual solutions are <em>panel plots</em> (one panel per level of a second predictor), <em>all-in-one plots</em> with different symbols or colours per group, and for two continuous predictors <em>effect plots</em> or <em>image/contour plots</em> of the fitted surface.</li>
<li><strong>Interactions.</strong> Two predictors interact when the effect of one depends on the value of the other. In a figure this shows up as lines with <em>different slopes</em>; in the model as a product term <code>x1:x2</code> (R’s <code>x1 * x2</code> means <code>x1 + x2 + x1:x2</code>). The coefficient of the interaction is the <em>change in slope</em> of one predictor per unit of the other. If an interaction is in the model, its main effects must stay in the model, even if they are not significant (the <strong>marginality principle</strong>, Nelder 1977).</li>
<li><strong>Collinearity.</strong> Predictors that are strongly correlated with each other (<span class="math inline">\(|r| &gt; 0.7\)</span>, Dormann et al.&nbsp;2013) cannot be separated by the model: their coefficients become unstable and their standard errors inflate (quantified by the <em>variance inflation factor</em>, VIF, which should stay below 10). The remedy is to check correlations <em>before</em> modelling and keep only one predictor of each correlated group.</li>
<li><strong>Model selection.</strong> With several predictors and their interactions, many candidate models exist. The full model is compared with simpler models by likelihood-ratio tests (<code>anova()</code>) or by information criteria (AIC, BIC; BIC penalises complexity more strongly and prefers simpler models). Backward stepwise selection (<code>step()</code>) drops one term at a time; best-subset selection (<code>MuMIn::dredge()</code>) fits all sub-models and ranks them. Note that the <code>anova()</code> table of a single model is <em>sequential</em>: each term is tested after the terms above it, so the order of the terms matters when predictors are correlated.</li>
</ol>
<p><strong>This practical is different from the previous ones: you do not have to write any R code</strong> (occasionally you might use R to calculate coefficient-backtransforms). All output and figures are produced for you, and the code that produced them is shown so that you can see how it was done. Your task is to <em>read and interpret</em> the output, exactly as you would when reading a paper or a report. Write down your answers in a text document.</p>
<p>The data come from the <code>qsbsdata</code> package; in addition <code>MASS</code> (negative binomial GLM), <code>car</code> (variance inflation factors) and <code>MuMIn</code> (best-subset regression) are used.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(qsbsdata)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MuMIn)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="commands-used-in-this-practical" class="level1">
<h1>Commands used in this practical</h1>
<p>For reference only — you do not need to run them.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model formulae with several predictors</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>y <span class="sc">~</span> x1 <span class="sc">+</span> x2              <span class="co"># additive: two main effects</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>y <span class="sc">~</span> x1 <span class="sc">*</span> x2              <span class="co"># main effects plus interaction (= x1 + x2 + x1:x2)</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>y <span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x1<span class="sc">:</span>x2      <span class="co"># the same, written out</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">update</span>(fm, . <span class="sc">~</span> . <span class="sc">-</span> x1<span class="sc">:</span>x2)  <span class="co"># drop a term from an existing model</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Sequential analysis-of-deviance table of ONE model (order of terms matters!)</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fm, <span class="at">test =</span> <span class="st">"F"</span>)      <span class="co"># gaussian / quasi families</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fm, <span class="at">test =</span> <span class="st">"Chisq"</span>)  <span class="co"># poisson / binomial</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fm_small, fm_big)    <span class="co"># compare two nested models</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicted value for a combination of predictors</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fm, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x1 =</span> <span class="dv">3</span>, <span class="at">f =</span> <span class="st">"level"</span>), <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Collinearity</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(d[, <span class="fu">c</span>(<span class="st">"x1"</span>, <span class="st">"x2"</span>, <span class="st">"x3"</span>)])</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(d[, <span class="fu">c</span>(<span class="st">"x1"</span>, <span class="st">"x2"</span>, <span class="st">"x3"</span>)])</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(fm)                    <span class="co"># variance inflation factors (package car)</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Model selection</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(fm1, fm2, fm3); <span class="fu">BIC</span>(fm1, fm2, fm3)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(fm)                   <span class="co"># backward stepwise by AIC</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(fm, <span class="at">k =</span> <span class="fu">log</span>(n))       <span class="co"># backward stepwise by BIC</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="fu">dredge</span>(fm, <span class="at">rank =</span> <span class="st">"AIC"</span>)   <span class="co"># all sub-models (package MuMIn; needs na.action = na.fail)</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualising two continuous predictors</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">outer</span>(x1seq, x2seq, <span class="cf">function</span>(a, b) <span class="fu">predict</span>(fm, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x1 =</span> a, <span class="at">x2 =</span> b)))</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="fu">image</span>(x1seq, x2seq, z); <span class="fu">contour</span>(x1seq, x2seq, z, <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="exercise-1-two-categorical-predictors" class="level1">
<h1>Exercise 1 — Two categorical predictors</h1>
<p>Asghar et al.&nbsp;(2015, <em>Science</em>) measured the telomere length of great reed warbler chicks at 9 days of age (<code>OffBTL</code>, in <code>birdmalariaO</code>) and asked whether it depends on the malaria infection status of the mother (<code>mmal</code>: healthy or infected) and on the sex of the chick. Both predictors are factors with two levels, so there are four groups.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>bird <span class="ot">&lt;-</span> birdmalariaO</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>bird<span class="sc">$</span>Sex  <span class="ot">&lt;-</span> <span class="fu">factor</span>(bird<span class="sc">$</span>Sex,  <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"male"</span>, <span class="st">"female"</span>))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>bird<span class="sc">$</span>mmal <span class="ot">&lt;-</span> <span class="fu">factor</span>(bird<span class="sc">$</span>mmal, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"healthy"</span>, <span class="st">"infected"</span>))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>bird <span class="ot">&lt;-</span> bird[<span class="fu">complete.cases</span>(bird[, <span class="fu">c</span>(<span class="st">"OffBTL"</span>, <span class="st">"Sex"</span>, <span class="st">"mmal"</span>)]), ]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(bird<span class="sc">$</span>Sex, bird<span class="sc">$</span>mmal)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        
         healthy infected
  male        57       45
  female      40       37</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">tapply</span>(bird<span class="sc">$</span>OffBTL, <span class="fu">list</span>(bird<span class="sc">$</span>Sex, bird<span class="sc">$</span>mmal), mean), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       healthy infected
male     0.973    0.806
female   1.009    0.823</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">male =</span> <span class="st">"firebrick"</span>, <span class="at">female =</span> <span class="st">"steelblue"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>off  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">male =</span> <span class="sc">-</span><span class="fl">0.12</span>, <span class="at">female =</span> <span class="fl">0.12</span>)                 <span class="co"># horizontal shift per sex</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>yl   <span class="ot">&lt;-</span> <span class="fu">range</span>(bird<span class="sc">$</span>OffBTL)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co"># left: all observations, jittered around the shifted group positions</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>xpos <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(bird<span class="sc">$</span>mmal) <span class="sc">+</span> off[<span class="fu">as.character</span>(bird<span class="sc">$</span>Sex)] <span class="sc">+</span> <span class="fu">runif</span>(<span class="fu">nrow</span>(bird), <span class="sc">-</span><span class="fl">0.05</span>, <span class="fl">0.05</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(xpos, bird<span class="sc">$</span>OffBTL, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> cols[<span class="fu">as.character</span>(bird<span class="sc">$</span>Sex)], <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">2.5</span>), <span class="at">ylim =</span> yl, <span class="at">xaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"mother"</span>, <span class="at">ylab =</span> <span class="st">"telomere length (relative units)"</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">labels =</span> <span class="fu">levels</span>(bird<span class="sc">$</span>mmal))</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> cols, <span class="at">legend =</span> <span class="fu">names</span>(cols))</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co"># right: group means ± 1 SE, same y-axis, same horizontal shift</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>m  <span class="ot">&lt;-</span> <span class="fu">tapply</span>(bird<span class="sc">$</span>OffBTL, <span class="fu">list</span>(bird<span class="sc">$</span>mmal, bird<span class="sc">$</span>Sex), mean)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">tapply</span>(bird<span class="sc">$</span>OffBTL, <span class="fu">list</span>(bird<span class="sc">$</span>mmal, bird<span class="sc">$</span>Sex), <span class="cf">function</span>(x) <span class="fu">sd</span>(x) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(x)))</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="cn">NA</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">2.5</span>), <span class="at">ylim =</span> yl, <span class="at">xaxt =</span> <span class="st">"n"</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"mother"</span>, <span class="at">ylab =</span> <span class="st">"mean telomere length (± 1 SE)"</span>)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">labels =</span> <span class="fu">levels</span>(bird<span class="sc">$</span>mmal))</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (sx <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"male"</span>, <span class="st">"female"</span>)) {</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span> <span class="sc">+</span> off[sx]</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(x, m[, sx], <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> cols[sx])</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrows</span>(x, m[, sx] <span class="sc">-</span> se[, sx], x, m[, sx] <span class="sc">+</span> se[, sx], <span class="at">angle =</span> <span class="dv">90</span>, <span class="at">code =</span> <span class="dv">3</span>, <span class="at">length =</span> <span class="fl">0.05</span>, <span class="at">col =</span> cols[sx])</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> cols, <span class="at">legend =</span> <span class="fu">names</span>(cols))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_5_multiple_regression_files/figure-html/ex1-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Telomere length of great reed warbler chicks by mother’s malaria status and chick sex (red = male, blue = female). Left: all data; right: group means ± 1 standard error, connected per sex (an <em>interaction plot</em>). Male and female points are shifted slightly sideways so that they do not overlap.</figcaption>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Two gaussian GLMs were fitted: an <strong>additive</strong> model and a model <strong>with interaction</strong>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>fb_add <span class="ot">&lt;-</span> <span class="fu">glm</span>(OffBTL <span class="sc">~</span> Sex <span class="sc">+</span> mmal, <span class="at">family =</span> gaussian, <span class="at">data =</span> bird)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>fb_int <span class="ot">&lt;-</span> <span class="fu">glm</span>(OffBTL <span class="sc">~</span> Sex <span class="sc">*</span> mmal, <span class="at">family =</span> gaussian, <span class="at">data =</span> bird)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fb_int)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                          Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept)             0.97325432 0.04555958 21.362232 1.235502e-50
Sexfemale               0.03540190 0.07094725  0.498989 6.184138e-01
mmalinfected           -0.16706938 0.06859201 -2.435697 1.586587e-02
Sexfemale:mmalinfected -0.01846687 0.10421307 -0.177203 8.595539e-01</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fb_int, <span class="at">test =</span> <span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: gaussian, link: identity

Response: OffBTL

Terms added sequentially (first to last)

         Df Deviance Resid. Df Resid. Dev       F    Pr(&gt;F)    
NULL                       178     22.086                      
Sex       1  0.01747       177     22.068  0.1477 0.7012309    
mmal      1  1.35984       176     20.709 11.4936 0.0008631 ***
Sex:mmal  1  0.00372       175     20.705  0.0314 0.8595539    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fb_add)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate Std. Error    t value     Pr(&gt;|t|)
(Intercept)   0.97678378 0.04086226 23.9043027 3.696272e-57
Sexfemale     0.02684296 0.05182413  0.5179626 6.051348e-01
mmalinfected -0.17506949 0.05149732 -3.3995842 8.349140e-04</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(fb_add, fb_int)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       df      AIC
fb_add  4 129.9060
fb_int  5 131.8739</code></pre>
</div>
</div>
<ol type="a">
<li>Which of the four groups is the <em>reference group</em> that the intercept of the interaction model refers to, and why that one? Reconstruct from the four coefficients of <code>fb_int</code> the fitted mean telomere length of (i) a male chick of a healthy mother, (ii) a female chick of a healthy mother, (iii) a male chick of an infected mother and (iv) a female chick of an infected mother. Compare your four numbers with the table of group means.</li>
<li>What does the coefficient <code>Sexfemale:mmalinfected</code> measure, in words? Judging from its estimate, its p-value and the interaction plot: do sex and mother’s infection status interact?</li>
<li>The <code>anova()</code> table tests the terms <em>sequentially</em>. Explain what the three rows test. Which term explains most of the deviance? What fraction of the total deviance (the <code>NULL</code> row) is explained by the full interaction model?</li>
<li>Which of the two models would you report, and why? Support your choice with the AIC values <em>and</em> with the F-test of the interaction. Then give the interpretation of the <code>mmalinfected</code> coefficient of the model you chose, including its uncertainty (estimate ± SE), in one sentence a biologist would understand.</li>
<li>In the additive model the <code>Sexfemale</code> coefficient is not significant. Is it allowed to remove <code>Sex</code> from the additive model? Is it allowed to remove <code>Sex</code> from the interaction model? Explain the difference.</li>
</ol>
</section>
<section id="exercise-2-a-continuous-and-a-categorical-predictor-ancova" class="level1">
<h1>Exercise 2 — A continuous and a categorical predictor (ANCOVA)</h1>
<p><code>regrowth</code> contains the fruit production (<code>Fruit</code>, mg) of 40 plants, their initial root diameter (<code>Root</code>, mm, measured <em>before</em> the treatment) and whether the plant was grazed by rabbits (<code>Grazing</code>: Grazed / Ungrazed).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fg_add <span class="ot">&lt;-</span> <span class="fu">glm</span>(Fruit <span class="sc">~</span> Root <span class="sc">+</span> Grazing, <span class="at">family =</span> gaussian, <span class="at">data =</span> regrowth)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Fruit <span class="sc">~</span> Grazing, <span class="at">data =</span> regrowth, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">ylab =</span> <span class="st">"fruit production (mg)"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Fruit <span class="sc">~</span> Root, <span class="at">data =</span> regrowth, <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">1</span>)[regrowth<span class="sc">$</span>Grazing], <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"initial root diameter (mm)"</span>, <span class="at">ylab =</span> <span class="st">"fruit production (mg)"</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>cf <span class="ot">&lt;-</span> <span class="fu">coef</span>(fg_add)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> cf[<span class="st">"(Intercept)"</span>], <span class="at">b =</span> cf[<span class="st">"Root"</span>], <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> cf[<span class="st">"(Intercept)"</span>] <span class="sc">+</span> cf[<span class="st">"GrazingUngrazed"</span>], <span class="at">b =</span> cf[<span class="st">"Root"</span>], <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">1</span>), <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Grazed"</span>, <span class="st">"Ungrazed"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_5_multiple_regression_files/figure-html/ex2-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Fruit production of grazed and ungrazed plants. Left: ignoring root size. Right: as a function of root size, with the fitted lines of the additive model <code>Fruit ~ Root + Grazing</code>.</figcaption>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(regrowth<span class="sc">$</span>Fruit, regrowth<span class="sc">$</span>Grazing, mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Grazed Ungrazed 
 67.9405  50.8805 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(regrowth<span class="sc">$</span>Root, regrowth<span class="sc">$</span>Grazing, mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Grazed Ungrazed 
  8.3094   6.0529 </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fg_add)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                  Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept)     -127.82936   9.664095 -13.22725 1.349804e-15
Root              23.56005   1.148771  20.50892 8.408231e-22
GrazingUngrazed   36.10325   3.357396  10.75335 6.107286e-13</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the same additive model, terms entered in two different orders</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">glm</span>(Fruit <span class="sc">~</span> Grazing <span class="sc">+</span> Root, <span class="at">family =</span> gaussian, <span class="at">data =</span> regrowth), <span class="at">test =</span> <span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: gaussian, link: identity

Response: Fruit

Terms added sequentially (first to last)

        Df Deviance Resid. Df Resid. Dev       F    Pr(&gt;F)    
NULL                       39    23743.8                      
Grazing  1   2910.4        38    20833.4  63.929 1.397e-09 ***
Root     1  19148.9        37     1684.5 420.616 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">glm</span>(Fruit <span class="sc">~</span> Root <span class="sc">+</span> Grazing, <span class="at">family =</span> gaussian, <span class="at">data =</span> regrowth), <span class="at">test =</span> <span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: gaussian, link: identity

Response: Fruit

Terms added sequentially (first to last)

        Df Deviance Resid. Df Resid. Dev      F    Pr(&gt;F)    
NULL                       39    23743.8                     
Root     1  16795.0        38     6948.8 368.91 &lt; 2.2e-16 ***
Grazing  1   5264.4        37     1684.5 115.63 6.107e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the model with interaction</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>fg_int <span class="ot">&lt;-</span> <span class="fu">glm</span>(Fruit <span class="sc">~</span> Root <span class="sc">*</span> Grazing, <span class="at">family =</span> gaussian, <span class="at">data =</span> regrowth)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fg_int)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                         Estimate Std. Error    t value     Pr(&gt;|t|)
(Intercept)          -125.1730569  12.811165 -9.7706222 1.150540e-11
Root                   23.2403732   1.530771 15.1821314 3.173208e-17
GrazingUngrazed        30.8057049  16.841823  1.8291194 7.567489e-02
Root:GrazingUngrazed    0.7560338   2.354111  0.3211547 7.499503e-01</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fg_add, fg_int, <span class="at">test =</span> <span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: Fruit ~ Root + Grazing
Model 2: Fruit ~ Root * Grazing
  Resid. Df Resid. Dev Df Deviance      F Pr(&gt;F)
1        37     1684.5                          
2        36     1679.7  1   4.8122 0.1031   0.75</code></pre>
</div>
</div>
<ol type="a">
<li>According to the boxplot, grazed plants produce <em>more</em> fruit than ungrazed plants (means 68 vs 51 mg). According to the coefficient <code>GrazingUngrazed</code> of the additive model, ungrazed plants produce <em>more</em> fruit. Both statements are based on the same data. Explain, using the right-hand figure and the mean root diameters per group, how this apparent contradiction arises and which of the two statements answers the question “does grazing reduce fruit production?”.</li>
<li>Write down the two fitted regression lines (one per grazing group) in the form <span class="math inline">\(\hat{y} = a + b \cdot \mathrm{Root}\)</span> from the coefficients of <code>fg_add</code>. What does the model assume about the two lines?</li>
<li>The two <code>anova()</code> tables are for the <em>same</em> model, but the deviance attributed to <code>Grazing</code> is 2910 in one and 5264 in the other. Explain why the order of the terms matters here (hint: are <code>Root</code> and <code>Grazing</code> independent in this data set?). Why does the <em>residual</em> deviance not depend on the order?</li>
<li>In the interaction model, what does the coefficient <code>Root:GrazingUngrazed</code> represent? Is there evidence that the effect of root size differs between grazed and ungrazed plants? Which model would you report?</li>
<li>Root diameter was measured before the grazing treatment. Why is that important for the interpretation in (a)? What would change in your interpretation if root diameter had been measured <em>after</em> grazing?</li>
</ol>
</section>
<section id="exercise-3-interaction-between-a-continuous-and-a-categorical-predictor" class="level1">
<h1>Exercise 3 — Interaction between a continuous and a categorical predictor</h1>
<p>We return to the <code>wells</code> data (Practicals 3 and 4b): the number of contaminated wells <code>y</code> out of <code>n</code> in 20 areas, with the nitrate concentration (<code>nitrate</code>, mg/l) and whether the area is sewered (<code>sewer</code>: yes/no). Because the data were overdispersed, a <strong>quasi-binomial</strong> model is used.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>fw_int <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(y, n <span class="sc">-</span> y) <span class="sc">~</span> nitrate <span class="sc">*</span> sewer, <span class="at">family =</span> quasibinomial, <span class="at">data =</span> wells)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>fw_add <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(y, n <span class="sc">-</span> y) <span class="sc">~</span> nitrate <span class="sc">+</span> sewer, <span class="at">family =</span> quasibinomial, <span class="at">data =</span> wells)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y <span class="sc">/</span> n <span class="sc">~</span> nitrate, <span class="at">data =</span> wells, <span class="at">cex =</span> <span class="fu">sqrt</span>(n) <span class="sc">/</span> <span class="dv">3</span>, <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">16</span>)[<span class="fu">factor</span>(sewer)], <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"nitrate (mg/l)"</span>, <span class="at">ylab =</span> <span class="st">"proportion of contaminated wells"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>xnew <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">8</span>, <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (s <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"no"</span>, <span class="st">"yes"</span>)) {</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  pr <span class="ot">&lt;-</span> <span class="fu">predict</span>(fw_int, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">nitrate =</span> xnew, <span class="at">sewer =</span> s), <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">matlines</span>(xnew, <span class="fu">plogis</span>(<span class="fu">cbind</span>(pr<span class="sc">$</span>fit, pr<span class="sc">$</span>fit <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> pr<span class="sc">$</span>se.fit, pr<span class="sc">$</span>fit <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> pr<span class="sc">$</span>se.fit)),</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>), <span class="at">col =</span> <span class="fu">ifelse</span>(s <span class="sc">==</span> <span class="st">"yes"</span>, <span class="st">"black"</span>, <span class="st">"grey50"</span>), <span class="at">lwd =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">1</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"grey50"</span>), <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"sewered"</span>, <span class="st">"unsewered"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_5_multiple_regression_files/figure-html/ex3-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Proportion of contaminated wells against nitrate concentration in sewered (filled) and unsewered (open) areas. Symbol size is proportional to the number of wells. Lines: fitted curves of the interaction model with 95 % confidence bands.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fw_int)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                    Estimate Std. Error    t value     Pr(&gt;|t|)
(Intercept)      -3.06888250  0.5983799 -5.1286522 0.0001010547
nitrate           0.06607054  0.1656261  0.3989139 0.6952302636
seweryes         -0.13285511  1.0104045 -0.1314871 0.8970292106
nitrate:seweryes  0.55407961  0.2539352  2.1819726 0.0443687501</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fw_int)<span class="sc">$</span>dispersion</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.109884</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fw_int, <span class="at">test =</span> <span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: quasibinomial, link: logit

Response: cbind(y, n - y)

Terms added sequentially (first to last)

              Df Deviance Resid. Df Resid. Dev       F    Pr(&gt;F)    
NULL                             19    146.956                      
nitrate        1   34.796        18    112.160 16.4918 0.0009079 ***
sewer          1   66.778        17     45.382 31.6502 3.792e-05 ***
nitrate:sewer  1   11.295        16     34.087  5.3532 0.0343083 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fw_add, fw_int, <span class="at">test =</span> <span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: cbind(y, n - y) ~ nitrate + sewer
Model 2: cbind(y, n - y) ~ nitrate * sewer
  Resid. Df Resid. Dev Df Deviance      F  Pr(&gt;F)  
1        17     45.382                             
2        16     34.087  1   11.295 5.3532 0.03431 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ol type="a">
<li>Write down the fitted model on the logit scale for unsewered areas and for sewered areas, each in the form <span class="math inline">\(\mathrm{logit}(p) = a + b \cdot \mathrm{nitrate}\)</span>, using the four coefficients.</li>
<li>Calculate by hand (calculator) the fitted probability of contamination at a nitrate concentration of 4 mg/l in an unsewered and in a sewered area. Recall that <span class="math inline">\(p = e^{\eta} / (1 + e^{\eta})\)</span>.</li>
<li>The <code>nitrate</code> main effect has <span class="math inline">\(p = 0.70\)</span> and the <code>seweryes</code> main effect has <span class="math inline">\(p = 0.90\)</span>, yet the interaction is significant. Explain what the two non-significant main effects mean in this model (what exactly do they test?) and why they must nevertheless stay in the model.</li>
<li>Describe the interaction in words for a report on groundwater quality: what is the effect of nitrate in unsewered areas, what is it in sewered areas, and what does this suggest about the <em>source</em> of the contamination? Use the figure.</li>
<li>The <code>anova()</code> comparison of the additive and the interaction model gives <span class="math inline">\(F = 5.35\)</span>, <span class="math inline">\(p = 0.034\)</span>. Why is an F-test used here rather than a <span class="math inline">\(\chi^2\)</span> test? What would have happened to this p-value if the ordinary binomial family had been used (think back to Practical 4b, Exercise 2)?</li>
</ol>
</section>
<section id="exercise-4-interaction-and-model-simplification-with-a-negative-binomial-glm" class="level1">
<h1>Exercise 4 — Interaction and model simplification with a negative binomial GLM</h1>
<p>In Practical 4b we found that macro-fauna richness (<code>RIKZdat</code>) depends on tidal height <code>NAP</code> and that the residuals also showed an effect of beach <code>exposure</code> (three levels: 8, 10, 11). Four negative binomial models were fitted:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>RIKZdat<span class="sc">$</span>exposure <span class="ot">&lt;-</span> <span class="fu">factor</span>(RIKZdat<span class="sc">$</span>exposure)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>fr_nap <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Richness <span class="sc">~</span> NAP, <span class="at">data =</span> RIKZdat)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>fr_exp <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Richness <span class="sc">~</span> exposure, <span class="at">data =</span> RIKZdat)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>fr_add <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Richness <span class="sc">~</span> NAP <span class="sc">+</span> exposure, <span class="at">data =</span> RIKZdat)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>fr_int <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Richness <span class="sc">~</span> NAP <span class="sc">*</span> exposure, <span class="at">data =</span> RIKZdat)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fr_int)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                 Estimate Std. Error    z value     Pr(&gt;|z|)
(Intercept)     2.5485423  0.1684491 15.1294499 1.035574e-51
NAP            -0.3239406  0.1776522 -1.8234538 6.823469e-02
exposure10     -0.6323736  0.1987119 -3.1823645 1.460778e-03
exposure11     -1.3537393  0.2198968 -6.1562468 7.448912e-10
NAP:exposure10 -0.3383220  0.2142170 -1.5793423 1.142576e-01
NAP:exposure11 -0.2435137  0.2437588 -0.9989945 3.177974e-01</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fr_add, fr_int)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of Negative Binomial Models

Response: Richness
           Model    theta Resid. df    2 x log-lik.   Test    df LR stat.
1 NAP + exposure 15.25376        41       -196.0406                      
2 NAP * exposure 18.25390        39       -193.7610 1 vs 2     2 2.279608
    Pr(Chi)
1          
2 0.3198817</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(fr_nap, fr_exp, fr_add, fr_int)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       df      AIC
fr_nap  3 231.7456
fr_exp  4 239.2391
fr_add  5 206.0406
fr_int  7 207.7610</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fr_add)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error   z value     Pr(&gt;|z|)
(Intercept)  2.5831487 0.17500217 14.760667 2.626718e-49
NAP         -0.5690938 0.08565631 -6.643921 3.054464e-11
exposure10  -0.6577734 0.20502891 -3.208198 1.335693e-03
exposure11  -1.3882048 0.22636325 -6.132642 8.643143e-10</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"8"</span> <span class="ot">=</span> <span class="st">"firebrick"</span>, <span class="st">"10"</span> <span class="ot">=</span> <span class="st">"steelblue"</span>, <span class="st">"11"</span> <span class="ot">=</span> <span class="st">"grey30"</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>nap_new <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(RIKZdat<span class="sc">$</span>NAP), <span class="fu">max</span>(RIKZdat<span class="sc">$</span>NAP), <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (m <span class="cf">in</span> <span class="fu">list</span>(fr_add, fr_int)) {</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(Richness <span class="sc">~</span> NAP, <span class="at">data =</span> RIKZdat, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> cols[<span class="fu">as.character</span>(exposure)], <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"NAP (m)"</span>, <span class="at">ylab =</span> <span class="st">"species richness"</span>, <span class="at">log =</span> <span class="st">"y"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="dv">25</span>))</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (e <span class="cf">in</span> <span class="fu">levels</span>(RIKZdat<span class="sc">$</span>exposure)) {</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">lines</span>(nap_new, <span class="fu">predict</span>(m, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">NAP =</span> nap_new, <span class="at">exposure =</span> e), <span class="at">type =</span> <span class="st">"response"</span>),</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">col =</span> cols[e], <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">col =</span> cols, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">legend =</span> <span class="fu">paste</span>(<span class="st">"exposure"</span>, <span class="fu">names</span>(cols)))</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_5_multiple_regression_files/figure-html/ex4-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Species richness against NAP for the three exposure classes. Left: additive model (parallel lines on the log scale). Right: interaction model (separate slopes).</figcaption>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<ol type="a">
<li>In the interaction model, which combination of NAP and exposure does the intercept refer to? Write down the slope of <code>NAP</code> (on the log scale) for each of the three exposure classes as a sum of coefficients.</li>
<li>Is the interaction needed? Answer using the likelihood-ratio test in <code>anova(fr_add, fr_int)</code> and the AIC table. Why does the test have 2 degrees of freedom?</li>
<li>The AIC table contains four models. Rank them and state the AIC difference between the best and each of the others. Which of the two single-predictor models is better, and how does that compare with the conclusion from Practical 4b where only <code>NAP</code> was used?</li>
<li>Use the coefficients of the additive model to describe the effect of exposure: by which <em>factor</em> does the expected richness differ between exposure 8 and exposure 11 at a given NAP? And by which factor does richness change per metre of NAP? (You need <code>exp()</code>; a calculator will do.)</li>
<li>Why is the y-axis of the figure drawn on a log scale, and what property of the additive model becomes visible in that representation that would be hidden on a linear axis?</li>
</ol>
</section>
<section id="exercise-5-collinearity" class="level1">
<h1>Exercise 5 — Collinearity</h1>
<p>For the Galápagos islands (<code>gala</code>) several possible predictors of plant species richness are available: island area, elevation, distance to the nearest island and area of the adjacent island. All four are strongly right-skewed and have been log-transformed. Before fitting a multiple regression, we check how the predictors are related to each other.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> gala</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>g<span class="sc">$</span>lArea <span class="ot">&lt;-</span> <span class="fu">log</span>(g<span class="sc">$</span>Area); g<span class="sc">$</span>lElev <span class="ot">&lt;-</span> <span class="fu">log</span>(g<span class="sc">$</span>Elevation)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>g<span class="sc">$</span>lNear <span class="ot">&lt;-</span> <span class="fu">log</span>(g<span class="sc">$</span>Nearest.dist); g<span class="sc">$</span>lAdj <span class="ot">&lt;-</span> <span class="fu">log</span>(g<span class="sc">$</span>Adjacent.isl.area)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(g[, <span class="fu">c</span>(<span class="st">"lArea"</span>, <span class="st">"lElev"</span>, <span class="st">"lNear"</span>, <span class="st">"lAdj"</span>)], <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="st">"grey40"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_5_multiple_regression_files/figure-html/ex5-cor-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Pairwise scatter plots of the four log-transformed predictors for the Galápagos data.</figcaption>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(g[, <span class="fu">c</span>(<span class="st">"lArea"</span>, <span class="st">"lElev"</span>, <span class="st">"lNear"</span>, <span class="st">"lAdj"</span>)]), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      lArea lElev lNear  lAdj
lArea  1.00  0.83  0.10  0.15
lElev  0.83  1.00  0.20 -0.01
lNear  0.10  0.20  1.00 -0.09
lAdj   0.15 -0.01 -0.09  1.00</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>m_area <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Species <span class="sc">~</span> lArea, <span class="at">data =</span> g)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>m_elev <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Species <span class="sc">~</span> lElev, <span class="at">data =</span> g)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>m_both <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Species <span class="sc">~</span> lArea <span class="sc">+</span> lElev, <span class="at">data =</span> g)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>m_all  <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Species <span class="sc">~</span> lArea <span class="sc">+</span> lElev <span class="sc">+</span> lNear <span class="sc">+</span> lAdj, <span class="at">data =</span> g)</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(m_area)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)    3.150      0.140  22.440        0
lArea          0.367      0.036  10.204        0</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(m_elev)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)    0.051      0.683   0.075     0.94
lElev          0.761      0.127   5.986     0.00</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(m_both)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)    3.449      0.773   4.461    0.000
lArea          0.389      0.065   5.962    0.000
lElev         -0.065      0.165  -0.396    0.692</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(m_all)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)    3.326      0.769   4.326    0.000
lArea          0.375      0.064   5.854    0.000
lElev          0.001      0.164   0.005    0.996
lNear         -0.130      0.072  -1.801    0.072
lAdj          -0.030      0.036  -0.827    0.408</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(m_all)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   lArea    lElev    lNear     lAdj 
3.571490 3.585532 1.053126 1.066036 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(m_area, m_elev, m_both, m_all)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       df      AIC
m_area  3 273.9926
m_elev  3 294.3806
m_both  4 275.8631
m_all   6 276.6726</code></pre>
</div>
</div>
<ol type="a">
<li>Which pair of predictors is collinear according to Dormann’s rule of thumb? Give a physical reason why these two variables are so strongly correlated on the Galápagos.</li>
<li>On its own, <code>lElev</code> is a highly significant predictor (<span class="math inline">\(z = 6.0\)</span>). In the model with both <code>lArea</code> and <code>lElev</code>, its coefficient is <span class="math inline">\(-0.07\)</span> with <span class="math inline">\(p = 0.69\)</span>. Explain what happened. Does this mean that elevation has no effect on species richness?</li>
<li>Compare the standard error of <code>lArea</code> in <code>m_area</code> with that in <code>m_both</code>. By what factor did it increase? Relate this to the variance inflation factors: what does a VIF of 3.6 mean, and would Dormann consider it a problem?</li>
<li>Which of the four models would you choose as the final model, and on what grounds (AIC, parsimony, interpretability)? Formulate a sentence for the discussion section of a paper that honestly states what the data can and cannot tell us about the roles of area and elevation.</li>
<li>Suppose a colleague argues: “Elevation is biologically the more relevant variable, because higher islands have more habitat types, so we should keep elevation and drop area.” Can the data decide this argument? What kind of data <em>could</em>?</li>
</ol>
</section>
<section id="exercise-6-two-continuous-predictors-and-their-interaction" class="level1">
<h1>Exercise 6 — Two continuous predictors and their interaction</h1>
<p><code>loyn</code> contains the abundance of forest birds (<code>ABUND</code>, birds per 20-minute census) in 56 forest fragments in Victoria, Australia, together with the fragment area (<code>AREA</code>, ha, log10-transformed below), the grazing intensity (<code>GRAZE</code>, index 1 = light to 5 = heavy) and several other variables. Here we look at area and grazing together, treating grazing as a continuous predictor.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>loyn<span class="sc">$</span>lAREA <span class="ot">&lt;-</span> <span class="fu">log10</span>(loyn<span class="sc">$</span>AREA)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>fl_add <span class="ot">&lt;-</span> <span class="fu">lm</span>(ABUND <span class="sc">~</span> lAREA <span class="sc">+</span> GRAZE, <span class="at">data =</span> loyn)</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>fl_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(ABUND <span class="sc">~</span> lAREA <span class="sc">*</span> GRAZE, <span class="at">data =</span> loyn)</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fl_add)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)   21.603      3.092   6.987        0
lAREA          6.890      1.290   5.341        0
GRAZE         -2.854      0.713  -4.005        0</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fl_int)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)   26.558      3.358   7.910    0.000
lAREA          2.112      2.038   1.037    0.305
GRAZE         -4.547      0.885  -5.138    0.000
lAREA:GRAZE    2.142      0.736   2.911    0.005</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fl_add, fl_int)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: ABUND ~ lAREA + GRAZE
Model 2: ABUND ~ lAREA * GRAZE
  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
1     53 2200.9                                
2     52 1892.5  1    308.49 8.4766 0.005287 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>area_seq  <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(loyn<span class="sc">$</span>lAREA), <span class="fu">max</span>(loyn<span class="sc">$</span>lAREA), <span class="at">length =</span> <span class="dv">50</span>)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>graze_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="at">length =</span> <span class="dv">50</span>)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">outer</span>(area_seq, graze_seq,</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>           <span class="cf">function</span>(a, gr) <span class="fu">predict</span>(fl_int, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">lAREA =</span> a, <span class="at">GRAZE =</span> gr)))</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="fu">image</span>(area_seq, graze_seq, z, <span class="at">col =</span> <span class="fu">hcl.colors</span>(<span class="dv">50</span>, <span class="st">"YlGnBu"</span>, <span class="at">rev =</span> <span class="cn">TRUE</span>), <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">xlab =</span> <span class="st">"log10(area) (ha)"</span>, <span class="at">ylab =</span> <span class="st">"grazing intensity"</span>)</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a><span class="fu">contour</span>(area_seq, graze_seq, z, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">labcex =</span> <span class="fl">0.9</span>)</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(loyn<span class="sc">$</span>lAREA, loyn<span class="sc">$</span>GRAZE, <span class="at">pch =</span> <span class="dv">3</span>)</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>ch <span class="ot">&lt;-</span> <span class="fu">chull</span>(<span class="fu">cbind</span>(loyn<span class="sc">$</span>lAREA, loyn<span class="sc">$</span>GRAZE))</span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">cbind</span>(loyn<span class="sc">$</span>lAREA, loyn<span class="sc">$</span>GRAZE)[ch, ], <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_5_multiple_regression_files/figure-html/ex6-surface-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Fitted bird abundance as a function of log10(area) and grazing intensity for the interaction model, shown as a colour image with contour lines. The crosses are the observed combinations of the two predictors; the polygon is their convex hull.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ABUND <span class="sc">~</span> lAREA, <span class="at">data =</span> loyn, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="fu">grey</span>(<span class="dv">1</span> <span class="sc">-</span> loyn<span class="sc">$</span>GRAZE <span class="sc">/</span> <span class="dv">6</span>), <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"log10(area) (ha)"</span>, <span class="at">ylab =</span> <span class="st">"bird abundance"</span>)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (gr <span class="cf">in</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>)) {</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(area_seq, <span class="fu">predict</span>(fl_int, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">lAREA =</span> area_seq, <span class="at">GRAZE =</span> gr)),</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="fu">grey</span>(<span class="dv">1</span> <span class="sc">-</span> gr <span class="sc">/</span> <span class="dv">6</span>))</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="fu">grey</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>) <span class="sc">/</span> <span class="dv">6</span>),</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"grazing 1"</span>, <span class="st">"grazing 3"</span>, <span class="st">"grazing 5"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="QSBS_5_multiple_regression_files/figure-html/ex6-slopes-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>The same interaction model as lines: fitted abundance against log10(area) for grazing intensity 1, 3 and 5. Points are coloured by grazing class (light = light grazing).</figcaption>
</figure>
</div>
</div>
</div>
<ol type="a">
<li>In the additive model, what is the interpretation of the <code>lAREA</code> coefficient (6.89) and of the <code>GRAZE</code> coefficient (<span class="math inline">\(-2.85\)</span>)? Pay attention to the units: what does “one unit of <code>lAREA</code>” mean for the actual area?</li>
<li>In the interaction model the <code>lAREA</code> main effect is 2.11 with <span class="math inline">\(p = 0.30\)</span>. Does this mean that area has no effect on bird abundance? What exactly does this coefficient represent in the presence of the interaction (hint: at what grazing intensity is it the slope — and does that value occur in the data)?</li>
<li>Use the coefficients to calculate the slope of abundance against <code>lAREA</code> at grazing intensity 1 and at grazing intensity 5. Describe the interaction in words: is it synergistic or antagonistic (Dormann, Sect. 15.2)?</li>
<li>Look at the image/contour plot. Where in the predictor space are the fitted values highest, and where lowest? Which corner(s) of the plot contain no data, and why should you refrain from interpreting the model there?</li>
<li>Dormann (Sect. 15.2, footnote 4) warns that a significant interaction can be an artefact of an unmodelled <em>non-linear</em> effect of one of the predictors. Suggest how you would check this for the present model (which alternative model would you compare it with?).</li>
</ol>
</section>
<section id="exercise-7-model-selection" class="level1">
<h1>Exercise 7 — Model selection</h1>
<p>We now use all predictors in <code>loyn</code> to explain bird abundance: <code>lAREA</code>, <code>lDIST</code> (log10 distance to the nearest fragment), <code>lLDIST</code> (log10 distance to the nearest <em>larger</em> fragment), <code>YR.ISOL</code> (year of isolation), <code>GRAZE</code> and <code>ALT</code> (altitude). A model with only main effects was fitted and simplified in three ways: backward stepwise selection by AIC, backward stepwise selection by BIC, and best-subset selection (all 64 sub-models) ranked by AIC.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>loyn<span class="sc">$</span>lDIST  <span class="ot">&lt;-</span> <span class="fu">log10</span>(loyn<span class="sc">$</span>DIST)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>loyn<span class="sc">$</span>lLDIST <span class="ot">&lt;-</span> <span class="fu">log10</span>(loyn<span class="sc">$</span>LDIST)</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(loyn[, <span class="fu">c</span>(<span class="st">"lAREA"</span>, <span class="st">"lDIST"</span>, <span class="st">"lLDIST"</span>, <span class="st">"YR.ISOL"</span>, <span class="st">"GRAZE"</span>, <span class="st">"ALT"</span>)]), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        lAREA lDIST lLDIST YR.ISOL GRAZE   ALT
lAREA    1.00  0.30   0.38    0.28 -0.56  0.28
lDIST    0.30  1.00   0.60   -0.02 -0.14 -0.22
lLDIST   0.38  0.60   1.00   -0.16 -0.03 -0.27
YR.ISOL  0.28 -0.02  -0.16    1.00 -0.64  0.23
GRAZE   -0.56 -0.14  -0.03   -0.64  1.00 -0.41
ALT      0.28 -0.22  -0.27    0.23 -0.41  1.00</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>fl_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(ABUND <span class="sc">~</span> lAREA <span class="sc">+</span> lDIST <span class="sc">+</span> lLDIST <span class="sc">+</span> YR.ISOL <span class="sc">+</span> GRAZE <span class="sc">+</span> ALT, <span class="at">data =</span> loyn,</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">na.action =</span> na.fail)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fl_full)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -125.697     91.692  -1.371    0.177
lAREA          7.470      1.465   5.099    0.000
lDIST         -0.907      2.676  -0.339    0.736
lLDIST        -0.648      2.123  -0.305    0.761
YR.ISOL        0.074      0.045   1.634    0.109
GRAZE         -1.668      0.930  -1.793    0.079
ALT            0.020      0.024   0.814    0.419</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">vif</span>(fl_full), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  lAREA   lDIST  lLDIST YR.ISOL   GRAZE     ALT 
   1.91    1.65    2.01    1.80    2.52    1.47 </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>fl_stepAIC <span class="ot">&lt;-</span> <span class="fu">step</span>(fl_full, <span class="at">trace =</span> <span class="dv">0</span>)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>fl_stepBIC <span class="ot">&lt;-</span> <span class="fu">step</span>(fl_full, <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">nrow</span>(loyn)), <span class="at">trace =</span> <span class="dv">0</span>)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="fu">formula</span>(fl_stepAIC)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>ABUND ~ lAREA + YR.ISOL + GRAZE</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">formula</span>(fl_stepBIC)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>ABUND ~ lAREA + GRAZE</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># one step of the BIC selection, shown in full</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(fl_full, <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">nrow</span>(loyn)), <span class="at">steps =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=228.32
ABUND ~ lAREA + lDIST + lLDIST + YR.ISOL + GRAZE + ALT

          Df Sum of Sq    RSS    AIC
- lLDIST   1      3.80 2000.7 224.40
- lDIST    1      4.68 2001.5 224.43
- ALT      1     27.02 2023.9 225.05
- YR.ISOL  1    108.83 2105.7 227.27
- GRAZE    1    131.07 2127.9 227.85
&lt;none&gt;                 1996.8 228.32
- lAREA    1   1059.75 3056.6 248.14

Step:  AIC=224.4
ABUND ~ lAREA + lDIST + YR.ISOL + GRAZE + ALT</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ABUND ~ lAREA + lDIST + YR.ISOL + GRAZE + ALT, data = loyn, 
    na.action = na.fail)

Coefficients:
(Intercept)        lAREA        lDIST      YR.ISOL        GRAZE          ALT  
 -131.84739      7.29529     -1.30325      0.07658     -1.67573      0.02145  </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>dm <span class="ot">&lt;-</span> <span class="fu">dredge</span>(fl_full, <span class="at">rank =</span> <span class="st">"AIC"</span>)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">subset</span>(dm, delta <span class="sc">&lt;</span> <span class="dv">2</span>), <span class="at">abbrev.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Global model call: lm(formula = ABUND ~ lAREA + lDIST + lLDIST + YR.ISOL + GRAZE + 
    ALT, data = loyn, na.action = na.fail)
---
Model selection table 
   (Intercept)     ALT  GRAZE lAREA  lDIST lLDIST YR.ISOL df   logLik   AIC
39     -134.30         -1.902 7.166               0.07835  5 -180.555 371.1
40     -141.90 0.02586 -1.601 7.076               0.07991  6 -179.761 371.5
55     -113.40         -1.842 7.751        -1.646 0.06941  6 -180.036 372.1
47     -120.50         -1.939 7.487 -2.048        0.07354  6 -180.072 372.1
7        21.60         -2.854 6.890                        4 -182.257 372.5
23       25.74         -2.630 7.709        -2.190          5 -181.347 372.7
38     -236.70 0.03623        8.150               0.12480  5 -181.428 372.9
   delta weight
39  0.00  0.228
40  0.41  0.185
55  0.96  0.141
47  1.04  0.136
7   1.40  0.113
23  1.59  0.103
38  1.75  0.095
Models ranked by AIC(x) </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(fl_full, fl_stepAIC, fl_stepBIC)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>           df      AIC
fl_full     8 375.0638
fl_stepAIC  5 371.1092
fl_stepBIC  4 372.5134</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(fl_full, fl_stepAIC, fl_stepBIC)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>           df      BIC
fl_full     8 391.2666
fl_stepAIC  5 381.2360
fl_stepBIC  4 380.6148</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(fl_stepAIC)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -134.261     86.391  -1.554    0.126
lAREA          7.166      1.273   5.631    0.000
YR.ISOL        0.078      0.043   1.805    0.077
GRAZE         -1.902      0.874  -2.175    0.034</code></pre>
</div>
</div>
<ol type="a">
<li>Look at the correlation matrix and the VIFs of the full model. Is collinearity a problem here? Which pair of predictors is most strongly correlated, and is it a problem that they are both in the model?</li>
<li>In the full model only <code>lAREA</code> is significant, yet the model explains 68 % of the variance. Explain why a model can be highly significant as a whole while most of its individual coefficients are not (think of what a coefficient’s p-value tests when other, correlated predictors are in the model).</li>
<li>Read the displayed first step of the BIC selection. Explain the meaning of the rows: what does <code>&lt;none&gt;</code> represent, what does the row <code>- lLDIST</code> represent, and why is <code>- lAREA</code> at the bottom? Which term is removed in this step, and why?</li>
<li>Stepwise AIC ends with <code>lAREA + YR.ISOL + GRAZE</code>, stepwise BIC with <code>lAREA + GRAZE</code>. Explain why BIC leads to a smaller model. Which criterion would you use with 56 observations?</li>
<li>In the best-subset table, seven models lie within 2 AIC units of the best one. What does the column <code>weight</code> mean? What does it tell you that the best model has a weight of only 0.23? Which predictor appears in <em>all</em> seven models, which ones in most of them, and which ones only occasionally? What would you conclude about their importance?</li>
<li>Given everything above, formulate your final model and justify it in three or four sentences. Then note one caveat about the p-values of a model that was chosen by model selection.</li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>