<!DOCTYPE html>
<html lang="en"><head>
<script src="presentation3_regression_files/libs/clipboard/clipboard.min.js"></script>
<script src="presentation3_regression_files/libs/quarto-html/tabby.min.js"></script>
<script src="presentation3_regression_files/libs/quarto-html/popper.min.js"></script>
<script src="presentation3_regression_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="presentation3_regression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="presentation3_regression_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="presentation3_regression_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Emiel van Loon">
  <meta name="dcterms.date" content="2026-09-15">
  <title>Regression: Generalised Linear Models</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="presentation3_regression_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="presentation3_regression_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="presentation3_regression_files/libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link href="presentation3_regression_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="presentation3_regression_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="presentation3_regression_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="presentation3_regression_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Regression: Generalised Linear Models</h1>
  <p class="subtitle">Dormann (2020), <em>Environmental Data Analysis</em> — Chapters 7 and 8</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Emiel van Loon 
</div>
</div>
</div>

  <p class="date">2026-09-15</p>
</section>
<section class="slide level2">

<style>
.reveal .fignote { font-size: 0.60em; line-height: 1.35; }
.reveal .fignote code { font-size: 0.95em; }
.reveal pre code { font-size: 0.80em; line-height: 1.25; }
.reveal .smallout pre code { font-size: 0.60em; line-height: 1.2; }
.reveal .smallout table { font-size: 0.70em; }
</style>
</section>
<section id="where-we-are-going" class="slide level2 smaller">
<h2>Where we are going</h2>
<p>In practical 2 we fitted <strong>one</strong> distribution to a whole sample. Now a parameter of that distribution is allowed to <strong>depend on a predictor</strong>. That is all a regression is.</p>
<p>At the end of this chapter you should…</p>
<ul>
<li>see a regression as <em>y</em> ~ <em>x</em>: a response drawn from a distribution whose parameter is a function of the predictor</li>
<li>understand why the fit is done on the <strong>link scale</strong>, and be able to move between link scale and response scale (<code>exp()</code>, <code>plogis()</code>)</li>
<li>read the output of <code>summary(glm(...))</code>: coefficients, standard errors, deviances, dispersion, AIC</li>
<li>draw a regression line <strong>with its 95 % confidence band</strong></li>
<li>know how a <strong>factor</strong> is turned into dummy variables, and that the <em>t</em>-test and the χ²-test are just GLMs</li>
<li>fit a regression <strong>by hand</strong> with a likelihood function and <code>optim()</code> — for non-linear curves and for parameters other than the mean</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Illustrations use Dormann’s own examples: collared flycatchers, cherry <code>trees</code>, a bioassay, heights, smokers, Michaelis–Menten kinetics (<code>vmkm</code>) and hyena offspring. The practical uses data from the <code>qsbsdata</code> package.</p>
</div>
</div>
</div>
</section>
<section id="from-one-distribution-to-a-regression" class="slide level2">
<h2>From one distribution to a regression</h2>

<img data-src="presentation3_regression_files/figure-revealjs/one-to-regr-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>25 male collared flycatchers (<em>Ficedula albicollis</em>): food items delivered to the nest per hour, and an “attractiveness” score of their plumage (1–5). Left: ignoring attractiveness, one Poisson with λ = 7.0 fits the counts. Right: the group means (red crosses: 4.6, 6.8, 6.0, 8.6, 8.8) rise with attractiveness — the mean is a <strong>function of the predictor</strong>. Attractive males are better fathers.</p>
</div>
</section>
<section id="every-data-point-is-a-draw-from-its-own-distribution" class="slide level2">
<h2>Every data point is a draw from its own distribution</h2>

<img data-src="presentation3_regression_files/figure-revealjs/fig72-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>Dormann’s Fig. 7.2. We write <strong>pieces ~ Pois(λ = f(attractiveness))</strong>: every observation is a random draw from a Poisson distribution, but <em>which</em> Poisson depends on <em>x</em>. For an unattractive male we expect 4–5 items but 10 is still plausible; for the most attractive males the distribution has shifted right and become more symmetric. This is the whole idea of regression — the rest is technique.</p>
</div>
</section>
<section id="fitting-it-is-maximum-likelihood-again" class="slide level2">
<h2>Fitting it is maximum likelihood, again</h2>

<img data-src="presentation3_regression_files/figure-revealjs/ml-again-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>Same recipe as last week. For a candidate line, every point gets its own λ<sub>i</sub> = <em>a</em> + <em>b</em>·<em>x<sub>i</sub></em>; <code>dpois(y_i, lambda_i, log = TRUE)</code> gives the log-probability of that observation; sum over all 25 birds. Then search for the (<em>a</em>, <em>b</em>) that make the sum largest. Two parameters instead of one, so there is usually no formula — the computer searches. No least squares needed: this framework works for <strong>any</strong> distribution.</p>
</div>
</section>
<section id="the-flaw-of-a-straight-line-and-the-link-function" class="slide level2">
<h2>The flaw of a straight line — and the link function</h2>

<img data-src="presentation3_regression_files/figure-revealjs/link-why-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>Dormann’s Fig. 7.3, extended to the left. The straight (grey) line crosses zero at <em>x</em> = −3.74 (blue cross); beyond it the model predicts a <em>negative</em> number of food items, which a Poisson distribution cannot produce — R would refuse to fit. Harmless here (attractiveness is never negative), fatal for predictors that can be. The fix: fit the straight line on a <strong>transformed scale</strong> — for the Poisson, the logarithm — so that ln λ = <em>a</em> + <em>b</em>·<em>x</em>, and λ = e<sup><em>a</em>+<em>b</em>·<em>x</em></sup> is positive for every <em>x</em>. Within the data the two curves barely differ.</p>
</div>
</section>
<section id="four-link-functions" class="slide level2 smaller">
<h2>Four link functions</h2>

<img data-src="presentation3_regression_files/figure-revealjs/fig74-1.png" width="1350" class="r-stretch"><table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>distribution</th>
<th>data look like</th>
<th>link</th>
<th>fit on the link scale</th>
<th>back to the response scale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>normal</td>
<td>measurements</td>
<td>identity</td>
<td>μ = <em>a</em> + <em>b</em> <em>x</em></td>
<td>nothing to do</td>
</tr>
<tr class="even">
<td>Poisson, neg. binomial</td>
<td>counts ≥ 0</td>
<td>log</td>
<td>ln λ = <em>a</em> + <em>b</em> <em>x</em></td>
<td><code>exp()</code></td>
</tr>
<tr class="odd">
<td>binomial</td>
<td><em>k</em> out of <em>n</em>, 0/1</td>
<td>logit</td>
<td>ln [<em>p</em>/(1−<em>p</em>)] = <em>a</em> + <em>b</em> <em>x</em></td>
<td><code>plogis()</code></td>
</tr>
<tr class="even">
<td>gamma</td>
<td>positive, skewed</td>
<td>inverse</td>
<td>1/μ = <em>a</em> + <em>b</em> <em>x</em></td>
<td><code>1/x</code></td>
</tr>
</tbody>
</table>
<div class="fignote">
<p>Dormann’s Fig. 7.4 and Table 7.1. The link function transforms the <strong>relationship</strong>, not the data: a straight line on the link scale becomes an exponential (log), a sigmoid (logit) or a hyperbola (inverse) on the response scale. A regression that is linear on the link scale and lets you choose the distribution is a <strong>generalised linear model (GLM)</strong>. The inverse link is the confusing one: larger coefficients mean <em>smaller</em> fitted values.</p>
</div>
</section>
<section id="response-scale-or-link-scale" class="slide level2">
<h2>Response scale or link scale?</h2>

<img data-src="presentation3_regression_files/figure-revealjs/fig75-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>Dormann’s Fig. 7.5. With a logarithmic <em>y</em>-axis the log-link model (red) becomes the straight line it really is, and the identity-link line (grey) becomes a curve. The response scale is where the data were collected — show it in a report. The link scale shows the <em>form of the fitted model</em> — show it to a statistician. “Linear” in <em>generalised linear model</em> refers to the link scale: additive terms in the parameters (even <em>x</em>² is allowed).</p>
</div>
</section>
<section id="reading-summaryglm-the-cherry-trees" class="slide level2">
<h2>Reading <code>summary(glm())</code>: the cherry trees</h2>
<div class="smallout">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a>fm <span class="ot">&lt;-</span> <span class="fu">glm</span>(Volume <span class="sc">~</span> Girth, <span class="at">data =</span> trees, <span class="at">family =</span> gaussian)</span>
<span id="cb1-2"><a href=""></a><span class="fu">summary</span>(fm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Volume ~ Girth, family = gaussian, data = trees)

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -36.9435     3.3651  -10.98 7.62e-12 ***
Girth         5.0659     0.2474   20.48  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 18.0794)

    Null deviance: 8106.1  on 30  degrees of freedom
Residual deviance:  524.3  on 29  degrees of freedom
AIC: 181.64

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
</div>
<div class="fignote">
<p>31 black cherry trees: <code>Volume ~ N(μ = a + b·Girth, σ)</code>. <strong>Estimate</strong>: intercept and slope (here identity link, so directly in cubic feet per inch). <strong>Std. Error</strong> and a <em>t</em>-test whether each differs from 0. <strong>Dispersion</strong> 18.08 = σ² (so σ = 4.25). <strong>Null deviance</strong>: variability without predictor; <strong>residual deviance</strong>: what is left — the model explains (8106 − 524)/8106 = <strong>94 %</strong>. <strong>AIC</strong> for comparing models on the same data.</p>
</div>
</section>
<section id="drawing-the-line-and-its-uncertainty" class="slide level2">
<h2>Drawing the line — and its uncertainty</h2>

<img data-src="presentation3_regression_files/figure-revealjs/trees-ci-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>Dormann’s three-step recipe: (1) <code>seq()</code> of new <em>x</em> values over the observed range — never beyond it; (2) <code>predict(fm, newdata = ..., se.fit = TRUE)</code>; (3) <code>lines()</code> for the fit and for fit ± 2 SE. The blue band says where the <strong>true line</strong> lies in 95 % of repeated samples — it is <em>not</em> where new data points will fall; for that you must add the scatter σ of the distribution (green, the <em>prediction</em> interval).</p>
</div>
</section>
<section id="proportions-the-binomial-glm" class="slide level2">
<h2>Proportions: the binomial GLM</h2>

<img data-src="presentation3_regression_files/figure-revealjs/bioassay-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>Bioassay (Dormann, Sect. 8.1): water fleas in 15 dilutions of a substance, <em>y</em> survivors out of <em>n</em>. Model: <code>cbind(alive, dead) ~ S, family = binomial</code> — the response is a <strong>two-column matrix</strong>, so the GLM knows that 20 of 20 carries more weight than 1 of 1 (point size ∝ <em>n</em>). Coefficients on the logit scale: intercept 5.70, slope −2.31 per mg/l. <code>dose.p()</code> (package <code>MASS</code>) returns the concentration at which half survive.</p>
</div>
</section>
<section id="link-scale-response-scale" class="slide level2 smaller">
<h2>Link scale ⇄ response scale</h2>
<p>The coefficients in <code>summary()</code> live on the <strong>link scale</strong>. To say something in the units of the data, back-transform:</p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>example</th>
<th>coefficient (link scale)</th>
<th>back-transformed</th>
<th>in words</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>flycatchers, log link</td>
<td>intercept 1.47</td>
<td>e<sup>1.47</sup> = 4.4</td>
<td>expected items at attractiveness 0</td>
</tr>
<tr class="even">
<td></td>
<td>slope 0.148</td>
<td>e<sup>0.148</sup> = 1.16</td>
<td>every step in attractiveness <strong>multiplies</strong> λ by 1.16</td>
</tr>
<tr class="odd">
<td>bioassay, logit link</td>
<td>intercept 5.70</td>
<td><code>plogis(5.70)</code> = 0.997</td>
<td>survival probability at [S] = 0</td>
</tr>
<tr class="even">
<td></td>
<td>slope −2.31</td>
<td>e<sup>−2.31</sup> = 0.10</td>
<td>every mg/l multiplies the <strong>odds</strong> of survival by 0.10</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>The same applies to predictions and confidence bands: <code>predict()</code> works on the link scale, so <strong>add ± 2 SE first, back-transform afterwards</strong>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a>pr <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">S =</span> Sn), <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-2"><a href=""></a><span class="fu">lines</span>(Sn, <span class="fu">plogis</span>(pr<span class="sc">$</span>fit))                       <span class="co"># exp() for a log link</span></span>
<span id="cb3-3"><a href=""></a><span class="fu">lines</span>(Sn, <span class="fu">plogis</span>(pr<span class="sc">$</span>fit <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> pr<span class="sc">$</span>se.fit), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb3-4"><a href=""></a><span class="fu">lines</span>(Sn, <span class="fu">plogis</span>(pr<span class="sc">$</span>fit <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> pr<span class="sc">$</span>se.fit), <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>A band that is symmetric on the link scale becomes <strong>asymmetric</strong> on the response scale — and can never cross 0 or 1. That is a feature, not a bug.</p>
</div>
</section>
<section id="a-categorical-predictor-height-and-sex" class="slide level2">
<h2>A categorical predictor: height and sex</h2>

<img data-src="presentation3_regression_files/figure-revealjs/fig77-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>Dormann’s Figs. 7.6–7.7 (data simulated to his summary statistics). Behind the scenes R recodes the factor as 0/1, alphabetically: Female = 0 is the <strong>reference level</strong>. The intercept (173.1) is then the mean of the reference group and the “slope” <code>sexMale</code> (12.9) is the <strong>difference</strong> between the groups: males average 173.1 + 12.9 = 186.0 cm. The test of <code>sexMale</code> against 0 is the test for a sex difference — the classic <em>t</em>-test is nothing but this regression.</p>
</div>
</section>
<section id="the-null-model-and-what-a-predictor-buys-us" class="slide level2">
<h2>The null model, and what a predictor buys us</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a>fm0 <span class="ot">&lt;-</span> <span class="fu">glm</span>(height <span class="sc">~</span> <span class="dv">1</span>,   <span class="at">data =</span> hgt, <span class="at">family =</span> gaussian)   <span class="co"># intercept only</span></span>
<span id="cb4-2"><a href=""></a>fm1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(height <span class="sc">~</span> sex, <span class="at">data =</span> hgt, <span class="at">family =</span> gaussian)</span>
<span id="cb4-3"><a href=""></a><span class="fu">rbind</span>(<span class="st">`</span><span class="at">height ~ 1</span><span class="st">`</span>   <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">coef</span>(fm0), <span class="at">sexMale =</span> <span class="cn">NA</span>, <span class="at">deviance =</span> <span class="fu">deviance</span>(fm0), <span class="at">df =</span> <span class="fu">df.residual</span>(fm0), <span class="at">AIC =</span> <span class="fu">AIC</span>(fm0)),</span>
<span id="cb4-4"><a href=""></a>      <span class="st">`</span><span class="at">height ~ sex</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">coef</span>(fm1),               <span class="at">deviance =</span> <span class="fu">deviance</span>(fm1), <span class="at">df =</span> <span class="fu">df.residual</span>(fm1), <span class="at">AIC =</span> <span class="fu">AIC</span>(fm1)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             (Intercept) sexMale deviance df      AIC
height ~ 1        179.59      NA 13191.93 99 776.0067
height ~ sex      173.14    12.9  9031.68 98 740.1201</code></pre>
</div>
</div>
<div class="fignote">
<p>The <strong>null model</strong> fits one grand mean (179.6) and leaves 99 residual degrees of freedom. Spending <strong>one</strong> extra parameter on sex cuts the residual deviance from 13 262 to 9 102 and the AIC by 36 — a huge improvement. That is the logic of every regression: reduce the leftover noise as much as possible with as few parameters as possible. With a normal distribution and an identity link the G in GLM is idle; <code>lm()</code> gives identical answers.</p>
</div>
</section>
<section id="more-than-two-levels-dummy-variables" class="slide level2 smaller">
<h2>More than two levels: dummy variables</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a><span class="fu">head</span>(<span class="fu">model.matrix</span>(<span class="sc">~</span> colour, <span class="at">data =</span> bfly[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">21</span>, <span class="dv">22</span>, <span class="dv">41</span>, <span class="dv">42</span>), , <span class="at">drop =</span> <span class="cn">FALSE</span>]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) colourred colouryellow
1            1         0            0
2            1         0            0
21           1         1            0
22           1         1            0
41           1         0            1
42           1         0            1</code></pre>
</div>
</div>

<img data-src="presentation3_regression_files/figure-revealjs/fig78-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>A factor with <em>k</em> levels becomes <em>k</em> − 1 columns of 0/1 <strong>dummies</strong> plus the intercept; you never build them yourself. Dormann’s butterflies: time until birds detect blue, red or yellow morphs. Waiting times are skewed — a <strong>gamma</strong> GLM (inverse link) or a log-normal (<code>log(time)</code> with gaussian) are the candidates. The intercept is <code>blue</code>; <code>colourred</code> and <code>colouryellow</code> are differences from blue <em>on the link scale</em>.</p>
</div>
</section>
<section id="two-models-for-the-same-question-which-to-trust" class="slide level2">
<h2>Two models for the same question — which to trust?</h2>
<div class="smallout">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<colgroup>
<col style="width: 24%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 9%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">(Intercept)</th>
<th style="text-align: right;">colourred</th>
<th style="text-align: right;">colouryellow</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">deviance explained</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">gamma, inverse link</td>
<td style="text-align: right;">0.132</td>
<td style="text-align: right;">-0.039</td>
<td style="text-align: right;">0.060</td>
<td style="text-align: right;">329.153</td>
<td style="text-align: right;">0.239</td>
</tr>
<tr class="even">
<td style="text-align: left;">log(time), gaussian</td>
<td style="text-align: right;">1.914</td>
<td style="text-align: right;">0.352</td>
<td style="text-align: right;">-0.463</td>
<td style="text-align: right;">105.915</td>
<td style="text-align: right;">0.271</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="fignote">
<p>Same data, two distributions, coefficients that look nothing alike because the link scales differ: for the gamma fit the fitted mean for blue is 1/0.11 ≈ 9 s and a <em>larger</em> coefficient for yellow means a <em>shorter</em> time; for the log-normal fit the yellow effect is negative. Both say yellow is found sooner. <strong>The AICs cannot be compared</strong> — one model is fitted to <code>time</code>, the other to <code>log(time)</code>: different data. Compare instead the <strong>deviance explained</strong>, (null − residual)/null. In Dormann’s data the log-normal did better (14 % vs 9 %).</p>
</div>
</section>
<section id="the-χ²-test-is-a-binomial-glm" class="slide level2">
<h2>The χ²-test is a binomial GLM</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href=""></a><span class="fu">table</span>(smoke<span class="sc">$</span>sex, smoke<span class="sc">$</span>smoker)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
          0  1
  Female 26 12
  Male   14  1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a>fm.s <span class="ot">&lt;-</span> <span class="fu">glm</span>(smoker <span class="sc">~</span> sex, <span class="at">data =</span> smoke, <span class="at">family =</span> binomial)</span>
<span id="cb10-2"><a href=""></a><span class="fu">round</span>(<span class="fu">summary</span>(fm.s)<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)   -0.773      0.349  -2.215    0.027
sexMale       -1.866      1.092  -1.708    0.088</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a><span class="fu">c</span>(<span class="at">female =</span> <span class="fu">plogis</span>(<span class="fu">coef</span>(fm.s)[[<span class="dv">1</span>]]), <span class="at">male =</span> <span class="fu">plogis</span>(<span class="fu">sum</span>(<span class="fu">coef</span>(fm.s))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    female       male 
0.31578947 0.06666667 </code></pre>
</div>
</div>
<div class="fignote">
<p>The 2 × 2 table of Chapter 5 in long format: one row per person, 0/1 smoker, sex as predictor — a Bernoulli GLM. <code>plogis()</code> of the intercept gives 0.316, exactly 12/38, the proportion of women who smoke; the intercept plus the <code>sexMale</code> effect back-transforms to 0.067 = 1/15. The difference is not significant (<em>p</em> = 0.088), the same conclusion as the χ²-test (<em>p</em> = 0.122). Correlation, <em>t</em>-test, χ²-test: all special cases of one model.</p>
</div>
</section>
<section id="dispersion-is-the-scatter-what-the-distribution-promises" class="slide level2 smaller">
<h2>Dispersion: is the scatter what the distribution promises?</h2>

<img data-src="presentation3_regression_files/figure-revealjs/overdisp-1.png" width="1350" class="r-stretch"><div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">x</th>
<th style="text-align: right;">SE(x)</th>
<th style="text-align: right;">resid. dev / df</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Poisson</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">14.58</td>
<td style="text-align: right;">9811.60</td>
</tr>
<tr class="even">
<td style="text-align: left;">neg. binomial</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">4377.43</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="fignote">
<p>For the normal distribution σ is <em>estimated</em>; for Poisson and binomial the variance is <em>fixed</em> by the mean, so we must <strong>check</strong> it: residual deviance / residual df should be ≈ 1. Dormann’s simulated counts (<code>set.seed(101)</code>, Sect. 8.3) come from a negative binomial with θ = e: the Poisson ratio is ≫ 1 — <strong>overdispersion</strong>. The fitted line is the same, but the Poisson standard error is far too small and its <em>p</em>-values far too optimistic. <code>glm.nb()</code> (package <code>MASS</code>) estimates θ and repairs the standard errors.</p>
</div>
</section>
<section id="beyond-glm-a-non-linear-curve" class="slide level2">
<h2>Beyond <code>glm()</code>: a non-linear curve</h2>

<img data-src="presentation3_regression_files/figure-revealjs/micmen-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>Michaelis–Menten kinetics, <code>vmkm</code> from <code>nlstools</code> (Dormann, Sect. 8.2.2): <em>v</em> ~ N(μ = <em>v</em><sub>max</sub>·<em>S</em>/(<em>K</em><sub>M</sub> + <em>S</em>) + <em>B</em>, σ). No link function makes this a straight line, so <code>glm()</code> cannot fit it — but <code>optim()</code> does not care about the shape of μ. Two tricks: a <strong>named</strong> parameter vector, and estimating <strong>log σ</strong> so that σ stays positive whatever the optimiser tries (a link function for σ). <em>t</em> = estimate/SE judges the parameters; <em>B</em> is not significant.</p>
</div>
</section>
<section id="modelling-something-other-than-the-mean" class="slide level2">
<h2>Modelling something other than the mean</h2>

<img data-src="presentation3_regression_files/figure-revealjs/hyena-1.png" width="1350" class="r-stretch"><div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">lower</th>
<th style="text-align: right;">upper</th>
<th style="text-align: right;">t</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mean (both sexes)</td>
<td style="text-align: right;">2.04</td>
<td style="text-align: right;">1.86</td>
<td style="text-align: right;">2.25</td>
<td style="text-align: right;">15.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">clumping, males</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">-5.44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">clumping, females : males</td>
<td style="text-align: right;">39.01</td>
<td style="text-align: right;">5.47</td>
<td style="text-align: right;">278.19</td>
<td style="text-align: right;">3.73</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="fignote">
<p>Spotted hyenas (Dormann, Sect. 8.4; simulated): 200 males and 200 females, <strong>same mean</strong> of 2 offspring — but a few males sire most of the cubs. So we model the negative binomial’s <strong>clumping parameter</strong> as a function of sex, holding the mean constant. Females are far less clumped than males (Dormann finds 13.6 vs 0.46, a factor ≈ 30). The CIs are computed on the link scale (± 2 SE) and back-transformed: hence <strong>asymmetric</strong> — and very wide for the ratio, though clearly above 1 (<em>t</em> ≫ 1.65). Any parameter of any distribution can be made a function of predictors — the only limits are the data and your imagination.</p>
</div>
</section>
<section id="the-same-curve-several-routes-not-the-same-answer" class="slide level2">
<h2>The same curve, several routes — not the same answer</h2>

<img data-src="presentation3_regression_files/figure-revealjs/routes-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>All three fit an exponential ln μ = <em>a</em> + <em>b</em>·<em>x</em>, yet the slopes differ. They assume different <strong>noise</strong>: <code>lm(log(y))</code> puts normal scatter on the log scale (so the noise grows with the mean and the back-transformed line sits <em>below</em> the mean); the log-link gaussian GLM puts constant normal scatter on the original scale; the Poisson lets the variance equal the mean. The curve is the same <em>shape</em>; the distribution decides which points get how much say. And remember: the AIC of <code>lm(log(y))</code> is not comparable with the others.</p>
</div>
</section>
<section id="what-you-will-do-in-practical-3" class="slide level2 smaller">
<h2>What you will do in practical 3</h2>
<ol type="1">
<li><strong>Poisson GLM</strong> of species richness against beach height (<code>RIKZdat</code>): read the output, back-transform, deviance explained, dispersion, and draw the curve with its confidence band — on both scales</li>
<li>a <strong>factor</strong> as predictor (<code>slugs</code>): dummies, <code>model.matrix()</code>, <code>relevel()</code>, overdispersion and <code>glm.nb()</code></li>
<li>a <strong>binomial GLM</strong> with <code>cbind(y, n - y)</code> (<code>wells</code>): <code>plogis()</code>, <code>dose.p()</code>, and the χ²-test as a GLM</li>
<li>the <strong>species–area power law</strong> (<code>gala</code>): Poisson, negative binomial and <code>lm(log(S))</code> compared</li>
<li>the Poisson regression <strong>by hand</strong>: <code>llfun()</code>, profile, contour surface, <code>optim()</code> and standard errors from the Hessian</li>
<li>a <strong>Michaelis–Menten</strong> curve for pollen removal by bees (<code>beepollen</code>)</li>
<li>exponential <strong>decay</strong> fitted by three routes — and why they disagree</li>
<li>bear growth (<code>beargrowth</code>): a <strong>standard deviation that grows with age</strong></li>
</ol>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Everything you need is <code>glm()</code>, <code>glm.nb()</code>, <code>summary()</code>, <code>coef()</code>, <code>predict()</code>, <code>exp()</code>, <code>plogis()</code>, <code>dose.p()</code>, <code>model.matrix()</code>, <code>dpois()</code>/<code>dnorm()</code>/<code>dbinom()</code> with <code>log = TRUE</code>, and <code>optim()</code>.</p>
</div>
</div>
</div>
</section>
<section id="take-home-messages" class="slide level2 smaller">
<h2>Take-home messages</h2>
<ol type="1">
<li>A regression is a distribution whose <strong>parameter depends on a predictor</strong>: <em>y</em> ~ Dist(θ = f(<em>x</em>)). Fitting it is <strong>maximum likelihood</strong>, as before.</li>
<li>The <strong>link function</strong> keeps fitted values legal (positive counts, probabilities in 0–1). Coefficients, predictions and standard errors live on the <strong>link scale</strong>; back-transform with <code>exp()</code> / <code>plogis()</code> — SEs <em>before</em> back-transforming.</li>
<li><code>summary(glm())</code>: estimate ± SE with a test against 0; <strong>null vs residual deviance</strong> for the fit; <strong>dispersion</strong> ≈ 1 or you are <strong>overdispersed</strong> (→ <code>glm.nb()</code>); AIC only for models fitted to the same response.</li>
<li>A <strong>factor</strong> becomes 0/1 dummies: the intercept is the reference level, the other coefficients are differences. The <em>t</em>-test and χ²-test are GLMs.</li>
<li>Draw the line over the observed range only, <strong>with</strong> its 95 % confidence band (<code>predict(..., se.fit = TRUE)</code>); the band is about the line, not about new data.</li>
<li>When <code>glm()</code> cannot do it — non-linear curves, other distributions, a variance that changes with <em>x</em> — write the <strong>likelihood function</strong> and let <code>optim()</code> climb; the <strong>Hessian</strong> gives the standard errors.</li>
</ol>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="presentation3_regression_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="presentation3_regression_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="presentation3_regression_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="presentation3_regression_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="presentation3_regression_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="presentation3_regression_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="presentation3_regression_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="presentation3_regression_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="presentation3_regression_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="presentation3_regression_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>