<!DOCTYPE html>
<html lang="en"><head>
<script src="presentation5_multiple_regression_files/libs/clipboard/clipboard.min.js"></script>
<script src="presentation5_multiple_regression_files/libs/quarto-html/tabby.min.js"></script>
<script src="presentation5_multiple_regression_files/libs/quarto-html/popper.min.js"></script>
<script src="presentation5_multiple_regression_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="presentation5_multiple_regression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="presentation5_multiple_regression_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="presentation5_multiple_regression_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Emiel van Loon">
  <meta name="dcterms.date" content="2026-09-23">
  <title>Multiple Regression: More than One Predictor</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="presentation5_multiple_regression_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="presentation5_multiple_regression_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="presentation5_multiple_regression_files/libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link href="presentation5_multiple_regression_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="presentation5_multiple_regression_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="presentation5_multiple_regression_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="presentation5_multiple_regression_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Multiple Regression: More than One Predictor</h1>
  <p class="subtitle">Dormann (2020), <em>Environmental Data Analysis</em> — Chapters 15 and 16</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Emiel van Loon 
</div>
</div>
</div>

  <p class="date">2026-09-23</p>
</section>
<section class="slide level2">

<style>
.reveal .fignote { font-size: 0.60em; line-height: 1.35; }
.reveal .fignote code { font-size: 0.95em; }
.reveal table { font-size: 0.72em; }
.reveal pre code { font-size: 0.75em; line-height: 1.25; }
.reveal .tight { font-size: 0.80em; line-height: 1.3; }
.reveal .tight2 { font-size: 0.72em; line-height: 1.3; }
</style>
</section>
<section id="where-we-are-going" class="slide level2 smaller">
<h2>Where we are going</h2>
<div class="tight">
<p>Every model so far had <strong>one</strong> predictor. Adding a second one is, in principle, just one more row in the coefficient table — but four things get complicated. At the end of this chapter you should…</p>
<ul>
<li>be able to <strong>visualise</strong> data and models with two predictors (panels, symbols, image/contour plots)</li>
<li>know what a statistical <strong>interaction</strong> is, how it is coded, how you recognise it in a figure and in the output, and how to <em>read the equations</em> from a coefficient table</li>
<li>recognise <strong>collinearity</strong> between predictors, know what it does to a model (VIF) and what to do about it</li>
<li>understand <strong>model selection</strong>: the marginality principle, AIC vs BIC vs likelihood-ratio test, backward stepwise selection and best-subset regression — and their pitfalls</li>
</ul>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Skipped from Dormann: principal component analysis (15.3.1, 16.2.1), the two-way ANOVA by hand (15.4.1) and the matrix algebra (15.5). Practical 5 is a <em>reading</em> practical: you interpret output, you do not write code.</p>
</div>
</div>
</div>
</section>
<section id="one-more-predictor-what-changes" class="slide level2 smaller">
<h2>One more predictor: what changes?</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">z value</th>
<th style="text-align: right;">Pr(&gt;|z|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.2354</td>
<td style="text-align: right;">0.1920</td>
<td style="text-align: right;">6.43</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: right;">-0.0043</td>
<td style="text-align: right;">0.0052</td>
<td style="text-align: right;">-0.82</td>
<td style="text-align: right;">0.413925</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sexmale</td>
<td style="text-align: right;">-2.4607</td>
<td style="text-align: right;">0.1523</td>
<td style="text-align: right;">-16.16</td>
<td style="text-align: right;">0.000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="tight">
<p>Survival of 1046 Titanic passengers, <code>survived ~ age + sex</code>. Each predictor gets its own maximum-likelihood estimate; a 42-year-old man survives with probability <span class="math inline">\(\mathrm{logit}^{-1}(1.235 - 0.00425 \cdot 42 - 2.46) = 0.20\)</span>. Nothing new — except that four complications now arise:</p>
<ol type="1">
<li><strong>Visualising</strong> — a figure has only two axes</li>
<li><strong>Interactions</strong> — the effect of one predictor may depend on the other</li>
<li><strong>Collinearity</strong> — predictors that carry the same information</li>
<li><strong>Model selection</strong> — which of the many candidate models to report</li>
</ol>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>“Multiple” regression = several predictors, one response. (<em>Multivariate</em> statistics means several <em>responses</em> — a different topic.)</p>
</div>
</div>
</div>
</section>
<section id="visualising-two-categorical-predictors" class="slide level2">
<h2>1. Visualising two categorical predictors</h2>

<img data-src="presentation5_multiple_regression_files/figure-revealjs/cormorant-vis-1.png" width="1575" class="r-stretch"><div class="fignote">
<p>Dive times of two European cormorant subspecies, <em>P. carbo carbo</em> (C) and <em>P. c.&nbsp;sinensis</em> (S), in four seasons (Dormann Figs 15.1, 15.2). <strong>Panel plots</strong> (left, middle) give a quick overview; an <strong>all-in-one plot</strong> (right) needs more work but takes less space. Either way we see the same thing: dive time increases over the year in <em>both</em> subspecies, and the smaller <em>sinensis</em> dives a little shorter. A continuous <em>x</em> works the same way — one panel, or one symbol, per level of the factor.</p>
</div>
</section>
<section id="visualising-binary-data-smooth-first" class="slide level2">
<h2>Visualising binary data: smooth first</h2>

<img data-src="presentation5_multiple_regression_files/figure-revealjs/titanic-vis-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>Titanic survival against age (Dormann Figs 15.3–15.5). A panel or scatter plot of 0/1 data shows <strong>nothing</strong> (left). A <strong>moving average</strong> (LOESS: a local regression in a sliding window, span 0.2 / 0.5 / 0.75 from dark to light) makes the pattern visible: women survived at a high rate at every age, men’s survival dropped steeply with age. The window width is a choice — narrow traces the data, wide smooths it. Note the two curves are <em>not parallel</em>: that is an interaction.</p>
</div>
</section>
<section id="interactions-when-one-effect-depends-on-the-other" class="slide level2">
<h2>2. Interactions: when one effect depends on the other</h2>

<img data-src="presentation5_multiple_regression_files/figure-revealjs/interaction-idea-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>What does a plant need to grow? Water <em>and</em> light. More light helps — <strong>but only if there is enough water</strong>. That is a statistical interaction: the effect of one predictor depends on the value of the other (Dormann Fig. 15.6). In a figure you recognise it as lines with <strong>different slopes</strong>; parallel lines mean purely additive effects. Tropical trees grow because heat and rain come in the right combination; on the Titanic the effect of age depends on sex.</p>
</div>
</section>
<section id="how-an-interaction-enters-the-model-multiply" class="slide level2 smaller">
<h2>How an interaction enters the model: multiply</h2>
<div class="columns">
<div class="column" style="width:42%;">
<div class="tight">
<table class="caption-top">
<thead>
<tr class="header">
<th>passenger</th>
<th>sex</th>
<th>age</th>
<th>sex × age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Miss Allen</td>
<td>female (0)</td>
<td>29.0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Master Allison</td>
<td>male (1)</td>
<td>0.9</td>
<td>0.9</td>
</tr>
<tr class="odd">
<td>Mrs Allison</td>
<td>female (0)</td>
<td>25.0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Mr Anderson</td>
<td>male (1)</td>
<td>48.0</td>
<td>48.0</td>
</tr>
</tbody>
</table>
<p>The factor is a <strong>dummy</strong> (0/1). Multiplying it with age gives a new variable that is <em>zero for all women</em> — an effect of age that applies to men only. <code>R</code> does this for you: <code>age * sex</code> means <code>age + sex + age:sex</code>.</p>
</div>
</div><div class="column" style="width:58%;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">z value</th>
<th style="text-align: right;">Pr(&gt;|z|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.4934</td>
<td style="text-align: right;">0.2542</td>
<td style="text-align: right;">1.94</td>
<td style="text-align: right;">0.052257</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0.0225</td>
<td style="text-align: right;">0.0085</td>
<td style="text-align: right;">2.64</td>
<td style="text-align: right;">0.008342</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sexmale</td>
<td style="text-align: right;">-1.1541</td>
<td style="text-align: right;">0.3393</td>
<td style="text-align: right;">-3.40</td>
<td style="text-align: right;">0.000671</td>
</tr>
<tr class="even">
<td style="text-align: left;">age:sexmale</td>
<td style="text-align: right;">-0.0463</td>
<td style="text-align: right;">0.0112</td>
<td style="text-align: right;">-4.13</td>
<td style="text-align: right;">0.000037</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="tight">
<ul>
<li><strong>age</strong> = the slope of age <em>for women</em> (the reference level): +0.023 per year</li>
<li><strong>sexmale</strong> = the difference men − women <em>at age 0</em></li>
<li><strong>age:sexmale</strong> = how much <em>steeper</em> the age slope is for men: −0.046, so men: 0.023 − 0.046 = <strong>−0.024</strong> per year</li>
</ul>
<p>42-year-old man: <span class="math inline">\(\mathrm{logit}^{-1}(0.49 + 0.0225\cdot42 - 1.15 - 0.046\cdot42) = 0.11\)</span>; 42-year-old woman: the last two terms are × 0 → 0.73.</p>
</div>
</div></div>
<div class="fignote">
<p>Two <em>continuous</em> predictors: the product is taken directly; <strong>positive</strong> = synergistic, <strong>negative</strong> = antagonistic (standardise first, or the larger one dominates). Beware: an unmodelled <em>quadratic</em> effect can masquerade as a significant interaction — test polynomials as well (Dormann footnote 4).</p>
</div>
</section>
<section id="reading-the-anova-table-sequential-and-the-marginality-principle" class="slide level2 smaller">
<h2>Reading the ANOVA table: sequential, and the marginality principle</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Deviance</th>
<th style="text-align: right;">Resid. Df</th>
<th style="text-align: right;">Resid. Dev</th>
<th style="text-align: right;">Pr(&gt;Chi)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NULL</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1045</td>
<td style="text-align: right;">1414.6</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.2</td>
<td style="text-align: right;">1044</td>
<td style="text-align: right;">1411.4</td>
<td style="text-align: right;">0.071959</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sex</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">310.0</td>
<td style="text-align: right;">1043</td>
<td style="text-align: right;">1101.3</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">age:sex</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">17.9</td>
<td style="text-align: right;">1042</td>
<td style="text-align: right;">1083.4</td>
<td style="text-align: right;">0.000023</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="tight">
<p><code>anova(fm)</code> adds the terms <strong>one after the other</strong> (“sequentially”): each row tests what a term adds <em>on top of the rows above it</em>. Age alone explains almost nothing (<em>P</em> = 0.41); sex explains a lot; the interaction explains 17.9 more units — highly significant.</p>
</div>
<div class="tight">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>Do not conclude “age does not matter”.</strong> The significant interaction says that the main effects <em>alone</em> do not describe the pattern: the sexes differ strongly, but <em>not</em> among young children. Once an interaction is in the model, its <strong>main effects must stay</strong> — even if not significant — because the interaction <em>contains</em> them (Nelder’s <strong>marginality principle</strong>). And do not rank importance by the deviance column: with correlated predictors the order of the terms changes the numbers (but never the residual deviance).</p>
</div>
</div>
</div>
</div>
</section>
<section id="two-categorical-predictors-cormorants-additive-vs-interaction" class="slide level2 smaller">
<h2>Two categorical predictors: cormorants, additive vs interaction</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">13.49</td>
<td style="text-align: right;">0.58</td>
</tr>
<tr class="even">
<td style="text-align: left;">seasonsummer</td>
<td style="text-align: right;">3.23</td>
<td style="text-align: right;">0.74</td>
</tr>
<tr class="odd">
<td style="text-align: left;">seasonautumn</td>
<td style="text-align: right;">7.37</td>
<td style="text-align: right;">0.74</td>
</tr>
<tr class="even">
<td style="text-align: left;">seasonwinter</td>
<td style="text-align: right;">11.59</td>
<td style="text-align: right;">0.74</td>
</tr>
<tr class="odd">
<td style="text-align: left;">subspeciesS</td>
<td style="text-align: right;">-3.26</td>
<td style="text-align: right;">0.52</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Deviance</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">season</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">759.8</td>
<td style="text-align: right;">95.3</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">subspecies</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">106.0</td>
<td style="text-align: right;">39.9</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">season:subspecies</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">10.6</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">0.284</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="presentation5_multiple_regression_files/figure-revealjs/cormorant-plot-1.png" width="660"></p>
</figure>
</div>
</div>
</div>
</div></div>
<div class="fignote">
<p>Left: coefficients of the additive model and <code>anova(divetime ~ season * subspecies)</code>. The <strong>intercept</strong> is the reference cell (spring, C: 13.5 min); the season coefficients are differences from spring, <code>subspeciesS</code> the difference S − C (−3.3 min). A fitted value is a <strong>sum of coefficients</strong>: <em>sinensis</em> in autumn = 13.5 + 7.4 − 3.3 = 17.6 (or <code>predict()</code>). The interaction (3 df) is <em>not</em> significant (<em>F</em> = 1.4, <em>P</em> = 0.27): near-parallel lines, so we report the additive model. <span class="math inline">\(R^2\)</span> = 90%: season 79%, subspecies 11% (partial <span class="math inline">\(R^2\)</span> from the deviance column).</p>
</div>
</section>
<section id="continuous-categorical-the-four-models-of-an-ancova" class="slide level2">
<h2>Continuous + categorical: the four models of an ANCOVA</h2>

<img data-src="presentation5_multiple_regression_files/figure-revealjs/tet-four-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>Diameter of <em>Tetrahymena</em> cells against culture density, with and without added glucose (Dormann Fig. 16.4; data after Dalgaard 2002). A model with a continuous and a categorical predictor is traditionally called <strong>ANCOVA</strong> — “analysis of covariance” — only for nostalgic reasons: it is just a GLM. (<strong>a</strong>) one mean; (<strong>b</strong>) one regression line; (<strong>c</strong>) two means; (<strong>d</strong>) the additive model <code>diameter ~ log10(conc) + glucose</code>: <strong>two parallel lines</strong> — the factor shifts the intercept, the slope is shared.</p>
</div>
</section>
<section id="the-fifth-model-one-slope-per-group" class="slide level2 smaller">
<h2>The fifth model: one slope per group</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="presentation5_multiple_regression_files/figure-revealjs/tet-int-plot-1.png" width="690"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">37.559</td>
<td style="text-align: right;">0.988</td>
<td style="text-align: right;">38.03</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">lconc</td>
<td style="text-align: right;">-2.861</td>
<td style="text-align: right;">0.202</td>
<td style="text-align: right;">-14.19</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">glucoseYes</td>
<td style="text-align: right;">-1.122</td>
<td style="text-align: right;">1.219</td>
<td style="text-align: right;">-0.92</td>
<td style="text-align: right;">0.3618</td>
</tr>
<tr class="even">
<td style="text-align: left;">lconc:glucoseYes</td>
<td style="text-align: right;">0.662</td>
<td style="text-align: right;">0.248</td>
<td style="text-align: right;">2.67</td>
<td style="text-align: right;">0.0104</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="tight2">
<p>Read the two lines straight from the table:</p>
<ul>
<li>without glucose (reference): <span class="math inline">\(\hat y = 37.6 - 2.86 \cdot \log_{10}(\mathrm{conc})\)</span></li>
<li>with glucose: intercept <strong>and</strong> slope get their extra term: <span class="math inline">\(\hat y = (37.6 - 1.1) + (-2.86 + 0.66) \cdot \log_{10}(\mathrm{conc})\)</span></li>
</ul>
<p>The interaction is significant (<em>P</em> = 0.01): the <strong>slopes differ</strong>. The glucose main effect (<em>P</em> = 0.36) is the intercept difference <em>at log10(conc) = 0</em> — far outside the data, and it must stay in the model anyway.</p>
</div>
</div></div>
<div class="fignote">
<p>Dormann Figs 16.3 / 16.5: lines only over the data range, 95% bands via <code>predict(..., interval = "confidence")</code> and <code>matlines()</code>. “Glucose does have an effect, but it is only detectable if we take the cell concentration into account.”</p>
</div>
</section>
<section id="two-continuous-predictors-c3-grasses-in-north-america" class="slide level2 smaller">
<h2>Two continuous predictors: C3 grasses in North America</h2>
<div class="columns">
<div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="presentation5_multiple_regression_files/figure-revealjs/paruelo-pairs-1.png" width="630"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:55%;">
<div class="tight2">
<p>Proportion of C3 grasses (√-transformed) at 73 sites (Paruelo &amp; Lauenroth 1996) against mean annual precipitation (MAP), temperature (MAT) and the fraction of summer (JJAMAP) and winter rain (DJFMAP).</p>
<p><strong>Step 0: check the predictors.</strong> Summer and winter rain are strongly negatively correlated (<em>r</em> = −0.79 &gt; 0.7): keep only one — JJAMAP, because growth happens in summer.</p>
<p><strong>Step 1: the full model</strong> <code>sqC3 ~ MAP * MAT * JJAMAP</code> — 3 main effects, 3 two-way and 1 three-way interaction.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum Sq</th>
<th style="text-align: right;">F value</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">MAP</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.9859</td>
</tr>
<tr class="even">
<td style="text-align: left;">MAT</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.962</td>
<td style="text-align: right;">35.78</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">JJAMAP</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.100</td>
<td style="text-align: right;">1.83</td>
<td style="text-align: right;">0.1808</td>
</tr>
<tr class="even">
<td style="text-align: left;">MAP:MAT</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">0.54</td>
<td style="text-align: right;">0.4647</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MAP:JJAMAP</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">0.5928</td>
</tr>
<tr class="even">
<td style="text-align: left;">MAT:JJAMAP</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.282</td>
<td style="text-align: right;">5.14</td>
<td style="text-align: right;">0.0267</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MAP:MAT:JJAMAP</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.9554</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div></div>
<div class="fignote">
<p>Only <code>MAT:JJAMAP</code> is significant, so the reduced model keeps <code>MAP + MAT * JJAMAP</code> (<span class="math inline">\(R^2_{adj}\)</span> = 0.36 — “not too shabby for ecological data”). <code>JJAMAP</code> and <code>MAT</code> are not significant on their own but are part of the interaction, so they stay. Only MAP can be interpreted directly: more rain, more C3 grasses.</p>
</div>
</section>
<section id="visualising-an-interaction-of-two-continuous-predictors" class="slide level2">
<h2>Visualising an interaction of two continuous predictors</h2>

<img data-src="presentation5_multiple_regression_files/figure-revealjs/paruelo-surface-1.png" width="1350" class="r-stretch"><div class="fignote">
<p>Dormann Figs 16.7–16.9. Two predictors plus a response need a <strong>surface</strong>: <code>outer()</code> evaluates <code>predict()</code> on a grid, <code>image()</code> colours it, <code>contour()</code> labels it — here at the mean MAP. The effect of temperature is steepest where summer rain is high: a continuous change of slope, the interaction. <strong>Always add the data points</strong> and their convex hull: the empty corners (hot <em>and</em> summer-wet) contain no observations, and predictions there have no basis. With every extra dimension this “curse of dimensionality” gets worse. Slices (right) are the poor man’s effect plot.</p>
</div>
</section>
<section id="collinearity-two-predictors-that-say-the-same-thing" class="slide level2 smaller">
<h2>3. Collinearity: two predictors that say the same thing</h2>
<div class="columns">
<div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="presentation5_multiple_regression_files/figure-revealjs/gala-collin-1.png" width="600"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">lArea</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">lElev</th>
<th style="text-align: right;">SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Species ~ lArea</td>
<td style="text-align: right;">0.367</td>
<td style="text-align: right;">0.036</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Species ~ lElev</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.761</td>
<td style="text-align: right;">0.127</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Species ~ lArea + lElev</td>
<td style="text-align: right;">0.389</td>
<td style="text-align: right;">0.065</td>
<td style="text-align: right;">-0.065</td>
<td style="text-align: right;">0.165</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="tight">
<p>VIF of the two-predictor model: 3.3 — the variance of each coefficient is 3.3 × what it would be with uncorrelated predictors (SE of <code>lArea</code>: 0.036 → 0.065).</p>
</div>
</div></div>
<div class="tight2">
<p>Bigger islands are higher. Alone, each predictor is “highly significant”; put both in and elevation drops to zero with a doubled standard error. Two problems (Dormann 15.3): we <strong>cannot attribute</strong> the effect to one of them (interpretation), and the likelihood surface becomes a flat ridge, so estimates are <strong>unstable and their errors inflated</strong> (estimation).</p>
</div>
<div class="tight2">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Diagnose <strong>before</strong> modelling: <code>cor()</code> / <code>pairs()</code> — |<em>r</em>| &lt; 0.7 is safe. After modelling: <code>car::vif()</code> — values above 10 (Appalachian soils: 65,655!) mean a predictor has to go. The remedy in this course: keep one representative of each correlated group (Dormann’s PCA and cluster analysis are the alternatives).</p>
</div>
</div>
</div>
</div>
</section>
<section id="model-selection-how-many-models-and-which-one" class="slide level2 smaller">
<h2>4. Model selection: how many models, and which one?</h2>
<div class="columns">
<div class="column" style="width:58%;">
<div class="tight">
<p><strong>The full model</strong> contains every predictor you consider reasonable, with interactions (and polynomials). Rule of thumb: <strong>5–10 data points per model term</strong> (Harrell) — 100 observations allow ~10 terms; for 0/1 data count the rarer outcome.</p>
<p>With 14 terms there are <span class="math inline">\(2^{14}\)</span> = 16 384 sub-models. Three strategies:</p>
<ul>
<li><strong>backward stepwise</strong>: start full, drop the term whose removal improves the criterion most, repeat (<code>step()</code>)</li>
<li><strong>forward stepwise</strong>: start empty, add — <em>strongly discouraged</em>: a predictor that only matters in an interaction never gets in</li>
<li><strong>best subset</strong>: fit <em>all</em> sub-models and rank them (<code>MuMIn::dredge()</code>)</li>
</ul>
</div>
</div><div class="column" style="width:42%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="presentation5_multiple_regression_files/figure-revealjs/bias-variance-1.png" width="600"></p>
</figure>
</div>
</div>
</div>
</div></div>
<div class="fignote">
<p>Why not always keep the full model? It fits <em>these</em> data best and its estimates are unbiased — but it <strong>traces the data set</strong>. The <strong>variance–bias trade-off</strong> (schematic): with more terms the fit to the training data always improves, the error on new data first drops and then rises. Information criteria — AIC, BIC — balance fit (log-likelihood) against complexity (number of parameters) to find that minimum; BIC penalises harder and prefers smaller models. And every stepwise removal is a test, so selection distorts the <em>p</em>-values that survive.</p>
</div>
</section>
<section id="comparing-two-candidate-models-aic-bic-and-the-lr-test" class="slide level2 smaller">
<h2>Comparing two candidate models: AIC, BIC and the LR test</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 28%">
<col style="width: 3%">
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 21%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">log-likelihood</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">LR test: deviance</th>
<th style="text-align: right;">P (chi-sq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1: survived ~ age + sex</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-550.7</td>
<td style="text-align: right;">1107.3</td>
<td style="text-align: right;">1122.2</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">2: survived ~ age * sex</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">-541.7</td>
<td style="text-align: right;">1091.4</td>
<td style="text-align: right;">1111.2</td>
<td style="text-align: right;">17.9</td>
<td style="text-align: right;">2.32e-05</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="tight">
<p>Dormann’s Table 15.1: two ways to compare the additive and the interaction model of Titanic survival.</p>
<ul>
<li><strong>AIC / BIC</strong>: lower is better; a difference of <strong>≥ 2 units is substantial</strong> (they live on the log-likelihood scale: 3.6 units ≈ 37-fold likelihood). Model 2 wins by 16 (AIC) and 11 (BIC) units.</li>
<li><strong>Likelihood-ratio test</strong> (<code>anova(m1, m2, test = "Chisq")</code>): only for <em>nested</em> models; the deviance difference is <span class="math inline">\(\chi^2\)</span> with df = difference in parameters. Here 17.9 on 1 df, <em>P</em> &lt; 0.0001.</li>
<li>For quasi-models there is no likelihood, hence no AIC: use <code>test = "F"</code>.</li>
</ul>
</div>
<div class="tight">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The criteria do not always agree — on the Titanic test data the simpler model even had the better <span class="math inline">\(R^2\)</span>. Which criterion, you decide <strong>beforehand</strong>; AIC (or BIC) is currently the standard.</p>
</div>
</div>
</div>
</div>
</section>
<section id="backward-stepwise-selection-with-step-reading-the-output" class="slide level2 smaller">
<h2>Backward stepwise selection with <code>step()</code>: reading the output</h2>
<pre><code>Start:  AIC=999.41
surv ~ sex * age * passengerClass

                         Df Deviance    AIC
- sex:age:passengerClass  2   917.84 987.37
&lt;none&gt;                        915.98 999.41</code></pre>
<div class="tight">
<p>The full Titanic model <code>sex * age * passengerClass</code> (8 terms), first step of a BIC selection (<code>k = log(n)</code>). At every step <code>step()</code> tries to remove <strong>each removable term</strong> — only the three-way interaction here, because every other term is part of it (marginality!) — and lists the candidates by the criterion. <code>&lt;none&gt;</code> is the current model; anything <strong>above</strong> <code>&lt;none&gt;</code> improves the model when dropped, so the top term goes and the procedure repeats until <code>&lt;none&gt;</code> is on top.</p>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 69%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">criterion</th>
<th style="text-align: left;">final model</th>
<th style="text-align: right;">terms</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">full model</td>
<td style="text-align: left;">sex * age * passengerClass</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">940.0</td>
<td style="text-align: right;">999.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">backward by AIC</td>
<td style="text-align: left;">sex + age + passengerClass + sex:age + sex:passengerClass + age:passengerClass</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">937.8</td>
<td style="text-align: right;">987.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">backward by BIC</td>
<td style="text-align: left;">sex + age + passengerClass + sex:passengerClass</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">946.0</td>
<td style="text-align: right;">980.7</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="fignote">
<p>AIC keeps all two-way interactions; BIC ends with <code>sex:passengerClass</code> only. Dormann’s warning: stepwise selection looks <strong>one step ahead</strong> — a removal that only pays off together with a second one is never found, so an AIC-driven <code>step()</code> can stop at a model with a <em>worse</em> AIC than a BIC-selected one. Not a panacea (Austin &amp; Tu 2004); it gets more reliable with more data per term.</p>
</div>
</section>
<section id="best-subset-regression-fit-them-all-then-weigh" class="slide level2 smaller">
<h2>Best-subset regression: fit them all, then weigh</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">lArea</th>
<th style="text-align: left;">lElev</th>
<th style="text-align: left;">lNear</th>
<th style="text-align: left;">lAdj</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">delta</th>
<th style="text-align: right;">weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0.376</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">-0.123</td>
<td style="text-align: left;"></td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">273.4</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.28</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.367</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">274.0</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">0.21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0.375</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">-0.130</td>
<td style="text-align: left;">-0.030</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">274.7</td>
<td style="text-align: right;">1.29</td>
<td style="text-align: right;">0.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.371</td>
<td style="text-align: left;">0.017</td>
<td style="text-align: left;">-0.125</td>
<td style="text-align: left;"></td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">275.4</td>
<td style="text-align: right;">1.99</td>
<td style="text-align: right;">0.10</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="tight2">
<p><code>MuMIn::dredge()</code> fits all <span class="math inline">\(2^4\)</span> = 16 negative-binomial models of Galapagos plant richness (<code>na.action = na.fail</code> makes every model use the same rows). Shown: the models within 2 AIC units of the best.</p>
<ul>
<li><strong>delta</strong> = AIC distance to the best model; within 2 units = equivalent</li>
<li><strong>weight</strong> = each model’s share of the “evidence” (all 16 sum to 1): the best model holds only 29% — there is no single winner</li>
<li><code>lArea</code> is in <strong>every</strong> competitive model, <code>lNear</code> in most, <code>lElev</code> and <code>lAdj</code> only occasionally and with coefficients near 0 (<code>lElev</code> is collinear with area)</li>
</ul>
</div>
<div class="tight2">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Dredging is criticised as “fishing”: afterwards we act as if we had planned this one model, so its <strong>p-values and confidence intervals are wrong</strong> (point predictions are fine). Whatever you do — say what you did.</p>
</div>
</div>
</div>
</div>
</section>
<section id="what-you-will-do-in-practical-5" class="slide level2 smaller">
<h2>What you will do in practical 5</h2>
<div class="tight2">
<p>No code to write — you <strong>read and interpret</strong> output, as you would in a paper:</p>
<ol type="1">
<li><strong>Two factors</strong> (<code>birdmalariaO</code>): reconstruct the four group means from the coefficients of <code>Sex * mmal</code>; read a sequential ANOVA table; additive or interaction model?</li>
<li><strong>ANCOVA</strong> (<code>regrowth</code>): why the boxplot and the coefficient disagree about grazing; two parallel lines from one table; why the order of terms changes the deviance</li>
<li><strong>Continuous × factor interaction</strong> (<code>wells</code>, quasi-binomial): two logit equations; non-significant main effects that must stay; <em>F</em> instead of χ²</li>
<li><strong>Negative binomial with interaction</strong> (<code>RIKZdat</code>): slopes per exposure class, LR test with 2 df, AIC ranking of four models, back-transforming with <code>exp()</code></li>
<li><strong>Collinearity</strong> (<code>gala</code>): |<em>r</em>| &gt; 0.7, VIF, what happens to elevation once area is in the model</li>
<li><strong>Two continuous predictors</strong> (<code>loyn</code>): slopes at grazing 1 and 5, image/contour plot and the empty corners</li>
<li><strong>Model selection</strong> (<code>loyn</code>): a <code>step()</code> table, AIC vs BIC results, a <code>dredge()</code> table with delta and weight — and the caveat about the p-values</li>
</ol>
</div>
</section>
<section id="take-home-messages" class="slide level2 smaller">
<h2>Take-home messages</h2>
<div class="tight2">
<ol type="1">
<li>A second predictor is one more coefficient — but brings four problems: <strong>visualising, interactions, collinearity, model selection</strong>.</li>
<li>Visualise with panels or symbols; smooth binary data (LOESS); for two continuous predictors draw the surface (<code>outer</code> → <code>image</code> + <code>contour</code>) <strong>with the data points on it</strong>.</li>
<li>An <strong>interaction</strong> = the effect of one predictor depends on the other: non-parallel lines; coded as the <em>product</em>; the coefficient is the change in slope. Main effects then refer to the <em>reference level</em> / <em>x = 0</em> and must <strong>stay in the model</strong> (marginality).</li>
<li>Read the fitted equations from the table: reference group = intercept + slope; other groups add their extra intercept <strong>and</strong> extra slope.</li>
<li><code>anova()</code> of one model is <strong>sequential</strong> — order matters when predictors are correlated; <code>anova(m1, m2)</code> compares two nested models.</li>
<li><strong>Collinearity</strong> (|<em>r</em>| &gt; 0.7, VIF &gt; 10) makes effects unattributable and estimates unstable: check the predictors <em>before</em> modelling, keep one per group.</li>
<li>Compare candidate models by <strong>AIC/BIC</strong> (≥ 2 units) or an LR test; simplify <strong>backwards</strong> (<code>step()</code>, BIC for small <em>n</em>) or search all subsets (<code>dredge()</code>, weights); never forward. Selected models have optimistic <em>p</em>-values — say so.</li>
</ol>
</div>
<div class="tight2">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Dormann, C. F. (2020). <em>Environmental Data Analysis: An Introduction with Examples in R</em>, Chapters 15 and 16. Springer. Data: <code>carData::TitanicSurvival</code>, <code>ISwR::hellung</code>, Paruelo &amp; Lauenroth (1996) via Quinn &amp; Keough (2002), <code>qsbsdata::gala</code>.</p>
</div>
</div>
</div>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="presentation5_multiple_regression_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="presentation5_multiple_regression_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="presentation5_multiple_regression_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="presentation5_multiple_regression_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="presentation5_multiple_regression_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="presentation5_multiple_regression_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="presentation5_multiple_regression_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="presentation5_multiple_regression_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="presentation5_multiple_regression_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="presentation5_multiple_regression_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'mathjax/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>